pytorch/TensorRT

tests/core/converters/test_linear.cpp
tests/models/BUILD
tests/models/test_multiple_registered_engines.cpp
tests/util/run_graph.cpp

type GraphParams is std::map
plus some build fixes

Fix indeterministic params order in `RunGraph`

---

tests/BUILD

Tests still hang, probably something like out of GPU memeory need to pick
the right settings for bazel to run them

fix(//tests): Forgot to change this path to modules

---

third_party/cuda/BUILD

refactor(//third_party/cuda): Relax .so restriction on cudart so its

---

py/trtorch/__init__.py

Fix the libpath to register with torch

fix(//py): Lib path incorrect

---

core/conversion/conversion.cpp

fix(//core/conversion): Supress unnecessary debug messages

---

core/compiler.cpp
core/conversion/converters/NodeConverterRegistry.cpp
core/execution/TRTEngine.cpp
core/execution/execution.h
core/util/macros.h

Adds a destructor and code clean up of the execution class. Also add some lints

Adds a destructor for the new class that was previously in the old execution manager

---

core/conversion/converters/impl/shuffle.cpp
tests/core/converters/test_shuffle.cpp

Implements support for `torch.Tensor.permute`
Closes #91 

Implement permute support

---

core/conversion/converters/impl/pooling.cpp
tests/core/converters/test_pooling.cpp

Adds support for the rest of basic pooling operations
Fixes #11

Fills out basic pooling operations

---

.github/ISSUE_TEMPLATE/op-converter-request.md

tools(//.github): Add a converter request template

---

core/conversion/evaluators/aten.cpp

aten::add_.t evaluator support, which adds lists together in-place

Support for aten::add_.t operation

---

.github/ISSUE_TEMPLATE/bug-report.md

chore: adding a bug issue template

---

cpp/trtorchc/main.cpp

Fixes an issue where trtorchc was not using the newly updated C++ APIs
Fixes #132

fix(//cpp/trtorchc): Refactor trtorchc to use new C++ API

---

WORKSPACE
core/conversion/converters/impl/conv_deconv.cpp
core/conversion/converters/impl/interpolate.cpp
core/conversion/converters/impl/plugins/interpolate_plugin.cpp
notebooks/Dockerfile.notebook
notebooks/README.md
notebooks/WORKSPACE.notebook
third_party/tensorrt/local/BUILD

Fixes the network container to work with the new build system layout. Also fixes the TensorRT paths for local x86 builds

Fix notebook container

---

core/conversion/converters/converters.h
core/conversion/converters/impl/activation.cpp
core/util/trt_util.cpp
core/util/trt_util.h
tests/core/converters/test_activation.cpp

Implements prelu and a broadcasting checker
Closes #150 
Closes #5 

Implements prelu and a broadcasting checker

---

README.md

Windows support is possible now but it is going to be a lower priority unofficially supported platform. 
Signed-off-by: "Naren Dasan <naren@narendasan.com>"
Signed-off-by: "Naren Dasan <narens@nvidia.com>"

docs: Document unofficial windows support

---

core/compiler.cpp
core/execution/register_trt_op.cpp

Move to public APIs for operator registration
Fixes #131 
- Refactor

refactor(//core/execution): Move to public APIs for operator registration

---

core/conversion/conversion.cpp
core/conversion/conversionctx/ConversionCtx.h
core/conversion/converters/BUILD
core/conversion/converters/impl/lstm_cell.cpp
core/execution/TRTEngine.cpp
core/execution/execution.h
core/execution/register_trt_op.cpp
core/lowering/lowering.cpp
core/lowering/passes/BUILD
core/lowering/passes/conv3d_to_convolution.cpp
core/lowering/passes/passes.h
tests/core/converters/BUILD
tests/core/converters/test_lstm_cell.cpp
tests/util/run_graph_engine.cpp

LSTMCell converter
function schema: `lstm_cell(Tensor input, Tensor[] hx, Tensor w_ih, Tensor w_hh, Tensor? b_ih=None, Tensor? b_hh=None) -> (Tensor, Tensor)`
Fixes #108 

LSTMCell converter

---

core/execution/register_trt_op.cpp
docker/Dockerfile.20.07

Signed-off-by: Naren Dasan <naren@narendasan.com
Make it easier to run applications in the repo with the cuda11 container

refactor(//docker): Make it easier to run applications in the repo with the container

---

core/lowering/lowering.cpp

Add functionalization pass to replace inplace operators
Fixes #30 

feat(//core/lowering): Add functionalization pass to replace inplace operators

---

py/setup.py

Thanks to @mneilly for catching this
Fixes #192 

fix(//py): Fix long description section of setup.py

---

core/BUILD

Remove old backend.h from core includes

fix(//core): Remove old backend.h from core includes

---

.github/scripts/run_cpp_linter.py
.github/scripts/run_py_linter.py
.github/workflows/linter.yml
.github/workflows/stale.yml
docker/Dockerfile.docs
tools/linter/cpplint_diff.py
tools/linter/pylint_diff.py
tools/linter/utils.py

Fixes for the linter and integration into github workflows

Linter fix

---

.github/scripts/run_cpp_linter.py
.github/scripts/run_py_linter.py
.github/workflows/linter.yml

tools(//.github): fix reading from json

---

core/conversion/converters/impl/select.cpp
tests/core/converters/test_select.cpp

Support for aten::embedding conversion
Fixes https://github.com/NVIDIA/TRTorch/issues/102

feat(//converters): Add aten::embedding conversion functionality

---

.github/scripts/run_cpp_linter.py
.github/scripts/run_py_linter.py
.github/workflows/linter.yml

feat(//.github): Moving to python directly

---

core/conversion/converters/impl/element_wise.cpp
tests/core/converters/test_element_wise.cpp

Uni19 dev:  element wise operators support dynamic shape input and broadcast #223 

---

.gitignore
notebooks/Dockerfile.notebook
notebooks/WORKSPACE.notebook

Updates notebook container for 0.1.0. 
Fixes #244 
- Version updates

feat(//notebooks): Update notebooks container for 0.1.0

---

docker/Dockerfile.20.10
docker/README.md
docker/WORKSPACE.cu.docker

Update docker container for Pytorch 1.7.1
Create document for using docker
Fix small bug in existing docker file

Update docker container for Pytorch 1.7.1

---

core/lowering/passes/remove_to.cpp
tests/core/lowering/BUILD
tests/core/lowering/test_remove_to.cpp

This PR fixes the remove_to lowering pass (h/t @inocsin) and adds a basic test for it

Fix remove to pass

---

core/conversion/converters/impl/element_wise.cpp
tests/core/conversion/converters/test_element_wise.cpp

This adds support for the following logic operators (h/t @inocsin)
- aten::gt
- aten::lt
- aten::le
- aten::ge
- aten::eq

Adding support for basic logic operators

---

core/conversion/converters/impl/unary.cpp
tests/core/conversion/converters/test_unary.cpp

Add converters for erf/asinh/acosh/atanh

Add converters of erf/asinh/acosh/atanh

---

py/README.md

This code is not working now. 
I could run example code with this correction.
There is typo in [example code](https://github.com/NVIDIA/TRTorch/blob/master/py/README.md).
Fixes # (issue[https://github.com/NVIDIA/TRTorch/issues/335])

fix typo in example code

---

docsrc/index.rst

docs: fix link in index

---

core/conversion/converters/impl/activation.cpp
tests/core/conversion/converters/test_activation.cpp

Add ELU converter to our core library.

add ELU converter to core library

---

core/conversion/converters/impl/reduce.cpp
tests/core/conversion/converters/test_reduce.cpp

support aten::mean with negative dim

support aten::mean with negative dim

---

core/conversion/evaluators/aten.cpp
tests/core/conversion/evaluators/test_aten_evaluators.cpp

Please merge this PR after https://github.com/NVIDIA/TRTorch/pull/324
Fixes https://github.com/NVIDIA/TRTorch/issues/105
Add converter aten::arange

Add converter aten::arange

---

docker/Dockerfile.docs

refactor(//docker): Update docs container

---

core/partitioning/shape_analysis.cpp

Seems this feature was removed after refactor

feat: support prim::Param for input type after refactor

---

core/conversion/converters/impl/expand.cpp

fix aten::expand and aten::repeat compilation failure of IValue input

fix: support expand/repeat with IValue type input

---

core/conversion/converters/impl/shuffle.cpp
tests/core/conversion/converters/test_shuffle.cpp

Support pixel_shuffle converter
Fixes #271 

Support pixel_shuffle converter

---

.github/scripts/run_cpp_linter.py
.github/scripts/run_py_linter.py
cpp/ptq/training/vgg16/export_ckpt.py
cpp/ptq/training/vgg16/main.py
py/trtorch/_compile_spec.py

refactor: Fix python linting issues

---

core/conversion/conversionctx/ConversionCtx.cpp

feat(//core/conversion/conversionctx): Adding logging for truncated

---

core/conversion/converters/converter_util.cpp
core/conversion/converters/converter_util.h
core/conversion/converters/impl/batch_norm.cpp
core/conversion/converters/impl/conv_deconv.cpp
core/conversion/converters/impl/pooling.cpp
core/util/trt_util.cpp
tests/core/conversion/converters/test_pooling.cpp

refactor: Applying linting

---

core/partitioning/README.md

Documentation to illustrate the overall internals of partitioning phase as well as automatic fallback APIs. 
- Documentation for current feature

doc: documentation for partitioning phase as well as automatic fallback APIs

---

py/trtorch/ptq.py

Fixes ptq tests. More context : https://github.com/NVIDIA/TensorRT/issues/1186#issuecomment-822113987

Fix pybind empty buffer issue

---

docker/Dockerfile.21.03

Adding new docker container to go along with TRTorch 0.3.0
Fixes #387 

feat(//docker): Adding Docker 21.03

---

py/setup.py

chore(//py): Fix version number

---

core/conversion/converters/impl/pooling.cpp
core/plugins/impl/interpolate_plugin.cpp
core/plugins/impl/interpolate_plugin.h
core/plugins/impl/normalize_plugin.cpp
core/plugins/impl/normalize_plugin.h
tests/core/conversion/converters/test_pooling.cpp

Add adaptive max pool2d plugin to the new plugins interface. Add changes in the PR https://github.com/NVIDIA/TRTorch/pull/328 to the latest codebase. 

feat(//core/plugins): Add adaptive_max_pool2d plugin, enable the plugins to run on GPU

---

py/trtorch/ptq.py

Use len() to get size of dataset
Fixes https://github.com/NVIDIA/TRTorch/issues/498

fix: Use len() to get size of dataset

---

core/conversion/converters/impl/lstm_cell.cpp
tests/core/conversion/converters/test_lstm_cell.cpp

This PR introduces a TRTorch converter for the Gated Recurrent Unit (GRU) cell, as requested by Issue #109. Also includes tests for the converter, both with and without the bias term.
Fixes #109

GRU Cell Converter

---

core/conversion/converters/impl/batch_norm.cpp
core/conversion/converters/impl/conv_deconv.cpp
core/conversion/converters/impl/pooling.cpp

Signed-off-by: Boris Fomitchev <bfomitchev@nvidia.com>
Fixes #522  (issue)
Added checks to bail out in case of obviously wrong dimension counts.

Fixing issue #552

---

core/conversion/converters/impl/concat.cpp
tests/core/conversion/converters/test_concat.cpp

Adds support for negative dim for cat
Fixes #541

fix(aten::cat): support neg dim for cat

---

core/lowering/BUILD
core/lowering/LowerInfo.cpp
core/lowering/lowering.cpp
core/lowering/lowering.h
py/trtorch/_compiler.py
py/trtorch/csrc/tensorrt_classes.cpp

Extra logging and utilities to use for debugging 
-

feat(//core/lowering): additional logging in module fallback

---

core/lowering/lowering.cpp
core/lowering/passes/BUILD
core/lowering/passes/module_fallback.cpp
core/lowering/passes/passes.h
core/lowering/register_trt_placeholder_ops.cpp

feat(//core/lowering): Adding two passes, one to delimit and one to mark

---

cpp/ptq/main.cpp
tests/accuracy/BUILD
tests/accuracy/test_int8_accuracy.cpp

fixing bad accuracy in just the example code

fix(//cpp/ptq): fixing bad accuracy in just the example code

---

tests/BUILD
tests/accuracy/test_dla_fp16_accuracy.cpp
tests/accuracy/test_dla_int8_accuracy.cpp

Some slight changes to the jetson optional tests

fix(//tests): fix optional jetson tests

---

tests/modules/README.md
tests/modules/requirements.txt

chore: doc fix

---

WORKSPACE
core/lowering/lowering.cpp
core/lowering/passes/module_fallback.cpp

Updates cuDNN version to the latest available.
- Chore

Patch update/0.4/bump cudnn version 8.2.3

---

WORKSPACE

Update base cuDNN version to latest

chore: Updating base cuDNN version to v8.2.4.15

---

docker/Dockerfile

Update default base container to 21.10. 
Fixes #694 

fix: Update base container for dockerfile

---

cpp/bin/torchtrtc/main.cpp

Min block size was setup incorrectly

fix(//cpp/bin/torchtrtc): Fix mbs

---

core/conversion/converters/impl/activation.cpp
core/lowering/lowering.cpp
core/lowering/passes/BUILD
core/lowering/passes/passes.h
core/lowering/passes/reduce_gelu.cpp
tests/core/conversion/converters/test_activation.cpp
tests/core/lowering/BUILD
tests/core/lowering/test_reduce_gelu.cpp

Implement fast approximation of Gelu to improve performance (eg: BERT model)

feat: Implement fast approximation of Gelu to improve performance 

---

tests/accuracy/BUILD

fix: Fix BUILD file for tests/accuracy

---

core/partitioning/README.md

chore: Update partitioning readme

---

notebooks/Resnet50-example.ipynb
notebooks/lenet-getting-started.ipynb
notebooks/ssd-object-detection-demo.ipynb
notebooks/vgg-qat.ipynb

Added ipywidget dependency in Notebooks

fix: Added ipywidget dependency to notebook

---

tests/py/test_api.py

Disabled Mobilenet_V2 test for DLFW CI. 
This test will be enabled once the integration with DLFW has been successful.

fix: Disabled mobilenet_v2 test for DLFW CI

---

tests/py/test_api.py

Fix for failure with compilation for scripted models in DLFW integration

fix: Fix for torch scripted module faiure with DLFW

---

core/lowering/passes/fuse_addmm_branches.cpp

fix: Fix fuse addmm pass

---

examples/benchmark/py/README.md
examples/benchmark/py/config/vgg16.yml
examples/benchmark/py/config/vgg16_trt.yml
examples/benchmark/py/perf_run.py
examples/benchmark/py/requirements.txt

This benchmark script runs perf inference for different configurable backends. (Torch, Torch-TensorRT and TensorRT)
It ingests configurable yaml based configurations to run models with target precisions, devices etc.

feat: Added a comprehensive perf benchmark script in Python

---

docker/dist-accuracy-test.sh
noxfile.py
tests/README.md

Added support for Python accuracy tests using Nox. Using nox, one can run complete python tests more conveniently.

feat: Added Python accuracy and API tests using Nox for NGC branch

---

README.md

Added resources (mainly links to documentation) to the Readme
Updated Readme

Added resources to the readme

---

core/compiler.cpp
core/conversion/conversion.cpp

Change unsupported operators log level to DEBUG

chore: Change unsupported operators log level to DEBUG

---

core/conversion/conversion.cpp
core/conversion/converters/converter_util.cpp
core/conversion/converters/converter_util.h

Fix when TRT prunes away an output
Fixes https://github.com/NVIDIA/Torch-TensorRT/issues/728

fix: Fix when TRT prunes away an output

---

WORKSPACE
docker/Dockerfile.docs

Updates the dependency container to include TRT 8.2 
- [x ] New and existing unit tests pass locally with my changes

chore: Update CI container deps

---

README.md
core/conversion/converters/BUILD
cpp/bin/torchtrtc/main.cpp
tests/core/conversion/converters/BUILD

https://github.com/NVIDIA/Torch-TensorRT/pull/831 credits to @chengyute @p1x31 

feat: Add converter for reflection pad 1d and 2d operation

---

core/conversion/converters/impl/reflection_pad.cpp
tests/core/conversion/converters/test_reflection_pad.cpp

Missing files of https://github.com/NVIDIA/Torch-TensorRT/pull/895

feat: Add converter files for reflection pad 1d and 2d

---

README.md
WORKSPACE

feat: Upgrade TensorRT to 8.2.4.2

---

README.md
WORKSPACE
core/conversion/evaluators/eval_util.cpp
core/lowering/passes/linear_to_addmm.cpp
core/partitioning/shape_analysis.cpp
py/requirements.txt
tests/core/conversion/evaluators/test_aten_evaluators.cpp
tests/cpp/test_modules_as_engines.cpp
tests/modules/requirements.txt
tests/py/requirements.txt
tests/util/util.h
third_party/libtorch/BUILD

Update Pytorch version to 1.11

feat: Update Pytorch version to 1.11

---

tests/core/lowering/test_reduce_to_pass.cpp

Update the test code for aten::to for ngc. 
Fixes #958 

fix: update the test for aten::to for ngc branch

---

docsrc/index.rst
notebooks/CitriNet-example.ipynb
notebooks/README.md

Adding citrinet demo
New feature (non-breaking change which adds functionality)
Checklist:

Adding citrinet demo

---

docsrc/index.rst
notebooks/Hugging-Face-BERT.ipynb

Added a tutorial notebook for optimizing a Hugging Face BERT transformer for masked language modeling. This replaces the defunct PR 978, which I had messed up first by not signing my commit messages properly and then in attempting to fix my mistake. 

Added a tutorial notebook for optimizing a Hugging Face BERT transformer for masked language modeling

---

core/conversion/converters/impl/select.cpp
core/lowering/register_trt_placeholder_ops.cpp
tests/core/conversion/converters/test_select.cpp

Add converter for torch.unbind

feat (core//conversion) : Add converter for torch.unbind

---

core/lowering/register_trt_placeholder_ops.cpp

refactor: apply linting

---

noxfile.py

refactor(//nox): Add version detection

---

core/lowering/passes/exception_elimination.cpp
tests/core/lowering/BUILD
tests/core/lowering/test_exception_elimination_pass.cpp

Signed-off-by: Michael Feliz <michael.feliz@getcruise.com>
Fixes incorrect pattern matching in exception elimination and adds unit tests.
Fixes # [(issue)](https://github.com/NVIDIA/Torch-TensorRT/issues/1027)

fix: Resolve issues in exception elimination pass

---

core/lowering/passes/linear_to_addmm.cpp

chore: Typo fix. Stray semicolon in core file 

---

py/Dockerfile
py/build_whl.sh

chore: update the release system for python

---

notebooks/CitriNet-example.ipynb
notebooks/EfficientNet-example.ipynb
notebooks/Hugging-Face-BERT.ipynb
notebooks/dynamic-shapes.ipynb
notebooks/lenet-getting-started.ipynb
notebooks/ssd-object-detection-demo.ipynb
notebooks/vgg-qat.ipynb

Fixed Typos in the dynamic shapes notebook
Fixed Typo

fixed typos

---

py/torch_tensorrt/fx/README.md

[docs] Update link to relative path

---

tests/modules/hub.py

fix: fix the model name typo error

---

py/torch_tensorrt/ptq.py

Fix PTQ calibration when there are multiple inputs

fix: Fix PTQ calibration when there are multiple inputs

---

notebooks/EfficientNet-example.ipynb

Fix typo in EfficientNet-example

---

.gitignore
core/ir/CMakeLists.txt

fix: Update cmake for the new collection files

---

.circleci/config.yml

Updates the base pytorch version for jetson

chore: update jetson pytorch baase

---

README.md
core/conversion/converters/impl/element_wise.cpp
core/conversion/converters/impl/select.cpp
core/conversion/converters/impl/shuffle.cpp

Update release 1.2

---

examples/int8/training/vgg16/finetune_qat.py

Fix dataloader for finetune_qat script

chore: Fix dataloader in finetune_qat script

---

.github/workflows/linter.yml

* fix(tools): Fix linter to not depend on docker
Signed-off-by: Naren Dasan <1790613+narendasan@users.noreply.github.com>
* Update linter.yml
* Update linter.yml
Signed-off-by: Naren Dasan <1790613+narendasan@users.noreply.github.com>

fix(tools): Fix linter to not depend on docker (#1301)

---

docsrc/getting_started/getting_started_with_windows.rst
docsrc/tutorials/getting_started_with_fx_path.rst

chore: apply linting to docs

---

docker/WORKSPACE.ngc

chore: Update torch installation paths for NGC

---

tests/core/partitioning/test_shape_analysis.cpp
tests/core/partitioning/test_type_auto_conversion.cpp

fix: fix failed test cases caused by partition API changes

---

core/runtime/execute_engine.cpp

chore: remove debug statements from execute_engine

---

README.md

ATT. Make it easier to check the health of main trunk. 

add circle CI signal in README page

---

core/conversion/converters/impl/einsum.cpp
tests/core/conversion/converters/test_einsum.cpp

fix eisum signature

---

README.md

Fix typo in https://github.com/pytorch/TensorRT/pull/1481

Fix link to CircleCI in README.md

---

README.md
core/BUILD
core/conversion/converters/impl/einsum.cpp
tests/core/conversion/converters/test_einsum.cpp
tests/cpp/test_serialization.cpp

Remove compilation warning in test. 
Remove redundant fixes in build rule. 

Minor changes

---

WORKSPACE

chore: Update URLS and sha for cudnn and TensorRT

---

docs/_sources/tutorials/ptq.rst.txt
examples/fx/hugging_face_torchdynamo_example.py
examples/fx/torchdynamo_example.py
py/torch_tensorrt/fx/converters/acc_ops_converters.py
py/torch_tensorrt/fx/lower.py
py/torch_tensorrt/fx/test/converters/acc_op/test_cat.py
py/torch_tensorrt/fx/test/converters/acc_op/test_gelu.py
py/torch_tensorrt/fx/test/converters/acc_op/test_new_ones.py
py/torch_tensorrt/fx/test/converters/acc_op/test_to_dtype.py
py/torch_tensorrt/fx/test/converters/acc_op/test_unary_ops.py
py/torch_tensorrt/fx/test/core/test_trt_module.py
py/torch_tensorrt/fx/test/passes/test_setitem_trt.py
py/torch_tensorrt/fx/test/tools/test_model_packager.py
py/torch_tensorrt/fx/test/tracer/test_acc_tracer.py
py/torch_tensorrt/fx/test/tracer/test_dispatch_tracer.py
py/torch_tensorrt/fx/tools/common_fx2trt.py
py/torch_tensorrt/fx/tracer/acc_tracer/acc_ops.py
py/torch_tensorrt/fx/tracer/acc_tracer/acc_tracer.py
py/torch_tensorrt/fx/tracer/acc_tracer/acc_utils.py

cherry-pick newest change from master branch

---

.github/actions/assigner/dist/index.js
.github/actions/assigner/src/main.ts
.github/code-owners.yml

tools: assign 1 person to a bug instead of all

---

.circleci/config.yml
py/torch_tensorrt/fx/converters/aten_ops_converters.py
py/torch_tensorrt/fx/converters/convolution.py
py/torch_tensorrt/fx/lower.py
py/torch_tensorrt/fx/passes/lower_pass_manager_builder.py
py/torch_tensorrt/fx/test/converters/aten_op/test_maxpool_aten.py
py/torch_tensorrt/fx/test/converters/aten_op/test_reshape_aten.py
py/torch_tensorrt/fx/test/passes/test_fuse_permute_linear_trt.py
py/torch_tensorrt/fx/test/tracer/test_acc_tracer.py
py/torch_tensorrt/fx/test/tracer/test_dispatch_tracer.py
py/torch_tensorrt/fx/test/tracer/test_resnet.py
py/torch_tensorrt/fx/tools/common_fx2trt.py
py/torch_tensorrt/fx/tracer/acc_tracer/acc_ops.py
py/torch_tensorrt/fx/tracer/dispatch_tracer/aten_tracer.py

483102cd4151f02c2d3632e6b6df7a5e59c0d6f3 Wei Wei <wwei6@meta.com> [fx2trt] move acc op `torch.ops._caffe2.RoIAlign` to fb only 
8ce94a01caa090d56adb4708452b52890160ba69 Wei Wei <wwei6@meta.com> [aten2trt] reshape support c13a2b67f460e4dfacad2ac2a7ac537593a1c23b wwei6 <wwei6@fb.com> [aten2trt] resnet18 support
- This change …

[FX] Changes done internally at Facebook

---

py/torch_tensorrt/fx/passes/lower_basic_pass_aten.py

- Update dependencies to stable PyTorch 2.0
- CI testing

chore/fix: Repair FX CI on Stable 2.0

---

core/conversion/converters/impl/select.cpp
tests/core/conversion/converters/test_select.cpp

Add converter support for `aten::where.ScalarOther`.

feat: Add support for aten::where with scalar other

---

py/torch_tensorrt/dynamo/fx_ts_compat/fx2trt.py

- Fixes CI failure due to refactor from #1955 caused by merge with later changes made on `main`

minor fix: Dynamo CI fix due to merge issue

---

.circleci/config.yml

- CI is not running due to the GPU class - update to `gpu.nvidia.medium`
- CI fix

fix: Update CI GPU Class

---

README.md

docs: Update readme to include TRT as a seperate install dep.

---

py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
py/torch_tensorrt/dynamo/conversion/impl/unary/ops.py

The` cast_trt_tensor` has been moved to the `torch_tensorrt/dynamo/conversion/impl/unary/ops.py`. Removing this from `aten_ops_converters`

neg converter correction

---

py/torch_tensorrt/dynamo/backend/backends.py
tests/py/dynamo/backend/test_backend_compiler.py

- Add test case for validating backend membership in list
Fixes #2057
- Backend name reservation

fix: Register tensorrt backend name

---

py/requirements.txt
pyproject.toml

- Fixes Docker builds on `main` failing due to dependency resolution OOM.
- CI verification

fix: Update Torchvision version to address dependency resolution issue

---

py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py

Minor fix to `get_ir` function

minor fix: Update `get_ir` prefixes

---

py/torch_tensorrt/dynamo/lowering/_decomposition_groups.py

- Necessary decomposition for many models which use the unsafe index variant

feat: Decomposition for `_unsafe_index`

---

docsrc/index.rst
docsrc/user_guide/dynamo_export.rst
docsrc/user_guide/saving_models.rst

Cherry-pick : Add documentation for dynamo.compile backend (#2389)

---

py/torch_tensorrt/dynamo/lowering/_decomposition_groups.py

- Provides full coverage for VIT operators in Dynamo
- Decomposition addition

feat: Add `aten.unbind` decomposition for VIT

---

.github/workflows/docker_builder.yml

- Cherry-pick of #2437
- Cherry-pick
- [ - ] My code follows the style guidelines of this project (You can use the linters)
- [ - ] I have performed a self-review of my own code
- [ - ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ - ] I have made corresponding changes to the documentation
- [ - ] New and existing unit tests pass locally with my changes
- [ - ] I have added the relevant labels to my PR in so that relevant reviewers are notified

cherry-pick/minor fix: Parse out slashes in Docker container name (#2437)

---

.github/workflows/docker_builder.yml
docsrc/index.rst

- Fix rendering here: https://pytorch.org/TensorRT/, in "Contributor Documentation"
- Update syntax in Docker build
- Docs rendering fix
- [ - ] My code follows the style guidelines of this project (You can use the linters)
- [ - ] I have performed a self-review of my own code
- [ - ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ - ] I have made corresponding changes to the documentation
- [ - ] New and existing unit tests pass locally with my changes
- [ - ] I have added the relevant labels to my PR in so that relevant reviewers are notified

fix: Docs rendering on PyTorch site

---

docsrc/dynamo/dynamo_export.rst
docsrc/user_guide/saving_models.rst
py/torch_tensorrt/dynamo/_exporter.py

chore: fix docs for export

---

tools/perf/benchmark.sh

Minor fix for benchmark script to avoid TRT OOM

minor fix: Update Benchmark values

---

tools/perf/benchmark.sh

Minor benchmark fix cherry-pick to `release/2.1` - #2453

minor fix: Update Benchmark values (#2453)

---

tools/perf/accumulate_results.py
tools/perf/benchmark.sh
tools/perf/perf_run.py

- Cherry-pick of #2466
- Cherry-pick

cherry-pick: Wrap perf benchmarks with no_grad (#2466)

---

py/torch_tensorrt/dynamo/tools/opset_coverage.py

- Fix small typo in opset coverage tool for release branch

fix: Naming issue in opset coverage tool

---

core/conversion/converters/impl/conv_deconv.cpp

chore: fix deconv padding

---

.github/workflows/build-test.yml
requirements-dev.txt

- CI repair by specifying `expecttest==0.1.6`

fix: Specify expecttest version to fix CI

---

py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
py/torch_tensorrt/dynamo/conversion/impl/activation/ops.py
py/torch_tensorrt/dynamo/conversion/impl/elementwise/ops.py
tests/py/dynamo/conversion/test_clamp_aten.py
tests/py/dynamo/conversion/test_clip_aten.py

support `aten.clamp.Tensor` and update `aten.clamp.default` dynamo converters
Fixes #2517 

feat: support aten.clamp.Tensor and update aten.clamp.default dynamo converters

---

py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
py/torch_tensorrt/dynamo/conversion/impl/normalization/ops.py
tests/py/dynamo/conversion/test_pdist_aten.py

Support `_pdist_forward` dynamo converter
Fixes #2568 

feat: support _pdist_forward dynamo converter

---

py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
py/torch_tensorrt/dynamo/conversion/impl/unary/ops.py
tests/py/dynamo/conversion/test_scalar_tensor_aten.py

Support `aten.scalar_tensor` dynamo converter.
Fixes #2593 

feat: support aten.scalar_tensor dynamo converter

---

.github/workflows/docker_builder.yml

- Fix Docker build job on GHA
- Infra fix (non-breaking change which fixes an issue)

fix: Add write permissions to Docker GHA

---

.github/workflows/docker_builder.yml

Cherry-pick of
- #2600 
- #2619
- Cherry-pick

cherry-pick: Docker fixes `release/2.2`

---

tests/core/conversion/converters/BUILD

test_instance_norm - Fails with plugin not found
test_scaled_dot_product_attention - Fails with op not found in pytorch
cc: @apbose 

chore: patch 24.02 failing tests

---

noxfile.py
tests/core/conversion/converters/BUILD
tests/py/dynamo/lowering/test_aten_lowering_passes.py

patch test_hw_compatibility and restrict flash attention test to sm >=86
cc: @apbose 

chore: patch test_hw_compatibility and restrict flash attention test to sm >=86

---

.github/workflows/linux-test.yml
WORKSPACE
docker/dist-build.sh
py/requirements.txt
toolchains/ci_workspaces/WORKSPACE.x86_64.release.rhel.tmpl

- Fix failing Docker build for `release/2.2` branch
- Upgrade versions of `torchvision` and `libtorch` to stable variants

fix: Upgrade versions for Docker build rel 2.2

---

docker/Dockerfile

- Remove blocking + unnecessary keyserver fetch in `Dockerfile`
- Docker build fix

fix: Remove keyserver fetch from Dockerfile

---

docker/Dockerfile

- Cherry-pick of #2639
- Cherry-pick

cherry-pick: Remove keyserver fetch from Dockerfile (#2639)

---

.github/scripts/install-torch-tensorrt.sh

- CI Fix with version and package index upgrades
- CI fix

fix: Update index in installer for CI failures

---

README.md
py/requirements.txt
pyproject.toml

- Upgrade nightly version to `2.4.0` to unblock CI testing
- CI/Build Fix
- CI verified

ci: Torch nightly version upgrade to `2.4.0`

---

dev_dep_versions.yml
pyproject.toml

chore: Update versions

---

docker/Dockerfile

- Specify certain versions of TRT packages for `apt` in Docker build
- Repair Docker build job on `main`

fix: Add dependencies to Docker container for `apt` versioning TRT

---

README.md

**Changes Made:**
| Original    | Correction | Summary of Change                               | Issue Fixed                |
|-------------|------------|-------------------------------------------------|----------------------------|
| extention   | extension  | Corrected spelling error                        | Grammar correction in README |
| Allowerd    | Allowed    | Corrected spelling error                        | Grammar correction in README |
| Discusion   | Discussion | Corrected spelling error                        | Grammar correction in README |
| Its         | It's       | Corrected "Its" to "It's" for contraction      | Grammar correction in README |
- Typo fix: Grammar correction in README.

Fix minor grammatical corrections

---

.github/scripts/install-torch-tensorrt.sh
.github/workflows/build-test.yml
README.md
WORKSPACE
dev_dep_versions.yml
packaging/pre_build_script.sh
py/requirements.txt
py/torch_tensorrt/csrc/torch_tensorrt_py.cpp
toolchains/ci_workspaces/WORKSPACE.x86_64.release.rhel.tmpl

This PR runs CI to test TRT-10 GA support for release/2.3 branch.

TRT-10 GA Support for release/2.3 branch

---

tests/py/dynamo/backend/test_backend_compiler.py
tests/py/dynamo/backend/test_specialized_models.py
tests/py/dynamo/lowering/test_aten_lowering_passes.py
tests/py/dynamo/lowering/test_decompositions.py
tests/py/dynamo/partitioning/test_fast_partitioning.py
tests/py/dynamo/partitioning/test_global_partitioning.py

Updates tests to use assertEqual

chore(//tests): Update tests to use assertEqual

---

py/torch_tensorrt/dynamo/_settings.py

chore: small mypy issue

---

py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
py/torch_tensorrt/dynamo/conversion/converter_utils.py
py/torch_tensorrt/dynamo/conversion/impl/embedding.py
py/torch_tensorrt/dynamo/lowering/_decomposition_groups.py
tests/py/dynamo/conversion/test_embedding_aten.py
tests/py/dynamo/conversion/test_embedding_bag_aten.py

Cherry pick `embedding_bag` converter for release 2.3.

chore: Cherry pick embedding_bag converter for release 2.3

---

.github/workflows/docgen.yml

Use environment for docgen

---

docsrc/index.rst

Cherry pick a previous commit.

chore: cherry pick of #2805

---

core/util/trt_util.cpp
core/util/trt_util.h
py/torch_tensorrt/_enums.py
py/torch_tensorrt/dynamo/_defaults.py
py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py
py/torch_tensorrt/dynamo/conversion/converter_utils.py
tests/py/dynamo/models/test_dtype_support.py

feat(//py/torch_tensorrt/dynamo): Support for BF16 (#2833)

---

docsrc/tutorials/notebooks.rst
docsrc/tutorials/serving_torch_tensorrt_with_triton.rst
docsrc/user_guide/dynamic_shapes.rst
docsrc/user_guide/ptq.rst
docsrc/user_guide/runtime.rst
docsrc/user_guide/using_dla.rst

Fixing typos and clarifying instructions to improve clarity and readability of the user_guide.
- Documentation update (non-breaking change which enhances the documentation)

fix user_guide and tutorial docs

---

.github/workflows/build-test-linux.yml
.github/workflows/build-test-windows.yml
py/torch_tensorrt/_enums.py
tests/py/requirements.txt

chore: cherry-pick of https://github.com/pytorch/TensorRT/pull/2858

---

py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py
py/torch_tensorrt/dynamo/runtime/_PythonTorchTensorRTModule.py

chore: cherry pick of #2832

---

tests/py/ts/ptq/test_ptq_dataloader_calibrator.py
tests/py/ts/ptq/test_ptq_to_backend.py

Changes the ptq to ts namespace.

ptq test error correction

---

pyproject.toml

add a range of versions support for both torch and tensorrt.

suport a range of versions for torch and tensorrt

---

py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
tests/py/dynamo/conversion/test_cat_aten.py
tests/py/dynamo/conversion/test_cos_aten.py
tests/py/dynamo/conversion/test_sin_aten.py

Add dynamic shape support for sin/cos

add dynamic shape support for sin/cos/cat

---

.github/workflows/build-test-linux.yml
.github/workflows/docgen.yml

Only trigger doc gen if it is not a pytorchbot commit.
-

Only trigger doc gen if it is not a pytorchbot commit

---

py/torch_tensorrt/dynamo/lowering/_decompositions.py

scatter CI failures

---

.github/workflows/docker_builder.yml

- Adds Branches to Docker Build File
- CI fix

feat: Add Branches to Docker Build File

---

py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
py/torch_tensorrt/dynamo/conversion/impl/elementwise/ops.py
tests/py/dynamo/conversion/test_erf_aten.py
tests/py/dynamo/conversion/test_rsqrt_aten.py

dynamic shape support for rsqrt/erf ops

chore: dynamic shape support for rsqrt/erf ops

---

.github/workflows/build-test-linux.yml
toolchains/ci_workspaces/WORKSPACE.x86_64.release.rhel.tmpl

cherry pick this code from release/2.4 to main.

Template linux test Workspace in CI

---

py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
tests/py/dynamo/conversion/test_floor_aten.py
tests/py/dynamo/conversion/test_isinf_aten.py
tests/py/dynamo/conversion/test_isnan_aten.py
tests/py/dynamo/conversion/test_logical_not_aten.py
tests/py/dynamo/conversion/test_round_aten.py
tests/py/dynamo/conversion/test_sign_aten.py

add dynamic support for floor/logical_not/sign/round/isinf/isnan

add dynamic support for floor/logical_not/sign/round/isinf/isnan

---

py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
py/torch_tensorrt/dynamo/conversion/impl/elementwise/ops.py
tests/py/dynamo/conversion/test_acosh_aten.py
tests/py/dynamo/conversion/test_asinh_aten.py
tests/py/dynamo/conversion/test_atan2_aten.py
tests/py/dynamo/conversion/test_atan_aten.py
tests/py/dynamo/conversion/test_atanh_aten.py
tests/py/dynamo/conversion/test_ceil_aten.py

dynamic shape support for atan/asinh/acosh/atanh/atan2/ceil

feat: dynamic shape support for atan/asinh/acosh/atanh/atan2/ceil

---

docsrc/tutorials/notebooks.rst

Fix description for BERT example.

chore: fix bert example description in doc

---

py/torch_tensorrt/_compile.py

Fixes https://github.com/pytorch/TensorRT/issues/3005
- Bug fix (breaking change which fixes an issue)

fix: fix exported_program import error

---

README.md
WORKSPACE
dev_dep_versions.yml
docker/README.md
examples/dynamo/requirements.txt
packaging/pre_build_script_windows.sh
packaging/smoke_test_script.sh
py/ci/Dockerfile.ci
py/requirements.txt
pyproject.toml
tests/py/requirements.txt
toolchains/ci_workspaces/WORKSPACE.win.release.tmpl
toolchains/ci_workspaces/WORKSPACE.x86_64.release.rhel.tmpl

chore: cherrypick of #2855

---

py/torch_tensorrt/dynamo/lowering/_decompositions.py
tests/py/dynamo/lowering/test_decompositions.py

Cherry pick 2740 to release 2.4 branch.

cherry pick 2740 to release2.4 branch.

---

py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
tests/py/dynamo/conversion/test_embedding_bag_aten.py
tests/py/dynamo/conversion/test_index_select_aten.py
tests/py/dynamo/conversion/test_unsqueeze_aten.py

add dynamic support for embedding_bag/index_select

---

py/torch_tensorrt/dynamo/conversion/impl/elementwise/ops.py
py/torch_tensorrt/dynamo/lowering/_decompositions.py
tests/py/dynamo/lowering/test_decompositions.py

cherry pick from 3008 to release/2.4

cherry pick from 3008 to release/2.4

---

py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
py/torch_tensorrt/dynamo/conversion/impl/slice/ops.py
tests/py/dynamo/conversion/test_flip_aten.py

dynamic shape support for flip ops

chore: dynamic shape support for flip ops

---

py/torch_tensorrt/dynamo/lowering/passes/lower_scaled_dot_product_attention.py

Fixes the attention test in CI

chore: fix attn test

---

.github/workflows/build-test-linux.yml
.github/workflows/build-test-windows.yml

Run all model tests

---

tests/py/dynamo/conversion/test_argmin_aten.py

fix converter test error

---

notebooks/EfficientNet-example.ipynb

Notebook failure

---

tests/py/dynamo/conversion/test_group_norm_aten.py

chore: fix group_norm test

---

docsrc/index.rst

Docs mutable

---

py/torch_tensorrt/dynamo/_refit.py

_refit: Properly compare device type

---

docker/dist-build.sh
py/requirements.txt
pyproject.toml
tests/py/dynamo/models/test_models_export.py
tests/py/requirements.txt

cut release 2.5

---

docker/dist-build.sh
py/requirements.txt
pyproject.toml
tests/py/dynamo/models/test_models_export.py
tests/py/requirements.txt

release 2.5 branch cut

---

.github/workflows/linux-test.yml
.github/workflows/nightlies.yml
.github/workflows/windows-test.yml

cherry pick 3203 from main to release/2.5

---

py/torch_tensorrt/dynamo/_exporter.py
tests/py/dynamo/models/test_export_serde.py

cherry pick 
**fix: Fix static arange export #3194**
from main to release/2.5 branch

cherry pick to release/2.5 fix: Fix static arange export 3194

---

.github/workflows/build-test-windows.yml

extend windows build from 60 min to 120 min

extend windows build from 60 min to 120 min

---

py/torch_tensorrt/dynamo/_compiler.py
py/torch_tensorrt/dynamo/partitioning/_global_partitioner.py
tests/py/dynamo/partitioning/test_global_partitioning.py

cherry pick fix global partitioner bug #3195 from main to release/2.5 branch

cherry pick fix global partitioner bug #3195 from main to release/2.5 branch

---

.github/workflows/build-test-windows.yml
.github/workflows/release-windows.yml

cherry pick #3225 change from main to release/2.5 branch

---

examples/dynamo/refit_engine_example.py
py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py
py/torch_tensorrt/dynamo/conversion/impl/normalization/ops.py
tests/py/dynamo/models/test_model_refit.py

cherry pick refit error 3170 from main to release/2.5 branch

---

docsrc/index.rst
docsrc/tutorials/notebooks.rst
examples/README.rst
examples/dynamo/README.rst
examples/dynamo/torch_compile_resnet_example.py
examples/dynamo/torch_compile_stable_diffusion.py
examples/dynamo/torch_compile_transformers_example.py
examples/dynamo/torch_export_gpt2.py
examples/dynamo/torch_export_llama2.py

cherry pick doc fix #3238 from main to release2.5

---

packaging/env_vars.txt

export USE_CXX11_ABI=1 for cuda12.6

fix: export USE_CXX11_ABI=1 for cuda12.6

---

py/torch_tensorrt/dynamo/_compiler.py

Adding the changes in this PR: https://github.com/pytorch/TensorRT/pull/3282. Credit to @technillogue 

fix: Fix null inputs case

---

.github/scripts/generate-tensorrt-test-matrix.py
README.md
dev_dep_versions.yml
packaging/smoke_test_script.sh
py/ci/Dockerfile.ci
toolchains/ci_workspaces/MODULE.bazel.tmpl
toolchains/legacy/WORKSPACE.win.release.tmpl
toolchains/legacy/WORKSPACE.x86_64.release.rhel.tmpl
uv.lock

Cherrypick: Bump TRT version to 10.7

---

py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py

Accelerate network interpretation by 15x; fixed redundant code in TRT Interpreter

---

.github/scripts/filter-matrix.py
.github/scripts/generate-tensorrt-test-matrix.py
.github/scripts/generate_binary_build_matrix.py
.github/workflows/build-test-linux.yml
.github/workflows/build-test-windows.yml
py/torch_tensorrt/_features.py
py/torch_tensorrt/dynamo/_refit.py
py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py
pyproject.toml
setup.py
tests/modules/custom_models.py
tests/modules/hub.py
tests/py/dynamo/models/test_engine_cache.py
tests/py/dynamo/models/test_model_refit.py
tests/py/dynamo/models/test_models.py
tests/py/dynamo/models/test_models_export.py
tests/py/dynamo/models/test_weight_stripped_engine.py
tests/py/dynamo/runtime/test_mutable_torchtrt_module.py
tests/py/requirements.txt

Cherrypick #3455 for release/2.7

Cherrypick #3455 for release/2.7

---

py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py

fix: l2_limit_for_tiling (#3479) cherry pick to 2.7

---

.github/scripts/generate-release-matrix.py

Cherry pick to release 2.7-3499-add python3.13 into the final release artifact

---

.github/scripts/generate-release-matrix.py

add python3.13 into the final release artifact

---

tests/py/requirements.txt

add python version dependency for modelopt

---

.nspect-allowlist.toml

add nspect ignore file

---

docker/MODULE.bazel.docker
third_party/tensorrt/archive/BUILD
third_party/tensorrt/local/BUILD

fix docker build failure: add allow_empty to true 

---

py/torch_tensorrt/dynamo/conversion/custom_ops_converters.py

remove breakpoint

---

core/util/Exception.h

fix the build issue for patch2.6.1

---

py/torch_tensorrt/runtime/_cudagraphs.py
tests/core/conversion/converters/test_instance_norm.cpp
tests/core/lowering/BUILD
tests/core/partitioning/BUILD
tests/cpp/BUILD

Fixes the issues with cudagraphs and verifies that all c++ tests pass 

Verify C++ tests, fix cuda graphs union issue

---

.github/workflows/build-test-linux-aarch64.yml

disable test on aarch64 for now

---

docker/Dockerfile
docker/dist-build.sh
py/requirements.txt
pyproject.toml
tests/py/requirements.txt
uv.lock

release 2.8 branch cut

---

.github/workflows/build-test-linux-aarch64-jetpack.yml
pyproject.toml
uv.lock

disable jetpack build for now

---

py/torch_tensorrt/dynamo/conversion/impl/normalization/ops.py

Cherrypick #3719 for release/2.8

Cherrypick #3719 for release/2.8

---

examples/apps/flux_demo.py
py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
py/torch_tensorrt/dynamo/conversion/impl/elementwise/base.py
py/torch_tensorrt/dynamo/lowering/_decomposition_groups.py
py/torch_tensorrt/dynamo/lowering/_decompositions.py
py/torch_tensorrt/dynamo/lowering/passes/accumulate_fp32_matmul.py
tools/perf/Flux/benchmark.sh
tools/perf/Flux/flux_perf.py

broadcast_remove - cherry pick 3700

---

.github/scripts/install-torch-tensorrt.sh
tests/py/requirements.txt

fix typing-extensions issue

---

.github/workflows/build-test-linux-aarch64-jetpack.yml
.github/workflows/build-test-linux-aarch64.yml
.github/workflows/build_wheels_linux_aarch64.yml

fix build cancellation issue

---

py/torch_tensorrt/dynamo/conversion/plugins/_generate_plugin.py

fix the typo

---

tests/py/requirements.txt

upgrade torchvision from 0.23.0 to 0.24.0

---

.github/scripts/filter-matrix.py

disable python 3.14 in CI

---

setup.py

fix the broken build due to upstream pybind change:
https://github.com/pytorch/pytorch/commit/cbc53b76960cf9ee1f3b574b17ebdaac6c3c4581
reference: 
https://gcc.gnu.org/onlinedocs/gcc/C_002b_002b-Dialect-Options.html

fix pybind issue in windows

---

noxfile.py
tests/core/conversion/converters/test_cumsum.cpp
tests/py/dynamo/conversion/test_arange_aten.py
tests/py/dynamo/conversion/test_cumsum_aten.py
tests/py/dynamo/conversion/test_nonzero_aten.py
tests/py/dynamo/runtime/test_004_weight_streaming.py
tests/py/dynamo/runtime/test_output_allocator.py

cherry pick 25.09 skip test to main

---

py/torch_tensorrt/dynamo/utils.py

cherry pick is_thor from ngc/release/25.09 branch to main

---

setup.py

update 25.10 pytorch base commit

---

setup.py

add --dlfw in the build

---

.github/scripts/filter-matrix.py
.github/scripts/install-cuda-aarch64.sh
.github/scripts/install-cuda-dss.sh
.github/workflows/build_linux.yml
MODULE.bazel
packaging/pre_build_script.sh
setup.py
toolchains/ci_workspaces/MODULE.bazel.tmpl

cherry pick 3833 fix ci issue: from main to release/2.9 branch 

---

setup.py

fix thor tensorrt dependency issue
