pytorch/TensorRT

- core/conversion/converters/BUILD
- core/conversion/converters/NodeConverterRegistry.cpp
- core/conversion/converters/impl/activation.cpp
- core/conversion/converters/impl/batch_norm.cpp
- core/conversion/converters/impl/constant.cpp
- core/conversion/converters/impl/conv_deconv.cpp
- core/conversion/converters/impl/element_wise.cpp
- core/conversion/converters/impl/linear.cpp
- core/conversion/converters/impl/pooling.cpp
- core/conversion/converters/impl/scale.cpp
- core/conversion/converters/impl/softmax.cpp
- core/conversion/converters/impl/unary.cpp
- core/conversion/evaluators/BUILD
- core/conversion/evaluators/NodeEvaluatorRegistry.cpp
- core/conversion/evaluators/prim.cpp
corresponding bazel flag is "alwayslink"
Fixes NVIDIA/TRTorch#9
> Whole archive libs with registerers

- core/BUILD
- cpp/api/BUILD
When the library is full built the actual apis were getting stripped. Use alwayslink for both the core top level and api level to make sure they make it into the final .so
Thanks @bddppq for the pointer
> Fix stripping of apis from the final .so

- core/conversion/converters/NodeConverterRegistry.cpp
- core/conversion/converters/Weights.cpp
- core/execution/TRTEngine.cpp
> refactor: Remmoing some old std::couts used for debugging

- core/compiler.cpp
- core/compiler.h
- core/conversion/conversion.cpp
- core/conversion/conversion.h
- core/conversion/conversion_blacklist.cpp
- core/conversion/converters/NodeConverterRegistry.cpp
- core/conversion/evaluators/NodeEvaluatorRegistry.cpp
- cpp/api/include/trtorch/trtorch.h
- cpp/api/src/trtorch.cpp
- cpp/trtorchexec/main.cpp
> New API to display if a method can be converted to TensorRT

- core/conversion/converters/impl/batch_norm.cpp
- core/lowering/lowering.cpp
- core/lowering/passes/unpack_batch_norm.cpp
- tests/core/converters/BUILD
- tests/core/converters/test_batch_norm.cpp
Addresses performance issues seen with large input sizes and the conv based batch norm implementation. This new implementation just uses scale layers instead of conv.
> fix(aten::batch_norm): A new batch norm implementation that hopefully doesnt have the same performace cost

- core/conversion/converters/impl/shuffle.cpp
- tests/core/converters/BUILD
- tests/core/converters/converter_test.bzl
- tests/core/converters/test_shuffle.cpp
- tests/modules/hub.py
- tests/util/BUILD
> feat(aten::view): Adds support for ATen view also fixes some tests

- core/conversion/evaluators/aten.cpp
> fix(aten::neg): Fix a index bug in neg

- core/conversion/conversionctx/ConversionCtx.cpp
When int8 is enabled, we also need to enable fp16 kernels just in case those kernels provide a faster path. This explains significant performance differences between FP16 and INT8 in cases where most layers are not mapped to INT8 kernels. 
Partially addresses #93 
> Enable FP16 mixed precision with Int8

- core/conversion/conversion.cpp
- core/conversion/converters/NodeConverterRegistry.cpp
- core/conversion/evaluators/BUILD
- core/conversion/evaluators/NodeEvaluatorRegistry.cpp
- core/conversion/evaluators/aten.cpp
- core/conversion/evaluators/eval_macros.h
- core/conversion/evaluators/prim.cpp
Adds the ability to evaluate conditionals at compile time. Also adds evaluators for 
- aten::eq
- aten::ne
- aten::lt
- aten::gt
- aten::le
- aten::ge
- aten::add
- aten::sub
- aten::mul
- aten::Bool
- aten::Float
- aten::__not__
- aten::__is__
- aten::__isnot__
- aten::numel
- aten::dim
- aten::div
- aten::floordiv
- aten::floor
- aten::warn
- prim::min
- prim::max
- prim::shape
- prim::unchecked_cast
- prim::Uninitalized
- prim::RaiseException
> Adds support for the evaluation of conditionals

- core/conversion/converters/BUILD
- core/conversion/converters/impl/select.cpp
- core/conversion/converters/impl/stack.cpp
- core/util/trt_util.cpp
- core/util/trt_util.h
- tests/core/converters/BUILD
- tests/core/converters/test_select.cpp
- tests/core/converters/test_stack.cpp
Adds support for aten::select.int and aten::stack. Added test cases for these.
Added unsqueezeDims tool to unsqueeze Tensor at specified dimension. 
(from @narendasan) Added unpadDims tool to squeeze Tensor (removes first redundant dimension).
Fixes #110 
Fixes #115 
> Add support for aten::select.int and aten::stack

- core/conversion/converters/impl/shuffle.cpp
- tests/core/converters/test_shuffle.cpp
Fixes flatten to work with dynamic input. Also will now error out on dynamic input and resize (issue to be filed for a shape tensor runtime evaluation system)
> fix(aten::flatten): Fixes dynamic shape for flatten

- README.md
- WORKSPACE
- tests/core/converters/BUILD
- tests/util/BUILD
- third_party/cublas/BUILD
- third_party/cuda/BUILD
- third_party/tensorrt/local/BUILD
- toolchains/BUILD
Signed-off-by: anuragd <anuragd@nvidia.com>
It includes native compilation support for the NVIDIA Jetson AGX platform.
Dependencies:
Cross-compiled libraries from PyTorch on Jetson. Refer https://ngc.nvidia.com/catalog/containers/nvidia:l4t-pytorch
Type of change
> (//bazel): Native compilation support for NVIDIA Jetson AGX platform

- core/conversion/converters/impl/conv_deconv.cpp
- core/conversion/converters/impl/interpolate.cpp
- core/conversion/converters/impl/plugins/BUILD
- core/conversion/converters/impl/plugins/interpolate_plugin.cpp
- core/conversion/converters/impl/plugins/interpolate_plugin.h
- core/conversion/converters/impl/pooling.cpp
- tests/modules/hub.py
- tests/modules/test_serialization.cpp
This PR fixes the interpolate plugin which was segfaulting in the enqueue method on Tensor creation in ATen. As a work around to fix the issue in master until a long term solution is found we have reduced the scope of the interpolate function to only handle the case of `aten::adaptive_avg_pool_2d`. Other cases are now handled via TensorRT. 
This PR also add support for dilated and group conv_transpose
Fixes #129  (partially)
- No API change but perf regression on adaptive_avg_pool_2d dynamic input
> Fix for interpolate plugin segfault

- py/setup.py
Allows setup.py to search for bazel installation path
> feat(//py): setup.py now searches for bazel executable

- notebooks/Dockerfile.notebook
- Change replaces pytorch 20.03 with tensorrt 20.03
as base container for trtorch builds.
- Adds locale setting as no locale was set by default leading to build failure.
Signed-off-by: Shashank Verma <shashank3959@gmail.com>
> Use TensorRT 20.03 as base container for builds

- core/util/macros.h
- cpp/api/include/trtorch/trtorch.h
- cpp/trtorchc/main.cpp
- third_party/cuda/BUILD
- third_party/cudnn/local/BUILD
- third_party/libtorch/BUILD
- third_party/tensorrt/local/BUILD
As part of Windows compatibility, a simple replacement for the two unistd functions is provided.
Also add in a missing export that is necessary on Windows.
> Fix missing unistd.h on Windows

- third_party/cudnn/local/BUILD
- third_party/tensorrt/local/BUILD
BREAKING CHANGE: Users on Windows trying to use cuDNN 8 must manually
configure third_party/cudnn/local/BUILD to use cuDNN 8.
> fix(Windows)!: Fix dependency resolution for local builds

- BUILD
- cpp/api/lib/BUILD
Now the generated tarball will contain trtorch.dll instead of a misnamed
file and will not include trtorchc (since we don't want to distribute
all the associated libraries as well)
> refactor(windows): Windows specific packaging rules

- core/conversion/conversion.cpp
- core/conversion/conversionctx/ConversionCtx.h
- core/execution/TRTEngine.cpp
- core/execution/execution.h
- core/execution/register_trt_op.cpp
- tests/util/run_graph_engine.cpp
The binding convention now looks for bindings by name and reorders
outputs to match the order expected by PyTorch.
BREAKING CHANGE: This changes the "ABI" of compiled TRTorch programs and
the runtime and breaks backwards compatability between the runtime in
0.1.0+ and programs compiled pre-0.1.0
Fixes #174 
> refactor(//core)!: Introducing a binding convention that will address determinism issues with TensorRT

- README.md
- core/conversion/converters/impl/element_wise.cpp
- py/README.md
- tests/core/converters/test_element_wise.cpp
Add support for converting power layer in Pytorch (torch.pow). Request : [https://github.com/NVIDIA/TRTorch/issues/184](https://github.com/NVIDIA/TRTorch/issues/184)
> Add power layer conversion support 

- core/conversion/converters/impl/select.cpp
- tests/core/converters/test_select.cpp
Adding conversion support for operator `torch.narrow(input, axis, start, length)`
The variable `start` can be a scalar or tensor. 
The test case when `start` is a tensor hasn't been implemented in the PR as the IR for this testcase wasn't being parsed by torch jit parser (due to start being prim::constant(value={2} for example). However, using trtorchexec, I was able to test that case as well and it works.
Fixes [#151](https://github.com/NVIDIA/TRTorch/issues/151)
> feat(//core/converters): Add conversion support for torch.narrow()

- core/lowering/passes/conv3d_to_convolution.cpp
- tests/core/converters/test_conv_deconv.cpp
Fix 3d convolution existing support and add testcases. Closing [this PR ](https://github.com/NVIDIA/TRTorch/pull/191) due to DCO issues.
Partially fixes (https://github.com/NVIDIA/TRTorch/issues/12)
> Add 3d convolution support with testcases

- tests/accuracy/test_int8_accuracy.cpp
Fixing a missing include in the int8 test accuracy. 
> fix(//tests/accuracy): Fix int8 accuracy test for new PTQ api

- CHANGELOG.md
- docsrc/RELEASE_CHECKLIST.md
- docsrc/conf.py
- py/setup.py
Version bump for 0.1.0 release
> chore: Bumping version to v0.1.0

- core/conversion/converters/impl/element_wise.cpp
- tests/core/converters/test_element_wise.cpp
Add layer now supports addition of tensor and a constant scalar with broadcasting.
Fixes  (https://github.com/NVIDIA/TRTorch/issues/185)
> Add scalar add functionality

- core/conversion/converters/impl/select.cpp
- tests/core/converters/test_select.cpp
Add conversion functionality for aten::slice layer. This is based on implicit Pytorch op. For example, the following snippet adds `aten::slice` in the graph.
```
class Slice(torch.nn.Module):
def __init__(self):
super(Slice, self).__init__()
def forward(self, x): 
return x[0, 1, 1:4:2, :]
```
Fixes (https://github.com/NVIDIA/TRTorch/issues/111)
> feat(//core/converters): Add support for aten::slice layer

- BUILD
- cpp/api/lib/BUILD
- docsrc/index.rst
- docsrc/tutorials/runtime.rst
Users now can simply ship the runtime library with their compiled
trtorch programs instead of the full compiler. The runtime will load
into pytorch on DL_OPEN, LD_PRELOAD or torch.ops.load
Fixes #77 
> feat(//cpp/api/lib): New runtime only library

- core/conversion/converters/impl/element_wise.cpp
- core/conversion/converters/impl/pooling.cpp
Supressing error due to not filling in stride in the default case in pooling converters
Fixes #228 
> fix(aten::max_pool2d): Supressing error due to not filling in stride in the default case

- core/conversion/converters/impl/conv_deconv.cpp
- tests/core/converters/test_conv_deconv.cpp
> fix deconv with groups > 1

- core/conversion/converters/impl/element_wise.cpp
- tests/core/converters/test_element_wise.cpp
Add fails when alpha > 1. Scale layer needs input tensors to be minimum of 3 dimensions. Replaced it with elementwise PROD layer.
Fixes (https://github.com/NVIDIA/TRTorch/issues/243)
> Fix add ops with alpha multiplier

- docker/Dockerfile.20.06
- docker/Dockerfile.docs
- docker/WORKSPACE.docker
- notebooks/Dockerfile.notebook
- notebooks/WORKSPACE.notebook
> refactor(//docker): Update containers for 0.2.0

- core/util/trt_util.cpp
- tests/util/util.cpp
Support bool datatype for input/output tensors
Fixes  (https://github.com/NVIDIA/TRTorch/issues/242)
This change is required to support aten::gt, aten::le etc.. 
Testcases will be added by Vincent (author of https://github.com/NVIDIA/TRTorch/issues/242) when he submits PR for the converter ops. I verified with the testcase provided by him in the issue.
> Support bool datatype of input/output tensors

- core/lowering/passes/fuse_addmm_branches.cpp
Change the condition to find ADDMM variant nodes to be more explicit. The following issue happens even though it is not a add + matmul variant
```
Found that node %scale_factor0.9 : float?, %size3.3 : int? = prim::If(%16230) # /opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:2969:4
block0():
= prim::RaiseException(%16215) # /opt/conda/lib/python3.6/site-packages/torch/nn/functional.py:2970:8
-> (%16220, %16221)
block1():
-> (%652, %size1.3)
is an AddMM variants node (FuseAddMMBranches)
```
> Explicit pattern matching for add + MM fusion

- core/conversion/conversion.cpp
- core/conversion/converters/impl/select.cpp
- core/conversion/evaluators/prim.cpp
- tests/core/conversion/converters/test_select.cpp
- tests/core/conversion/evaluators/test_prim_evaluators.cpp
- tests/util/evaluate_graph.cpp
Support aten::split and prim::ListUnpack
Fixes https://github.com/NVIDIA/TRTorch/issues/267 and https://github.com/NVIDIA/TRTorch/issues/259
> feat(//core/): Add support for Split converter and unpack evaluator

- core/conversion/converters/impl/interpolate.cpp
- core/conversion/converters/impl/plugins/interpolate_plugin.cpp
- core/conversion/converters/impl/plugins/interpolate_plugin.h
- core/conversion/converters/impl/pooling.cpp
- tests/core/conversion/converters/test_interpolate.cpp
- tests/util/util.cpp
This PR includes the changes in #258, does some refactoring of the test suite for interpolate and should expand coverage of the interpolate converter for the two variants of each of the currently supported resize functions (self, and vec). It should mean that we support interpolate for nearest and linear variants for all cases except when users use a type of linear upsampling, use scale factor for setting the size and set `align_corners` to true. It seems like @uni19  found that TensorRT  and PyTorch have different behavior in this case. I will check with the TRT team to see if they have observed this. Hopefully it is not a massive issue as PyTorch since 1.5 has switched to `align_corners` being false by default. As a stop gap this PR extends the interpolate plugin to handle this case, …
> Extending @uni19's work on support dynamic shape input and scale_factor in interpolate layer

- core/conversion/converters/impl/interpolate.cpp
- tests/core/converters/test_interpolate.cpp
support dynamic shape input and scale_factor in interpolate layer
> support dynamic shape input and scale_factor in interpolate layer

- core/conversion/converters/impl/element_wise.cpp
- tests/core/conversion/converters/test_element_wise.cpp
add support for torch.ne
Fixes https://github.com/NVIDIA/TRTorch/issues/279
> Add support for ne layer

- core/conversion/evaluators/prim.cpp
- tests/core/conversion/evaluators/test_prim_evaluators.cpp
This fixes an issue with the `prim::num_to_tensor` evaluator where it used to be using the output as a key for the argument instead of the node input. 
> Fix issue with num_to_tensor evaluator

- core/conversion/converters/impl/element_wise.cpp
- core/conversion/evaluators/aten.cpp
- tests/core/conversion/converters/test_element_wise.cpp
- tests/core/conversion/evaluators/BUILD
- tests/core/conversion/evaluators/test_aten_evaluators.cpp
- New feature
Support aten::div.Scalar(Tensor self, Scalar other), fix the conflict of aten::div in evaluator
solved this issue https://github.com/NVIDIA/TRTorch/issues/303
> support div.Scalar(Tensor self, Scalar other)

- core/conversion/converters/impl/element_wise.cpp
- tests/core/conversion/converters/test_element_wise.cpp
Add clamp conversion
Fixes https://github.com/NVIDIA/TRTorch/issues/274
> Add clamp conversion functionality

- core/conversion/converters/BUILD
- core/conversion/converters/impl/expand.cpp
- tests/core/conversion/converters/BUILD
- tests/core/conversion/converters/test_expand.cpp
Add expand layer, expand_as and repeat layer functionality
Fixes https://github.com/NVIDIA/TRTorch/issues/169 and https://github.com/NVIDIA/TRTorch/issues/281
> feat(//core/converters): Add expand layer, expand_as and repeat layer functionality

- core/conversion/converters/impl/expand.cpp
Fixes compiler warnings generated by the expand converters
> fix(aten::expand): Fix compiler warnings in the expand converter

- core/conversion/converters/impl/element_wise.cpp
- tests/core/conversion/converters/test_element_wise.cpp
Fix unused variable warning in clamp
> Fix unused variable out warning

- core/lowering/lowering.cpp
- core/lowering/passes/BUILD
- core/lowering/passes/passes.h
- core/lowering/passes/remove_nops.cpp
- core/lowering/passes/remove_to.cpp
- tests/core/lowering/BUILD
- tests/core/lowering/test_remove_contiguous_pass.cpp
- tests/core/lowering/test_remove_detach_pass.cpp
- tests/core/lowering/test_remove_to.cpp
Adds a lowering pass to remove Detach ops which have no meaning in TensorRT. 
> aten::detach removal pass

- core/conversion/converters/impl/softmax.cpp
- tests/core/conversion/converters/test_softmax.cpp
> support index=-1, and fix bug when nDims=2 or 3 in softmax

- tests/core/lowering/test_operator_aliasing_pass.cpp
Fix the test for the renamed op aliasing pass
> Fix the test for the renamed op aliasing pass

- core/conversion/conversionctx/ConversionCtx.cpp
- core/conversion/conversionctx/ConversionCtx.h
- cpp/api/include/trtorch/trtorch.h
- cpp/api/src/compile_spec.cpp
- cpp/trtorchc/main.cpp
- py/trtorch/_compile_spec.py
- py/trtorch/_compiler.py
- py/trtorch/csrc/register_tensorrt_classes.cpp
- py/trtorch/csrc/tensorrt_classes.cpp
- py/trtorch/csrc/tensorrt_classes.h
- py/trtorch/csrc/trtorch_py.cpp
- tests/py/test_api.py
- tests/py/test_to_backend_api.py
On Ampere TF32 is the default FP32 format. This PR adds support to disable TF32 and use the standard FP32 format. 
Fixes #247 
> Add a new API to disable TF32

- py/setup.py
Jetson does not seem to have a 1.7.1 build so this PR expands the supported version of Pytorch in the setup.py
> fix(setup.py): Broaden the supported pytorch versions to handle jetson

- core/conversion/converters/impl/element_wise.cpp
- tests/core/conversion/converters/test_element_wise.cpp
> Add mul.scalar converter

- core/conversion/converters/impl/expand.cpp
- core/conversion/converters/impl/shuffle.cpp
- tests/core/conversion/converters/test_pooling.cpp
- tests/core/conversion/converters/test_shuffle.cpp
- tests/util/run_graph_engine.cpp
- tests/util/util.h
Flatten converter implicitly assumed static batch size even in the dynamic case. This adds support for dynamic batch, but will not support both dynamic batch and dynamic shape as it stands right now. It is unclear if TensorRT can support that case at all. 
In the process we discovered an issue with dynamic batch and elementwise operations so this PR will include fixes for that too. 
Fixes #235 
> fix(aten::flatten): Fixing flatten converter to handle dynamic batch

- core/conversion/conversion.cpp
- core/conversion/evaluators/aten.cpp
- tests/core/conversion/evaluators/test_aten_evaluators.cpp
This PR fixes the `aten::zeros` evaluator and adds a test to make sure it matches PyTorch execution. 
It also adds a check to see if a graph will result in a TensorRT engine that does nothing at runtime and errors out if so. 
Fixes #343 
> Verify zeros evaluator works correctly and detect programs that will have an empty TensorRT engine

- core/conversion/converters/impl/shuffle.cpp
- tests/core/conversion/converters/test_shuffle.cpp
Add support for aten::transpose in shuffle converter.
Function Schema:
aten::transpose.int(Tensor(a) self, int dim0, int dim1) -> (Tensor(a))
Fixes # 275
> Add aten.transpose support.

- core/conversion/conversionctx/ConversionCtx.cpp
- py/trtorch/_compiler.py
- tests/py/test_multi_gpu.py
Fixes a memory leak where the `IHostMemory` container for the produced serialized engine after conversion is not destructed properly. 
h/t: @SakodaShintaro
Fixes #375 
> fix(//core/conversion/conversionctx): Fix memory leak in conversionctx

- core/conversion/converters/Weights.cpp
The memcpy for weights tensors over copies when the Tensor is not a FP32 tensor. This seems to be the root cause of segfaults observed in #326 as well as failing DLA tests on aarch64 when users try to compile a model that is already in FP16. 
Fixes #326 
> fix(//core/conversion/converters/Weights): Fix buffer allocation for weights data 

- core/conversion/converters/impl/element_wise.cpp
- tests/core/conversion/converters/test_element_wise.cpp
Fixes https://github.com/NVIDIA/TRTorch/issues/274
Support aten::clamp_min, aten::clamp_max converters
> add clamp_min/clamp_max converter

- core/conversion/converters/impl/squeeze.cpp
- tests/core/conversion/converters/test_squeeze.cpp
…a judgment condition to handle this situation
Some tensor like at::randint(1,10,{2,3,3}) dont need to squeeze and add a judgment condition to handle this situation. 
Fixes #392 
> Fix bug in squeeze

- .gitignore
- py/trtorch/_compile_spec.py
- py/trtorch/csrc/register_tensorrt_classes.cpp
- py/trtorch/csrc/tensorrt_classes.h
- py/trtorch/csrc/trtorch_py.cpp
- tests/BUILD
- tests/py/BUILD
- tests/py/test_ptq_dataloader_calibrator.py
- tests/py/test_ptq_to_backend.py
- tests/py/test_ptq_trt_calibrator.py
Adds support for PTQ through the PyTorch to_backend api.
> Adds support for PTQ through the PyTorch to_backend api.

- tests/core/conversion/converters/test_activation.cpp
- tests/core/conversion/converters/test_batch_norm.cpp
- tests/core/conversion/converters/test_concat.cpp
- tests/core/conversion/converters/test_conv_deconv.cpp
- tests/core/conversion/converters/test_element_wise.cpp
- tests/core/conversion/converters/test_expand.cpp
- tests/core/conversion/converters/test_interpolate.cpp
- tests/core/conversion/converters/test_linear.cpp
- tests/core/conversion/converters/test_lstm_cell.cpp
- tests/core/conversion/converters/test_matrix_multiply.cpp
- tests/core/conversion/converters/test_pooling.cpp
- tests/core/conversion/converters/test_reduce.cpp
- tests/core/conversion/converters/test_select.cpp
- tests/core/conversion/converters/test_shuffle.cpp
- tests/core/conversion/converters/test_softmax.cpp
- tests/core/conversion/converters/test_squeeze.cpp
- tests/core/conversion/converters/test_stack.cpp
- tests/core/conversion/converters/test_topk.cpp
- tests/core/conversion/converters/test_unary.cpp
- tests/core/conversion/converters/test_unsqueeze.cpp
- tests/core/conversion/evaluators/test_aten_evaluators.cpp
- tests/core/conversion/evaluators/test_prim_evaluators.cpp
- tests/core/lowering/test_operator_aliasing_pass.cpp
- tests/core/lowering/test_remove_contiguous_pass.cpp
- tests/core/lowering/test_remove_detach_pass.cpp
- tests/core/lowering/test_remove_to.cpp
- tests/core/lowering/test_silu_to_sigmoid_multiplication.cpp
Signed-off-by: Yonghye Kwon <developer.0hye@gmail.com>
```cpp
auto g = std::make_shared<torch::jit::Graph>();
torch::jit::parseIR(graph, &*g);
```
```cpp
auto g = std::make_shared<torch::jit::Graph>();
torch::jit::parseIR(graph, g.get());
```
Refer to [this thread](https://stackoverflow.com/questions/505143/getting-a-normal-ptr-from-shared-ptr) uploaded on Stack Overflow.
> more safe and easily readable use to get raw pointer of shared-pointer

- core/conversion/converters/impl/select.cpp
- tests/core/conversion/converters/test_select.cpp
In my practice, the `indicesTensor ` in aten::embedding sometimes is IValue. So i replaced the ITensor with ITensorOrFreeze.
According to the [document ](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_tensor.html#a1004b03f9249097f6d146abc3772819a), After calling setType, the type of a tensor is unchanged if the tensor is not a network input tensor, or marked as an output tensor or shape output tensor. So i replaced the setType with addIdentity to avoid change the input data type and ensure the indicesTensor is set as INT32.
In addition, i use the linters to ensure that my code matches the style guidelines. The linters changed the entire file(core/conversion/converters/impl/select.cpp) . I only modified the …
> fix bugs in embedding converter

- core/conversion/converters/impl/select.cpp
- core/conversion/var/BUILD
- core/conversion/var/Var.cpp
- core/conversion/var/Var.h
- tests/core/conversion/converters/test_select.cpp
Fix Split Converter bugs.  
1. Fix bug in ```core/conversion/converters/select.cpp: add_split``` function. 
2. Modified the `Var::ITensorOrFreeze` function in `core/conversion/var/Var.cpp`.
In addition, i use the linters to ensure that my code matches the style guidelines. The linters changed the entire file(core/conversion/converters/impl/select.cpp) . I only modified the `add_split ` part in select.cpp.
Fixes #401 
> fix bugs in split converter

- core/partitioning/partitioning.cpp
Support input node kind of prim::Param in registerSegmentInOutIValues. Without this if branch, prim::Param will go to **input->type()->isSubtypeOf(torch::jit::TensorType::get())** this branch and throw **Expected Tensor but got InvalidTag(3409)**
> feat: support prim::Param for fallback inputs

- core/conversion/conversion_ignorelist.cpp
- core/lowering/passes/remove_dropout.cpp
- tests/core/lowering/BUILD
- tests/core/lowering/test_remove_dropout_pass.cpp
As described in the [documentation](https://pytorch.org/docs/stable/nn.functional.html?highlight=feature_alpha_dropout#torch.nn.functional.feature_alpha_dropout), aten::feature_dropout and aten::feature_alpha_dropout are similar to aten::dropout that they should be removed from the graph in inference phase.
Fixes #273 
> Support feature_dropout and feature_alpha_dropout converters

- core/compiler.cpp
- core/compiler.h
- core/conversion/InterfaceTypes.cpp
- core/conversion/conversion.cpp
- core/conversion/conversion.h
- core/conversion/conversionctx/ConversionCtx.cpp
- core/conversion/conversionctx/ConversionCtx.h
- core/conversion/var/Var.cpp
- core/ir/BUILD
- core/ir/InputRange.cpp
- core/ir/ir.h
- core/partitioning/BUILD
- core/partitioning/PartitionInfo.cpp
- core/partitioning/PartitionInfo.h
- core/partitioning/SegmentedBlock.cpp
- core/partitioning/SegmentedBlock.h
- core/partitioning/partitioning.cpp
- core/partitioning/partitioning.h
- core/partitioning/shape_analysis.cpp
- core/partitioning/shape_analysis.h
- cpp/api/src/compile_spec.cpp
- py/trtorch/_compile_spec.py
- py/trtorch/csrc/tensorrt_classes.cpp
- tests/util/run_graph_engine.cpp
Reorganizes the codebase a bit to make the relationship between modules a bit clearer. Gives partition settings their own structure owned by the partitioning module in the internals settings struct/
> Reorganizing partitioning deps 

- core/conversion/converters/BUILD
- core/conversion/converters/impl/replication_pad.cpp
- tests/core/conversion/converters/BUILD
- tests/core/conversion/converters/test_replication_pad.cpp
Support converters:
Fixes #272 
> Support replication_padXd converters

- core/compiler.cpp
- core/compiler.h
- cpp/api/include/trtorch/trtorch.h
- cpp/api/src/trtorch.cpp
- py/trtorch/_compiler.py
- py/trtorch/csrc/trtorch_py.cpp
- tests/modules/test_modules_as_engines.cpp
- tests/py/BUILD
- tests/py/test_api.py
- tests/py/test_trt_intercompatability.py
This PR adds the ability to register TRT engines from outside TRTorch as TorchScript modules. Modules created through this method inherit all the abilities (and limitations) of TRTorch compiled TorchScript modules including serialization and portability through `torch.jit.load` and deployment with `libtrtorchrt.so`
Fixes #46 
> New API to register arbitrary TRT engines as TorchScript modules

- core/conversion/evaluators/aten.cpp
- tests/core/conversion/evaluators/test_aten_evaluators.cpp
Adds floor.int evaluator
Fixes #117 
(partially addresses #252)
> feat(aten::floor): Adds floor.int evaluator

- core/conversion/converters/impl/matrix_multiply.cpp
- tests/core/conversion/converters/test_matrix_multiply.cpp
Support aten::bmm converter
Fixes #270 
> Support aten::bmm converter

- core/conversion/converters/impl/replication_pad.cpp
When the last dimension of the input is specified as dynamic, the index of the last dimension will be out of range.
To Reproduce
The bug can be reproduced by change  https://github.com/NVIDIA/TRTorch/blob/3589730201efdef104e1a9d869a43507de865527/tests/util/run_graph_engine.cpp#L44 to 
```
min_range[opt.size() - 1] = ceil(opt[opt.size() - 1] / 2.0);
max_range[opt.size() - 1] = 2 * opt[opt.size() - 1];
```
> fix bug of replication_pad when input is dynamic

- core/conversion/converters/BUILD
- core/conversion/converters/converter_util.cpp
- core/conversion/converters/converter_util.h
- core/conversion/converters/impl/element_wise.cpp
- core/conversion/converters/impl/layer_norm.cpp
- tests/core/conversion/converters/BUILD
- tests/core/conversion/converters/test_layer_norm.cpp
Add aten::layer_norm support and move add_elementwise to core/conversion/converters/converter_util.h
Fixes # 278
> Add aten::layer_norm support and move add_elementwise to utils

- WORKSPACE
- third_party/cublas/BUILD
- third_party/tensorrt/archive/BUILD
- third_party/tensorrt/local/BUILD
Fixes a linking issue on Jetson where cuBLAS was missing for libnvinfer_plugin 
> fix(//plugins): Readding cuBLAS BUILD to allow linking of libnvinfer_plugin on Jetson

- core/compiler.cpp
There is a typo which couldn't print the mini graph in each Segmented Block correctly. 
> fix: fix a typo for printing mini graph when debug 

- py/setup.py
setup.py
Checks if bazel was found in the path otherwise errors out 
> feat(//py): Catch when bazel is not in path and error out when running

- core/conversion/converters/impl/activation.cpp
Set name of Gelu layer to "util::node_info(n).c_str()"  instead of string "gelu", to prevent "Repeated layer name: gelu (layers must have distinct names)"  error when building tensorrt engine from a module with multiple gelu layers.
Also format "trtorch::core::util::node_info(n).c_str()" to "util::node_info(n).c_str()".
> gelu layer setName using util::node_info(n).c_str()

- core/plugins/register_plugins.cpp
Uses global config to set reportable logging level
Superseeds: #458
> feat(//core/plugins): Gating plugin logging based on global config

- core/conversion/conversionctx/ConversionCtx.cpp
- core/util/Exception.cpp
Fixes an issue where if final network validation fails, a segfault
occurs. Now an exception is thrown which can be handled by the user
Fixes #475 
> fix(//core/conversion/conversionctx): Guard final engine building

- core/conversion/conversion.cpp
- core/conversion/evaluators/aten.cpp
- tests/core/conversion/evaluators/test_aten_evaluators.cpp
Now we can handle ITensors as inputs to append and handle returning singular ITensors from evaluators 
Fixes #471
> Handling ITensors in append and also unwrapping ITensors as result of evaluators

- core/partitioning/partitioning.cpp
There are some cases that TensorRT segments use some nonTensor input which is produced in Torch segments. However, the node in the dependencies for these nonTensor input might not be supported in TRTorch. So, we need to segment this TensorRT segment again and add the dependency nodes. 
Some bugs related to cannot find IValues for listConstruct operation.
> fix: fix the bug when TensorRT segment depends a nonTensor input which is produced in an unsupported op

- core/lowering/lowering.cpp
- core/lowering/passes/BUILD
- core/lowering/passes/passes.h
- core/lowering/passes/unpack_hardswish.cpp
- tests/core/lowering/BUILD
- tests/core/lowering/test_unpack_hardswish.cpp
Support aten::hardswish op which is used in the yolov5 model.
> Support aten::hardswish using unpack_hardswish pass

- py/trtorch/ptq.py
Transfer calibration data to gpu when the batch is not a list
> fix: Transfer calibration data to gpu when the batch is not a list

- core/compiler.cpp
- core/conversion/converters/impl/layer_norm.cpp
- core/conversion/converters/impl/matrix_multiply.cpp
- core/lowering/passes/linear_to_addmm.cpp
- tests/core/conversion/converters/test_layer_norm.cpp
- tests/core/conversion/converters/test_matrix_multiply.cpp
- tests/core/lowering/test_linear_to_addmm.cpp
- tests/modules/hub.py
These are the changes required for vision transformer network to work. 
Layer norm : Scale layer has a restriction where it requires the dims to greater than 3.
Matmul: Previously both the tensors were required to have same number of dimensions. Lifted this restriction.
Linear lowering pass : Subgraph writer is not working as expected for "None " bias. It matches even the valid Bias tensor case. Replaced this with new functionality which checks the types of tensors.
> fix: Fix linear lowering pass, lift layer_norm scale layer restriction and matmul layer nbdims restriction

- core/conversion/converters/converter_util.cpp
Set layer name with wrong string.
`+ ']'` will call char pointer operation, not string append. 
This could result in `ERROR: [TRTorch Conversion Context] - Repeated layer name` during compiling.
> string(char) operator+()  mistake.

- tests/modules/hub.py
- tests/modules/module_test.h
- tests/modules/test_compiled_modules.cpp
- tests/modules/test_modules_as_engines.cpp
- tests/modules/test_serialization.cpp
Add efficientnet and vit to testsuite
> chore: Add efficientnet b0 and VIT to testsuite

- core/compiler.cpp
- core/runtime/BUILD
- core/runtime/CudaDevice.cpp
- core/runtime/DeviceList.cpp
- core/runtime/TRTEngine.cpp
- core/runtime/register_trt_op.cpp
- core/runtime/runtime.cpp
- core/runtime/runtime.h
- cpp/api/src/compile_spec.cpp
- py/trtorch/csrc/tensorrt_backend.cpp
- tests/util/run_graph_engine.cpp
BREAKING CHANGE: This commit cleans up the WIP CudaDevice class,
simplifying implementation and formalizing the seralized format for CUDA
devices.
It also implements ABI Versioning. The first entry in the serialized
format of a TRTEngine now records the ABI that the engine was compiled
with, defining expected compatibility with the TRTorch runtime. If the
ABI version does not match, the runtime will error out asking to
recompile the program.
ABI version is a monotonically increasing integer and should be
incremented everytime the serialization format changes in some way.
This commit cleans up the CudaDevice class, implementing a number of
constructors to replace the various utility functions that populate the
struct. Descriptive utility functions remain but solely call the
relevant …
> feat(serde)!: Refactor CudaDevice struct, implement ABI versioning, serde cleanup

- core/runtime/DeviceList.cpp
Changed assert to warning logs. Document generation is not applicable to host machines with GPU cards. Hence, failure to read any CUDA-capable device is not a valid use case scenario. 
Bug fix (non-breaking change)
> fix(runtime): Fix document generator failure for non-GPU host machines

- py/trtorch/Device.py
- py/trtorch/__init__.py
- py/trtorch/_compile_spec.py
- py/trtorch/_compiler.py
- py/trtorch/csrc/tensorrt_classes.cpp
- py/trtorch/csrc/tensorrt_classes.h
- py/trtorch/csrc/trtorch_py.cpp
- tests/py/test_api.py
Adds a python level Device class so users can set device for apis like embed engine. 
> feat(//py): add user level device class in py for embed engine

- core/conversion/conversion.cpp
- core/util/jit_util.h
Signed-off-by: lamhoangtung <lamhoangtung.vz@gmail.com>
Inspired by my problem in #511, I'm trying to enable TensorRT for a TorchScript model and getting a bunch of Unsupported operators. I'm willing to change the implementation to avoid those unsupported operators or even trying to add support for it but struggling to find which line of code in my model are causing it.
Thanks to @narendasan guidance. I have tried to add a similar traceback feature like TorchScript where TRTorch will point to the exact line of PyTorch that cause the unsupported operators. 
So instead of showing a vague operator schema like this:
```console
ERROR: [TRTorch] - Method requested cannot be compiled by TRTorch.
Unsupported operators listed below:
-  aten::__contains__.str_list(str[] l, str item) -> (bool)
- …
```
> feat: Show PyTorch code of unsupported operators

- py/trtorch/csrc/trtorch_py.cpp
- py/trtorch/logging.py
Add certain codes to enable `LogLevel.GRAPH` in python. 
> Enable LogLevel.GRAPH in Python API

- core/conversion/evaluators/aten.cpp
- tests/core/conversion/evaluators/test_aten_evaluators.cpp
aten::Int.float is missing in evalutors, and there are some models need this evalutor
support aten::Int.float, aten::Int.bool
> feat: support aten::Int

- cpp/trtorchc/README.md
- cpp/trtorchc/main.cpp
- docsrc/tutorials/trtorchc.rst
Allows users to embed prebuild trt engines in TorchScript modules from trtorchc
Fixes #472 
> feat(trtorchc): Embedding engines in modules from the CLI

- cpp/trtorchc/main.cpp
Allows trtorchc to accept workspace sizes larger than 2GB and prints out better errors if string parsing fails. 
> fix(trtorchc): Allow for workspaces larger than 2G and better debugging

- core/runtime/TRTEngine.cpp
- cpp/trtorchc/README.md
- cpp/trtorchc/main.cpp
- docsrc/tutorials/trtorchc.rst
Fix TRT 8 engine capability flags in trtorchc
> fix: Fix TRT8 engine capability flags

- core/compiler.cpp
- core/runtime/TRTEngine.cpp
- core/runtime/runtime.h
BREAKING CHANGE: This bumps the TRTorch ABI version to 3 due to
a new field for engine name included in the serialized form of
TRTEngine. This lets deserialized engines have the same name they
serialized with
> feat(//core/runtime)!: Better and more portable names for engines

- docsrc/RELEASE_CHECKLIST.md
Signed-off-by: Nick Comly <ncomly@nvidia.com>
> Updated to include A30 PBR

- core/runtime/CudaDevice.cpp
- core/runtime/TRTEngine.cpp
- core/runtime/register_trt_op.cpp
- core/runtime/runtime.cpp
- core/runtime/runtime.h
- tests/core/conversion/evaluators/test_aten_evaluators.cpp
- tests/cpp/BUILD
- tests/cpp/test_multi_gpu_serdes.cpp
cases
The runtime device switching doesnt actual change the device. Also we just take whatever device is listed and set it to that which is useless in portable cases. Therefore now we have some way to search through devices and find the best match
> fix(device_conf): Devices never actually got swithed in multi device

- cpp/include/trtorch/trtorch.h
- cpp/src/compile_spec.cpp
- py/trtorch/Input.py
- py/trtorch/_compile_spec.py
- tests/cpp/BUILD
- tests/cpp/test_example_tensors.cpp
- tests/py/test_api.py
Adds a new convience constructor to both Python and C++ APIs to allow users to provide example tensors to implicitly set shape, dtype and layout. Does not allow for dynamic shape, there the existing Input constructors should be used
Fixes #514 
> Example tensors

- cpp/include/trtorch/trtorch.h
- cpp/src/compile_spec.cpp
- examples/int8/training/vgg16/test_qat.py
- py/trtorch/_compile_spec.py
- tests/py/test_api.py
- tests/py/test_qat_trt_accuracy.py
APIs
BREAKING CHANGE: This removes the InputRange Class and op_precision and
input shape fields which were deprecated in TRTorch v0.4.0
> refactor!: Removing deprecated InputRange, op_precision and input_shapes

- py/trtorch/Device.py
- tests/py/test_api.py
There were issues setting fields of trtorch.Device via
kwargs, this patch should resolve those and verify that they
work
> fix(//py): Fix trtorch.Device alternate contructor options

- README.md
- WORKSPACE
- core/lowering/passes/module_fallback.cpp
- core/lowering/passes/remove_nops.cpp
- core/lowering/passes/unpack_var.cpp
Upgrade TensorRT to 8.0.3.4 on x86 platform. Tests pass. 
Jetpack uses TRT 8.0.1.6.
> chore: Upgrade TRT version and README

- README.md
- WORKSPACE
- docker/WORKSPACE.docs
- docsrc/tutorials/installation.rst
- examples/int8/training/vgg16/requirements.txt
- examples/trtorchrt_example/README.md
- py/requirements.txt
- tests/modules/requirements.txt
- tests/py/requirements.txt
Bumps dependency for PyTorch to 1.9.1
> chore: Bumping default dep version on x86 for PyTorch to 1.9.1

- core/lowering/lowering.cpp
- core/lowering/passes/module_fallback.cpp
There was an issue where the module fallback notation pass just assumes
methods exist. This should catch that. This might be something we may want to release as a patch 
Fixes #613, (potentially  #609, Also probably partially solves: #608)
> fix(module_fallback): Catching recursive search if method doesnt exist

- core/lowering/lowering.cpp
- core/lowering/passes/module_fallback.cpp
This commit fixes module level fallback by using method calls
to determine modules to recurse down too. This should be robust
to names other than forward used for methods as well as ignoring
functional modules.
See #619 for patch discussion
> fix(//core/lowering): Fixes module level fallback recursion

- py/build_whl.sh
Theres two versions of CUDA in the build container so we need to explicitly pick the right one.
Fixes #697 
> fix(//py): Constrain the CUDA version in container builds

- .github/workflows/docgen.yml
- .github/workflows/linter.yml
- tests/py/test_api.py
- tests/py/test_ptq_dataloader_calibrator.py
- tests/py/test_ptq_to_backend.py
- tests/py/test_to_backend_api.py
Add an additional test for the top level compilation api
> test: Add a test for the global compile function

- docsrc/requirements.txt
- docsrc/tutorials/getting_started_with_cpp_api.rst
- docsrc/tutorials/runtime.rst
Update deps to support using python3.8
> chore(//docsrc): Update docs deps to fix docgen

- .bazelrc
Changing the pre_built to prebuilt in bazelrc file to keep it consistent
> fix: Fix pre_built name change in bazelrc

- .github/workflows/docgen.yml
- docsrc/contributors/useful_links.rst
- docsrc/py_api/ptq.rst
- docsrc/requirements.txt
> fix(//docsrc): Fix dependencies for docgen

- tests/NOTES.md
Added tracking for disabled CI tests from DLFW integration.
> refactor: Added tracking for disabled CI tests from DLFW integration

- tests/core/conversion/converters/test_activation.cpp
Aligning the CI testing guard for test_activation unit test case. This will make sure that the test suite is consistent across different release guarded by CI.
Non-Breaking change
> fix: Guard test activation for CI testing

- tests/py/test_api.py
Currently, different PRs are reporting failures for linting. Fixing this in NGC branch.
Analogous to PR [753](https://github.com/NVIDIA/Torch-TensorRT/pull/753)
> refactor: Added a py lint to address PR failures

- tests/py/test_api.py
Linter issue reported on recent PRs. Standalone refactor PR
> refactor: Applied py linter

- examples/benchmark/py/README.md
- examples/benchmark/py/config/vgg16.yml
- examples/benchmark/py/config/vgg16_trt.yml
- examples/benchmark/py/perf_run.py
- examples/benchmark/py/requirements.txt
This benchmark script runs perf inference for different configurable backends. (Torch, Torch-TensorRT and TensorRT)
It ingests configurable yaml based configurations to run models with target precisions, devices etc.
This PR is targeted for NGC release and is a replica of PR #768 for NGC branch.
> feat: Added comprehensive perf benchmark in Python for NGC

- core/conversion/converters/impl/batch_norm.cpp
- tests/core/conversion/converters/test_batch_norm.cpp
BatchNorm previously did not support 2D tensors, even though this is valid input (ie. BatchNorm1d). This change fixes this for the BatchNorm converter, as well as updating the unit tests to check against this.
Fixes # #692 
- Unit tests for bug fix
> Update batchnorm to support 2D tensors (ie. BatchNorm1D) and add unit test case.

- notebooks/README.md
Changed the docker run command in the notebook README file to avoid a warning message on container startup
Signed-off-by: Sven Chilton <sven.chilton@gmail.com>
> Changed the docker run command in the notebook README file to avoid a warning message on container startup

- core/lowering/lowering.cpp
- core/lowering/passes/BUILD
- core/lowering/passes/passes.h
- core/lowering/passes/view_to_reshape.cpp
- tests/core/lowering/BUILD
- tests/core/lowering/test_view_to_reshape_pass.cpp
During lowering, I replace `aten::view` with `aten::reshape`. According to the [document](https://pytorch.org/docs/stable/generated/torch.reshape.html?highlight=reshape#torch.reshape), the `aten::reshape`'s input can be contiguous or not. During the shape analysis process, even if the `aten::reshape` input is the output of `aten::permute` it works.
Fixes #742 
> feat: replace aten::view with aten::reshape during lowering

- core/compiler.cpp
Signed-off-by: liangtao07 <liangtao07@meituan.com>
Fixes #811
> Fix the bug that fallback does not support more than one output

- core/conversion/converters/impl/pooling.cpp
- core/plugins/impl/interpolate_plugin.cpp
- tests/core/conversion/converters/test_pooling.cpp
Fixes #791 and support `aten::adaptive_max_pool1d`, `aten::adaptive_avg_pool3d` and `aten::adaptive_max_pool3d` operators.
Besides, #766  needs `aten::adaptive_avg_pool3d` operator.
> Feat: support aten::adaptive_max_pool1d, aten::adaptive_avg_pool3d and aten::adaptive_max_pool3d operators and fix issue #791

- core/conversion/evaluators/aten.cpp
- core/partitioning/SegmentedBlock.h
- core/partitioning/partitioning.cpp
Fixes issues with arange getting handled by the wrong code path. Also some fixes to the partitioning code
Partially Fixes #833
> Fix arange

- WORKSPACE
- core/conversion/conversionctx/ConversionCtx.cpp
- core/conversion/conversionctx/ConversionCtx.h
- cpp/bin/torchtrtc/README.md
- cpp/include/torch_tensorrt/torch_tensorrt.h
- cpp/src/compile_spec.cpp
- docsrc/tutorials/ptq.rst
- docsrc/tutorials/torchtrtc.rst
- docsrc/tutorials/use_from_pytorch.rst
- examples/int8/ptq/main.cpp
- examples/int8/qat/main.cpp
- py/torch_tensorrt/csrc/register_tensorrt_classes.cpp
- py/torch_tensorrt/csrc/tensorrt_classes.cpp
- py/torch_tensorrt/csrc/tensorrt_classes.h
- py/torch_tensorrt/csrc/torch_tensorrt_py.cpp
- py/torch_tensorrt/ts/_compile_spec.py
- py/torch_tensorrt/ts/_compiler.py
- tests/accuracy/test_dla_int8_accuracy.cpp
- tests/accuracy/test_int8_accuracy.cpp
- tests/cpp/test_runtime_thread_safety.cpp
- tests/py/test_to_backend_api.py
BREAKING CHANGE: This commit removes the strict types and max_batch_size apis. We are doing this because the functionality of these APIs in TRT is convoluted and likely to be ignored during building. A replacement for strict types with actual guarantees will be added at a later date.
> refactor: removing the strict_types and max_batch_size apis

- core/conversion/evaluators/aten.cpp
- tests/core/conversion/evaluators/test_aten_evaluators.cpp
Adds an evaluator for `aten::__range_length`
Fixes #835 
> feat(aten::__range_length): Adding range length evaluator

- docs/v1.0.0/tutorials/runtime.html
Fixed broken link per this issue: https://github.com/NVIDIA/Torch-TensorRT/issues/840
> fixed broken link in runtime tutorial

- core/conversion/converters/impl/element_wise.cpp
- tests/core/conversion/converters/test_element_wise.cpp
Support `aten::div.Tensor_mode(Tensor self, Tensor other, *, str? rounding_mode) -> (Tensor)`
Based on the latest master code, i support the `aten::div.Tensor_mode`.
Fixes #766
> feat: support aten::div.Tensor_mode

- cpp/bin/torchtrtc/BUILD
- cpp/bin/torchtrtc/README.md
- cpp/bin/torchtrtc/accuracy.cpp
- cpp/bin/torchtrtc/accuracy.h
- cpp/bin/torchtrtc/fileio.cpp
- cpp/bin/torchtrtc/fileio.h
- cpp/bin/torchtrtc/luts.h
- cpp/bin/torchtrtc/main.cpp
- cpp/bin/torchtrtc/parser_util.cpp
- cpp/bin/torchtrtc/parser_util.h
- docsrc/tutorials/torchtrtc.rst
This PR refactors the CLI to make it easier to add new features in the future. Utility functions have been split out into their own files
- Refactor
> Refactor the CLI

- core/conversion/conversion.cpp
- core/conversion/evaluators/aten.cpp
- core/conversion/var/Var.cpp
- core/conversion/var/Var.h
- tests/core/conversion/evaluators/test_aten_evaluators.cpp
> Support aten::extend evaluator. The Function schema is "aten::extend.t(t[](a!) self, t[] other) -> ()"
Changes some rules about Vars in the conversion context, allowing evaluators to request mutable handles to support in-place operations explicitly
Closes #704 
> Support aten extend

- noxfile.py
After installing nox, the whole test stack can be run
by simply running `nox`.
This will create a venv, install the correct version of
pytorch and tests deps, build and install torch-tensorrt
download models and run the developer test suite.
The env is persistent so the step up steps are cached
> tests(nox): Adding a developer test suite

- docsrc/tutorials/installation.rst
Signed-off-by: KamalM9 <kamal@intuitionmachines.com>
Fix path typo in installation doc sources
- Minor path typo fix
> fix path typo in installation docs

- README.md
Signed-off-by: Nick Comly <85702008+ncomly-nvidia@users.noreply.github.com>
Updating README to direct users to NGC container immediately for download.
Fixes #755 
- Documentation fix. Makes distribution easier
> Updated README.md to point to NGC

- core/conversion/conversion.cpp
- core/conversion/evaluators/aten.cpp
- core/conversion/evaluators/eval_macros.h
- noxfile.py
- tests/core/conversion/evaluators/test_aten_evaluators.cpp
Improves some debugging tools and implements an aten::pow evaluator.
Partially addresses #833
Fixes: #923  
> aten::pow support

- core/conversion/converters/impl/stack.cpp
- tests/core/conversion/converters/test_stack.cpp
Signed-off-by: hongwei03 <hongwei03@corp.netease.com>
When dim is equal to -1, the last dimension is used as the concat dimension by default.But in “stack.cpp”.
So when dim equals -1, assign dim as the last dimension in "stack.cpp".
#931
> fix bug stack when dim -1

- core/lowering/lowering.cpp
- core/lowering/passes/BUILD
- core/lowering/passes/passes.h
- core/lowering/passes/reduce_remainder.cpp
- tests/core/conversion/converters/test_element_wise.cpp
- tests/core/lowering/BUILD
- tests/core/lowering/test_reduce_remainder.cpp
Signed-off-by: Cheng Hang <chang@nvidia.com>
Add support for `aten::remainder.Tensor(Tensor self, Tensor other) -> (Tensor)` and `aten::remainder.Scalar(Tensor self, Scalar other) -> (Tensor)`, which required by Video Swin Transformer. Use lowering to break it down, into 3 steps: 'aten::floor_div->aten::mul->aten::sub'.
Fixes #766
> Add remainders' op

- core/conversion/converters/impl/select.cpp
- tests/core/conversion/converters/test_select.cpp
support `aten::roll(Tensor self, int[1] shifts, int[1] dims=[]) -> (Tensor)`
Fixes #766 #785
> support aten::roll

- core/conversion/converters/impl/select.cpp
- tests/core/conversion/converters/test_select.cpp
`aten::index.Tensor(Tensor self, Tensor?[] indices) -> (Tensor)` is a complicated PyTorch function which can receive several indices. To focus on Video Swin Transformer, this version converter only supports one index. I will improve this converter in a future release.  
Fixes #766 
> support aten::index.Tensor

- core/compiler.cpp
inferred type.
fixes: #814
Addresses the missing type info when first use types can't be determined
> fix(//core): Take user setting in the case we can't determine the

- core/compiler.cpp
- core/ir/Input.cpp
- cpp/src/types.cpp
- py/setup.py
- py/torch_tensorrt/csrc/torch_tensorrt_py.cpp
Use user provided dtype when we can't infer it from the graph
Fixes https://github.com/NVIDIA/Torch-TensorRT/issues/911#issuecomment-1059609092
> fix: Use user provided dtype when we can't infer it from the graph

- core/conversion/conversion.cpp
Signed-off-by: Cheng Hang <calvinhance@gmail.com>
When using torch.split(), converters of `aten::split` would return a list of IVar which is actually a list of TensorContainers. When subsequent instructions use the result returned by `aten::split`, it would encounter such a bug:
```bash
RuntimeError: [Error thrown at core/conversion/var/Var.cpp:132] Expected isITensor() to be true but got false
Requested ITensor from Var, however Var type is c10::IValue
```
This indicates that we have to do something in order to unpack the tensors contained within TensorContainers. 
I did this in function `ConvertBlockToNetDef` in `core/conversion/conversion.cpp`, where there is a block just targetted at handling `prim::listunpack` instructions. Since `prim::listunpack` always follow the `aten::split`, we …
> Fix listunpack by checking TensorContainer

- core/partitioning/SegmentedBlock.h
- core/partitioning/partitioning.cpp
- tests/core/partitioning/test_resolve_nontensor_inputs.cpp
Signed-off-by: MenglingD [dengmengling@meituan.com](dengmengling@meituan.com)
Fix TensorList inputs in tensorrt engine building after parititioning.
Fixes [#915 ](https://github.com/NVIDIA/Torch-TensorRT/issues/915)
After `resolveNonTensorInputBlocks` process, `resolveTensorListInputBlocks` is required for `tensorrt segmented blocks`. In `resolveTensorListInputBlocks` process, we find all nodes which depend `TensorList inputs` and produce non-tensor outputs, and appends those nodes to the producer's block of the depended `TensorList inputs`.
> fix: tensorList inputs convertion failed in tensorrt engine building after fallback partitioning

- core/lowering/lowering.cpp
- core/lowering/passes/BUILD
- core/lowering/passes/passes.h
- core/lowering/passes/remove_set_attrs.cpp
- core/lowering/passes/remove_unnecessary_casts.cpp
- noxfile.py
- tests/core/lowering/BUILD
- tests/core/lowering/test_remove_unnecessary_casts.cpp
- tests/cpp/cpp_api_test.h
- tests/cpp/test_compiled_modules.cpp
- tests/cpp/test_default_input_types.cpp
- tests/cpp/test_example_tensors.cpp
- tests/cpp/test_modules_as_engines.cpp
- tests/cpp/test_multi_gpu_serde.cpp
- tests/cpp/test_serialization.cpp
- tests/modules/hub.py
- tests/modules/requirements.txt
This PR adds support for aten::Int / prim::NumToTensor in a few limited cases. 
1. a direct `prim::NumToTensor -> aten::Int `
2. `prim::NumToTensor -> X -> aten::Int` in cases where the tensors used are single use and can safely be fused 
Fixes #513, Fixes #707
Partially: #867, #829, #785, #711, #660
> Adding limited support for aten::Int

- core/lowering/passes/reduce_gelu.cpp
- tests/core/lowering/test_reduce_gelu.cpp
Implement a patch for gelu schema change in older NGC containers
Fixes https://github.com/NVIDIA/Torch-TensorRT/issues/776 
> fix: Implement a patch for gelu schema change in older NGC containers

- core/conversion/converters/impl/activation.cpp
- tests/core/conversion/converters/test_activation.cpp
Out_tensor of ParametricReLU shape is all 0, when nDims of slopes is 1, and it not equal to nDims of input.
this pr make sure nDims of slopes is equal to nDims of input.
#789
> keep slopes ndim and in ndims the same

- core/conversion/converters/impl/cast.cpp
- core/lowering/passes/reduce_to.cpp
2 bugs found in our lowering pass for aten::to:
1: the argument mismatch in signatures
2: we are omitting the device info when we lower aten::to, this will incur the device mismatch problem in later Torchscript running part in our shape analysis for fallback.
#941 
#954 
> fix: fix bugs in aten::to

- tests/core/lowering/test_reduce_to_pass.cpp
Update the test code for aten::to after fixing the bug #958, 
> test: update the test for aten::to after fixing

- core/conversion/converters/impl/cast.cpp
- core/conversion/converters/impl/cumsum.cpp
- core/conversion/converters/impl/element_wise.cpp
Fix bugs encountered when converting a RoBERTa model. 
Fixes #963 
Specifically, it fixes three things:
- For `aten::ne.Scalar(Tensor self, Scalar other) -> (Tensor)`,  the datatype of Scalar is by default initialized to be of type float. This should be int32 in this case.
- For `aten::cumsum(Tensor self, int dim, *, int? dtype=None) -> (Tensor)`, the zeroValue which stores runningSum, is by default initialized to be of type float. This should be int32 in this case. 
- For `aten::to.dtype(Tensor self, int dtype, bool non_blocking=False, bool copy=False, int? memory_format=None) -> (Tensor)`, it could be casting tensor to `long` datatype, but this cannot be processed in our code. We simply add an entry in `get_at_trt_type_map`, where `at::kLong` would be mapped to …
> Fix roberta conversion bugs

- .github/workflows/blossom-ci.yml
- core/lowering/register_trt_placeholder_ops.cpp
- docker/WORKSPACE.docs
- noxfile.py
Setting up CI ffor Torch-TensorRT
> (//ci): Setup of CI workflow

- docker/README.md
Allows docker to build with a specified version of the container.
In other words, using `docker_buildkit` is mandatory to change the version of the base container to build docker.
So, it is grateful if the `docker/README.md` suggests using `docker_buildkit` explicitly, or adding "DOCKER_BUILDKIT=1` before the command.
This ENV is also used in [a REAME.md in pytorch](https://github.com/pytorch/pytorch/blob/master/Dockerfile#L3-L9).
- ~[ ] My code follows the style guidelines of this project (You can use the linters)~
- ~[ ] I have commented my code, particularly in hard-to-understand areas and hacks~
- ~[ ] I have made corresponding changes to the documentation~
- ~[ ] I have added tests to verify my fix or my feature~
- ~[ ] New and …
> Allows docker to build with a specified version of the container

- noxfile.py
timm package updates the torch version inside the nox session which becomes incompatible with the cuda version and thereby fails the hub.py script inside the CI container.
Added the installation step for py/requirements.txt so that torch package is not disturbed inside the container.
> fix: Preempt torch package override via timm in nox session

- core/partitioning/shape_analysis.cpp
Dict type was missed for input types in shape analysis. 
Fixes #981 
> fix: support dict type for input in shape analysis

- core/lowering/register_trt_placeholder_ops.cpp
- core/runtime/runtime.cpp
Extended the support for Orin compute capability.
> feat: Added compute capability for Orin

- py/setup.py
- tests/py/test_ptq_dataloader_calibrator.py
- tests/py/test_ptq_to_backend.py
- tests/py/test_ptq_trt_calibrator.py
- tests/py/test_trt_intercompatibility.py
Added fixes required for CI pipeline
> Fixes for CI pipeline pre-cxx11 pipeline

- core/partitioning/partitioning.cpp
- core/partitioning/shape_analysis.cpp
There are some cases that TensorRT segments have Non-Tensor inputs after segmentation. In this case, if the nodes that produce these Non-Tensor Inputs are not supported by TensorRT, then we have to find a proper interface to re-segment this TensorRT segment again.
The previous code just naively segments the nodes one by once, which causes many issues such as what we have in #922 
Fixes #922
> fix: refactor the resegmentation in ResolveNonTensorInputs

- core/ir/ir.cpp
- core/runtime/TRTEngine.cpp
- core/runtime/runtime.h
- cpp/include/torch_tensorrt/torch_tensorrt.h
- py/torch_tensorrt/ts/_compiler.py
- tests/util/run_graph_engine.cpp
Fixes an issue where different classes of delimiters would not properly be handled when deserializing TRT engines. 
Fixes #930
Fixes #982 
> fix(//core/runtime): Support more delimiter variants

- noxfile.py
Added support for cxx11 ABI in noxfile
> feat: Extending nox for cxx11 ABI version

- .github/workflows/docgen.yml
- .github/workflows/linter.yml
- .gitignore
- docsrc/conf.py
- docsrc/requirements.txt
- py/setup.py
Changes the documentation theme to the PyTorch sphinx theme. 
> docs: Update the documentation theme to PyTorch

- .github/actions/assigner/.gitattributes
- .github/actions/assigner/.gitignore
- .github/actions/assigner/action.yml
- .github/actions/assigner/dist/index.js
- .github/actions/assigner/package-lock.json
- .github/actions/assigner/package.json
- .github/actions/assigner/src/main.ts
- .github/actions/assigner/tsconfig.json
- .github/code-owners.yml
- .github/workflows/assigner.yml
- package-lock.json
This adds a github action which will auto add reviewers to any PRs by label and assignees to triage issues by labels. This is configured but .github/code-owners.yml
> Adding an action to automatically assign reviewers and assignees

- .github/actions/assigner/dist/index.js
- .github/actions/assigner/src/main.ts
> Add PR assigner support

- core/lowering/passes/module_fallback.cpp
Aligned with prim::Enter API update in module fallback 
> (//core): Align with prim::Enter in module fallback

- core/conversion/converters/impl/select.cpp
Added a variant to aten::split as per latest torch API update
> (//core): Added a variant for aten::split

- README.md
- noxfile.py
Reduced host dependency based sessions from nox lists.
Switched to environment variable based context switching. Reduces redundant sessions. We already have multiple sessions as per different Python versions.
#1056 
> feat(nox): Replacing session with environment variable

- tests/core/partitioning/partitioning_test.bzl
format the bzl file with buidifier
> format by buildifier

- notebooks/README.md
Updated the repo's origin and the example container tag. Also split up the docker run commands across several lines to improve legibility.
Signed-off-by: Sven Chilton <sven.chilton@gmail.com>
- Documentation update
> Modified the notebooks directory's README file

- py/torch_tensorrt/fx/lower.py
- py/torch_tensorrt/fx/lower_setting.py
- py/torch_tensorrt/fx/passes/lower_basic_pass.py
- py/torch_tensorrt/fx/test/tracer/test_acc_tracer.py
- py/torch_tensorrt/fx/tracer/acc_tracer/acc_ops.py
364639a8ab2ee7531ce5259b8985a3c90bda4fdf Wei Wei <wwei6@fb.com> [fx2trt] target files added
07d8e842b54b9c727f4215239f6c007cc7a62c9f Wei Wei <wwei6@fb.com> Swap fx2trt_oss to torch_tensorrt
74731c90fd63e41ff5997887d8f72ca0b805cf8d Yinghai Lu <yinghai@fb.com> Fix uru_10x10 test
6c53d36a08a7d465a1108d7154ef29a373eb38cc Wei Wei <wwei6@fb.com> [fx2trt] Modify lower setting class to accommandate AIT lowering
6f873f4f3ece9d476479eb7c9633d38554dd8692 Oleg Khabinov <khabinov@fb.com> [fx2trt] Make sure acc_tracer belongs only to single target
529a5750ace2bede6e9b7a9922a0f75c459df16b Shirong Wu <shirong@fb.com> Enable explicit batch dim for MTS gpu benchmark
2d284df94ddb530f3a8875fdc76796fad508ec29 Wei Wei <wwei6@fb.com> [fx2trt] remove wildcard for obj of torch_fx2trt in TARGETS …
> [FX] Sync to OSS

- docsrc/index.rst
- docsrc/tutorials/serving_torch_tensorrt_with_triton.rst
Changed the name of the documentation section
> amending triton deployment docs

- core/conversion/converters/impl/max.cpp
- tests/core/conversion/converters/test_reduce.cpp
Signed-off-by: dperi <dperi@nvidia.com>
Fix keep_dims functionality for aten::max
> fix: Fix keep_dims functionality for aten::max

- tests/util/util.cpp
- tests/util/util.h
Updating the tolerance metric using absolute and relative tolerance threshold.
This PR directly impacts the CI, DLFW workflow.
#1054 
> feat(//tests): Update rtol and atol based tolerance for test cases

- docsrc/contributors/partitioning.rst
Documentation for partitioning.
> doc: add the explanation for partition phases on docs

- cpp/bin/torchtrtc/README.md
- cpp/bin/torchtrtc/accuracy.cpp
- cpp/bin/torchtrtc/accuracy.h
- cpp/bin/torchtrtc/main.cpp
- docsrc/tutorials/torchtrtc.rst
Added rtol + atol tolerance check for torchtrtc. Similar to what we have for test benchmarks.
This PR is a replica of https://github.com/NVIDIA/Torch-TensorRT/pull/1038
#1030 
> feat (//cpp): Using atol and rtol based tolerance threshold for torchtrtc

- core/conversion/converters/BUILD
- core/conversion/converters/impl/bitwise.cpp
- core/lowering/register_trt_placeholder_ops.cpp
- tests/core/conversion/converters/BUILD
- tests/core/conversion/converters/test_bitwise.cpp
- tests/util/run_graph_engine.cpp
Add converter for torch.bitwise_not
> feat (//core/conversion) : Add converter for torch.bitwise_not

- py/setup.py
Do not need to check bazel if --fx-only
> [FX] --fx-only does not need to check bazel

- README.md
- examples/fx/quantized_resnet_test.py
- py/torch_tensorrt/fx/converters/acc_ops_converters.py
- py/torch_tensorrt/fx/converters/converter_utils.py
- py/torch_tensorrt/fx/fx2trt.py
- py/torch_tensorrt/fx/passes/graph_opts.py
- py/torch_tensorrt/fx/passes/lower_pass_manager_builder.py
- py/torch_tensorrt/fx/test/converters/acc_op/test_adaptive_avgpool.py
- py/torch_tensorrt/fx/test/converters/acc_op/test_any.py
- py/torch_tensorrt/fx/test/converters/acc_op/test_as_strided.py
- py/torch_tensorrt/fx/test/converters/acc_op/test_avgpool.py
- py/torch_tensorrt/fx/test/converters/acc_op/test_batchnorm.py
- py/torch_tensorrt/fx/test/converters/acc_op/test_binary_ops.py
- py/torch_tensorrt/fx/test/converters/acc_op/test_cat.py
- py/torch_tensorrt/fx/test/converters/acc_op/test_chunk.py
- py/torch_tensorrt/fx/test/converters/acc_op/test_clamp.py
- py/torch_tensorrt/fx/test/converters/acc_op/test_convolution.py
- py/torch_tensorrt/fx/test/converters/acc_op/test_sigmoid.py
- py/torch_tensorrt/fx/test/passes/test_graph_opts.py
- py/torch_tensorrt/fx/test/quant/test_quant_trt.py
91196dedd10ed4061bef719b01fe917192a6fc17 Shiyan Deng <dsy842974287@fb.com> fix EngineHolder
608acce060d91ac93099f59e6165d43ffd79d50a Shiyan Deng <dsy842974287@fb.com> delete unused file
f88cb1566ae1c72634668fa26fadc3ef368b9727 Alex Beloi <alexbeloi@fb.com> [fx] add common_subexpression_elimination graph opt
b079de89bce912c29284809722cae63cb185c481 Yinghai Lu <yinghai@fb.com> handle list of integers in SliceOp check
e8f8dbda72625872a2657cdfd09dd59209f98090 Shiyan Deng <dsy842974287@fb.com> Add a pass to eliminate unsqueeze + cat + getitem pattern
675b28120c432c63bf4d451a4479b2376f73201d Kefei Lu <kefeilu@fb.com> Back out "[fx] add common_subexpression_elimination graph opt"
a3fb38bb6193b86a0ef0795a9104c073f5044598 Shiyan Deng <dsy842974287@fb.com> Back out "Back out "[fx] add …
> [FX] Sync enhancement done internally at Meta

- examples/int8/training/vgg16/main.py
The example uses the Python 2 `.next()` syntax [here](https://github.com/pytorch/TensorRT/blob/e19cbfc9d3e4313c43f15c17235255cff06b948e/examples/int8/training/vgg16/main.py#L96):
```python
data = iter(training_dataloader)
images, _ = data.next()
```
which will break if a PyTorch version after https://github.com/pytorch/pytorch/pull/78594 is used as the compat assignment was removed.
According to [PEP 3114](https://peps.python.org/pep-3114/) the new Python 3 syntax should be used:
```python
out = next(iterator)
```
> Use py3 next() syntax

- py/setup.py
Fixes torch upper bound version restriction in setup.py install_requires by adding missing comma.
Fixes [# (1002)](https://github.com/pytorch/TensorRT/issues/1002)
> Add missing comma for proper torch versioning in setup.py

- py/torch_tensorrt/fx/__init__.py
- py/torch_tensorrt/fx/input_tensor_spec.py
- py/torch_tensorrt/fx/lower.py
- py/torch_tensorrt/fx/passes/lower_pass_manager_builder.py
- py/torch_tensorrt/fx/passes/pass_utils.py
- py/torch_tensorrt/fx/test/converters/acc_op/test_prod.py
- py/torch_tensorrt/fx/test/core/test_input_tensor_spec.py
6703b98dff0695d91026f057b951dba1355825fa Shreyansh Prajapati <shreyanshp@fb.com> Test dynamic shape support for acc_ops.prod
c822345d6d673e1653c2208435e34ab400bada3d Jason Park <jasonjk@fb.com> Add support for generic torch ops to be used in training.
> [FX] Changes done internally at Facebook

- README.md
- WORKSPACE
- core/conversion/converters/converter_util.cpp
- tests/core/partitioning/test_fallback_graph_output.cpp
- third_party/cudnn/archive/BUILD
> feat: Upgrade TensorRT to 8.4 EA

- docsrc/tutorials/getting_started_with_fx_path.rst
> [FX] Update getting_started_with_fx_path.rst

- README.md
Update readme.md to add some FX contents.
> [FX] Update README.md

- .circleci/config.yml
> Different platform versions for each channel

- .circleci/config.yml
- py/setup.py
- py/torch_tensorrt/__init__.py
- py/torch_tensorrt/_compile.py
If the TensorRT python api is available then use that to load the .so files
> feat(//py): Use TensorRT to fill in .so libraries automatically if possible

- core/ir/GraphInputs.cpp
- core/partitioning/partitioning.cpp
- py/torch_tensorrt/csrc/tensorrt_classes.cpp
- py/torch_tensorrt/csrc/torch_tensorrt_py.cpp
- py/torch_tensorrt/ts/_compile_spec.py
- tests/cpp/test_collection.cpp
- tests/py/test_collections.py
Signed-off-by: inocsin <vcheungyi@163.com>
Support python api based on [#802](https://github.com/pytorch/TensorRT/pull/802) and https://github.com/pytorch/TensorRT/tree/collections
> Collection: Python api support

- core/compiler.cpp
- tests/core/partitioning/BUILD
- tests/core/partitioning/test_loading_model.cpp
When there is fallback, the converted model will contain input names that inherited from loweredGraph, such as x.1. 
These names cannot be parsed by torch.jit.load().
This induces some errors like: #973 , #1112 . 
We stop using the names from loweredGraph, we use the input names that are similar to what we are using when there is no fallback: input_0, input_1, ..
Fixes #973,  #1112
> fix: fix the parsing related model loading bug

- core/partitioning/partitioning.cpp
> fix: fix the fallback related issue after merging collection

- core/partitioning/partitioning.cpp
If there are nonTensor input for the graph and the nodes that use this nonTensor input are supported in torch-tensorrt, then these nodes will be segmented into TensorRT subgraph, which causes errors since nonTensor input is not directly supported in TRT engine. 
> fix: fix the error that collection input segmented into trt subgraph

- .circleci/config.yml
- core/conversion/converters/impl/max.cpp
- py/build_whl.sh
- py/ci/Dockerfile.ci
- py/ci/build_whl.sh
- py/requirements.txt
- py/setup.py
- third_party/cudnn/local/BUILD
- third_party/tensorrt/local/BUILD
- toolchains/BUILD
- toolchains/ci_workspaces/WORKSPACE.sbsa
- toolchains/ci_workspaces/WORKSPACE.x86_64.release
- toolchains/ci_workspaces/WORKSPACE.x86_64.release.rhel
- toolchains/ci_workspaces/WORKSPACE.x86_64.release.ubuntu
- toolchains/distro/BUILD
Automatically builds release binaries for x86 and aarch64
> feat(//circleci): Adding release automation

- core/conversion/converters/impl/element_wise.cpp
- tests/core/conversion/converters/test_element_wise.cpp
- tests/util/run_graph_engine.cpp
Signed-off-by: Michael Feliz <michael.feliz@getcruise.com>
Currently the aten::mul converter for Tensor * Scalar assumes that the scalar value is a float. This causes errors for int Tensor * int. Resolve this by using scalar_to_tensor.
Fixes # [(issue)](https://github.com/pytorch/TensorRT/issues/1094)
> fix: support int tensor * int scaler in aten::mul

- .circleci/config.yml
- core/conversion/conversionctx/ConversionCtx.cpp
- core/conversion/converters/converter_util.cpp
- core/conversion/converters/converter_util.h
- core/conversion/converters/impl/select.cpp
- core/lowering/register_trt_placeholder_ops.cpp
- core/partitioning/partitioning.cpp
- cpp/bin/torchtrtc/main.cpp
- py/torch_tensorrt/csrc/register_tensorrt_classes.cpp
- py/torch_tensorrt/csrc/tensorrt_classes.cpp
- py/torch_tensorrt/fx/test/converters/acc_op/test_convolution.py
- py/torch_tensorrt/fx/test/converters/acc_op/test_type_as.py
- tests/core/conversion/converters/test_cast.cpp
1. The torch-tensorrt new release triggered the bug of conv3d groups test. Potential reason could be TRT 8.4.1
With current default workspace size, it complains insufficient workspace size
```
[08/02/2022-20:17:52] [TRT] [W] The implicit batch dimension mode has been deprecated. Please create the network with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag whenever possible.
[08/02/2022-20:17:52] [TRT] [W] TensorRT was linked against cuDNN 8.4.1 but loaded cuDNN 8.3.2
[08/02/2022-20:17:52] [TRT] [W] GPU error during getBestTactic: [CONVOLUTION]-[acc_ops.conv3d]-[conv3d_1] : an illegal memory access was encountered
[08/02/2022-20:17:52] [TRT] [E] 1: [virtualMemoryBuffer.cpp::~StdVirtualMemoryBufferImpl::104] Error Code 1: Cuda Runtime (an illegal memory access was encountered) …
```
> [FX] disable 2 of conv3d and type_as tests 

- core/conversion/converters/impl/unary.cpp
- tests/core/conversion/converters/test_unary.cpp
Adds support for aten::abs with integer input. Previous implementation relied on the UnaryLayer kABS implementation which does not support integers.
https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_network_definition.html#a77831224c9a72ad02587a56ded93c672
```
Generally the input must have a floating-point type (or kINT8 as a quantized float), except for the following operations:
kSIGN accepts a floating-point or Int32 tensor.
kNOT requires a Bool tensor.
```
Fixes # (https://github.com/pytorch/TensorRT/issues/1231)
- Breaking change (fix or feature that would cause existing …
> [feat] Add support for integers in aten::abs converter (#35)

- docsrc/tutorials/ptq.rst
Signed-off-by: Nick Comly <85702008+ncomly-nvidia@users.noreply.github.com>
Fixed `compile(model, compile_spec)` to use kwargs instead. See 3557747.
Another option is to just use `**compile_spec` but we have been have been pushing kwargs instead
> Update PTQ example to fix new compile_spec requirements

- cpp/bin/torchtrtc/BUILD
- cpp/bin/torchtrtc/CMakeLists.txt
- cpp/bin/torchtrtc/README.md
- cpp/bin/torchtrtc/main.cpp
- docsrc/tutorials/torchtrtc.rst
This PR addresses the RFC for custom torch ops and converters. Details can be referenced here:
https://github.com/pytorch/TensorRT/discussions/1103
#877 
> feat: Added support for custom torch operators and converters in torchtrtc

- core/conversion/converters/impl/conv_deconv.cpp
- tests/core/conversion/converters/test_conv_deconv.cpp
Add output padding support in ConvTranspose2d/3d
Fixes #623 
> Add outputPadding in deconv

- core/conversion/conversionctx/ConversionCtx.cpp
- core/conversion/conversionctx/ConversionCtx.h
- core/util/macros.h
Refactored the hard coded values to macro for DLA specific memory sizes
> refactor: Changed the hardcoded values to macros for DLA memory sizes

- core/conversion/converters/converter_util.cpp
- core/conversion/converters/impl/element_wise.cpp
- tests/core/conversion/converters/test_element_wise.cpp
Adds automatic type promotion to match the default torch-script behavior for element-wise ops. Debug messages added for the type mismatch and cast.
Messages written to log.
```
DEBUG: [Torch-TensorRT] - Type mismatch for inputs in element-wise operation %3 : Tensor = aten::add(%0, %1, %2): Int32, Float32
DEBUG: [Torch-TensorRT] - Element-wise op type promotion adding cast from Int32 to Float32 for layer %3 : Tensor = aten::add(%0, %1, %2)
``` …
> [feat] Add automatic type promotion to element-wise ops

- core/partitioning/partitioning.cpp
In partitioning, when we check if a node would modify the input value, we use the node->schema() function from PyTorch previously. However, this function could return a nullptr in some cases, which triggers a error showing `Schema not found for node. File a bug report`
Fixes #1227 
> fix: fix the "schema not found for node" error

- CONTRIBUTING.md
> chore: Fix contributing doc

- core/conversion/converters/converter_util.cpp
- core/conversion/converters/converter_util.h
- core/conversion/converters/impl/element_wise.cpp
- core/conversion/converters/impl/select.cpp
- core/lowering/passes/op_aliasing.cpp
- tests/core/conversion/converters/test_select.cpp
Signed-off-by: inocsin <vcheungyi@163.com>
> feat: support scatter.value and scatter.src

- .gitmodules
- .pre-commit-config.yaml
Not sure if this is absolute best way to do this but will let us share `WORKSPACE`s which leverage the internal build server in a private space. This should not effect anyone else's workflow.
NVIDIA folks can set up the env using `git clone --recursive git@github.com/pytorch/tensorrt` 
> Internal workspace workflow

- core/conversion/converters/impl/element_wise.cpp
- core/conversion/converters/impl/select.cpp
- core/conversion/converters/impl/shuffle.cpp
Signed-off-by: Cheng Hang <calvinhance@gmail.com>
To support dynamic-batch compilation of swin transformer/BERT, I have added dynamic batch support of the following relevant op converters:
1. `aten::reshape`
2. `aten::select`
3. `aten::roll`
4. `aten::flatten`
5. `aten::slice` The older version can support dynamic shape, but will report a lot of trt ERRORs, meanwhile compiles successfully.  This can be reproduced for TRT 8.4, and it did not appear for TRT 8.2. I suppose it is caused by some new checks performed in TRT8.4.
To resolve this issue, I have slightly changed the order of codes for dynamic slice, and it did not change the logics. By such simple manipulation, the ERRORs disappear.
Fixes #1271
- Bug fix (non-breaking …
> Support swin/bert with dynamic batch

- WORKSPACE
The SHA256 and strip_prefix of cudnn in `WORKSPACE` file is incorrect, which causes compilation error.
> correct sha256sum of cudnn

- docsrc/tutorials/installation.rst
- py/setup.py
- toolchains/BUILD
- toolchains/jp_workspaces/WORKSPACE.jp50
Update the docs to use a simpler workflow to set up on jetson.
> Jetson workspace

- examples/int8/ptq/main.cpp
Adding truncate_long_and_double for PTQ C++ path
> chore: Truncate long and double for ptq CPP path

- core/conversion/converters/impl/element_wise.cpp
- tests/core/conversion/converters/test_element_wise.cpp
Adds a converter for aten::square as an element_wise op.
> feat: Add support for aten::square

- core/compiler.cpp
> fix: fix misleading skipping partitioning msg

- core/conversion/converters/impl/constant_pad.cpp
- tests/core/conversion/converters/test_constant_pad.cpp
The converter for aten::constant_pad_nd currently assumes float32 inputs. Change adds support and test for integer inputs.
> fix: Add int support to constant_pad_nd

- core/partitioning/partitioning.cpp
Using a set of Value* in registerSegmentsOutputs introduces unnecessary non-determinism in partitioning. Sort the set by Value*->unique to resolve this. 
> fix: Resolve non-determinism in registerSegmentsOutputs

- notebooks/getting_started_with_fx_path_lower_to_trt.ipynb
> update fx notebook

- .github/workflows/linter.yml
Signed-off-by: Naren Dasan <1790613+narendasan@users.noreply.github.com>
> fix(tools): Fix linter to not depend on docker

- core/conversion/converters/impl/select.cpp
- core/conversion/evaluators/prim.cpp
- tests/core/conversion/converters/test_select.cpp
Support multiple indices for aten::index.Tensor.  
In Pytorch, `aten::index.Tensor` can receive several indices, like this:
```
x = torch.rand(5, 7, 10)
idx0 = torch.tensor([0, 0, 0, 0])
idx1 = torch.tensor([1, 1, 1, 1])
idx2 = torch.tensor([2, 2, 2, 2])
y1 = x[idx0, idx1, idx2] # result is like tensor([x[0, 1, 2], x[0, 1, 2], x[0, 1, 2], x[0, 1, 2]])
y2 = x[idx0] # result is like tensor([x[0, :, :], x[0, :, :], x[0, :, :], x[0, :, :]])
```
Previous, we only support one indice in PR #921 .  Now we support serval indices for `aten::index.Tensor`. 
Fixes #1274 
> Support multiple indices for aten::index.Tensor

- .circleci/config.yml
> chore: Adding CMake to the CI

- .circleci/config.yml
- README.md
- WORKSPACE
- py/requirements.txt
> feat: Upgrade Pytorch to 1.12.1 and TensorRT to 8.4.3.1

- .circleci/config.yml
> chore: Adding NGC build path

- core/partitioning/shape_analysis.cpp
- cpp/bin/torchtrtc/main.cpp
- cpp/include/torch_tensorrt/torch_tensorrt.h
This PR fixes the issues in compilation failures on Windows platform.
Fixes # (issue) #1245 
> fix!: Fixed Windows compilation failures

- docsrc/getting_started/getting_started_with_windows.rst
Adding a guideline to build Torch-TensorRT on Windows platform using MS Visual Studio
> chore: Adding a guideline to build on Windows platform

- examples/int8/training/vgg16/export_qat.py
- noxfile.py
- py/torch_tensorrt/ptq.py
- tests/core/conversion/converters/test_select.cpp
- tests/py/ptq/test_ptq_trt_calibrator.py
> chore: Fix data loader issues and nox file paths

- core/conversion/converters/impl/unary.cpp
- tests/core/conversion/converters/test_unary.cpp
The unary layer does not support integer inputs to RECIP. Pytorch implicitly casts integer inputs to float for aten::reciprocal so we can add the same cast here to add support.
> [feat] add support for aten::reciprocal(int)

- examples/fx/lower_example.py
- py/torch_tensorrt/_compile.py
- py/torch_tensorrt/fx/__init__.py
> enable direct call to fx.compile()

- py/torch_tensorrt/csrc/torch_tensorrt_py.cpp
Fixing the failures for pybind related on nightly builds in circleci
> fix: Fixing pybind error on nightly

- core/conversion/converters/impl/select.cpp
- tests/core/conversion/converters/test_select.cpp
Repeated aten::index ops in a convertible block would cause layer name conflicts. Add node_info to the layer names to avoid this.
`Error Code 4: Internal Error (Repeated layer name: compute_dim0_0 (layers must have distinct names))`
> [fix] Avoid layer name conflicts in aten::index

- core/conversion/converters/impl/select.cpp
- tests/core/conversion/converters/test_select.cpp
aten::unbind removes the dimension it splits from the resulting tensors. The converter previously did not.
Fixes # (#1374)
> [fix] Fix output dimensions of aten::unbind converter

- core/conversion/converters/impl/unary.cpp
- tests/core/conversion/converters/test_unary.cpp
This feature adds the sign unary converter
Fixes #1074 
> feat: Add converter for aten::sign unary op

- core/conversion/converters/impl/squeeze.cpp
- core/util/trt_util.cpp
- core/util/trt_util.h
- tests/core/conversion/converters/test_squeeze.cpp
Adds converter support for aten::squeeze(Tensor) which will remove any static dimension of size 1. An existing converter supports aten::squeeze(Tensor, int dim).
> Add support for aten::squeeze without a dim

- core/conversion/converters/impl/element_wise.cpp
- tests/core/conversion/converters/test_element_wise.cpp
Remove incorrect cast to float in the floor_divide converter that created type-mismatches between the converted and original models.
Fixes # ()
> [fix] incorrect casting behavior in floor_divide

- README.md
- pyproject.toml
I've seen a few people (including myself get bit by not having clear instructions to pip install the library)
https://github.com/pytorch/TensorRT/issues/1233
https://github.com/pytorch/TensorRT/issues/1214
I can't update the release notes to fix the actual issue but regardless I believe installation instructions should be on the front page
If you like I can also update the dependencies here https://github.com/pytorch/TensorRT/blob/master/pyproject.toml so installation instructions will be a 1 liner
> Add correct pip install instructions

- core/conversion/converters/impl/select.cpp
- tests/core/conversion/converters/test_select.cpp
- Identified issue arising in the deepset/roberta-base-squad2 HuggingFace network (https://huggingface.co/deepset/roberta-base-squad2) during conversion
```
RuntimeError: [Error thrown at core/conversion/conversion.cpp:428] Expected eval_list->elements().size() == n->outputs().size() to be true but got false
Size of evaluated results: 3 and node outputs size: 2 must match.
```
- Bug involves the use of a negative index (-1) when applying the `aten::split` operator
- Improved axis handling in `add_split` to account for negative indexing
- Improved error handling in `add_split` to ensure valid axes for C++ indexing
- Added regression test to replicate error
Fixes #1410 
- [ x ] My code follows the style guidelines of this project (You can …
> fix: `aten::split` behavior with negative indexing

- core/lowering/lowering.cpp
- core/lowering/passes/exception_elimination.cpp
In some cases with exception , the compilation process stuck. The reason is that torch::jit::EliminateExceptions() pass conflict with EliminateCommonSubexpression() pass. 
This could be resolved by changing the execution order for now. 
Fixes #1408 
> fix: fix compilation stuck bug caused by elimination exception

- docs/_sources/tutorials/ptq.rst.txt
- py/torch_tensorrt/fx/converters/acc_ops_converters.py
- py/torch_tensorrt/fx/passes/lower_basic_pass.py
- py/torch_tensorrt/fx/passes/lower_pass_manager_builder.py
- py/torch_tensorrt/fx/passes/pass_utils.py
- py/torch_tensorrt/fx/test/converters/acc_op/test_clamp.py
- py/torch_tensorrt/fx/test/passes/test_fix_reshape_batch_dim.py
- py/torch_tensorrt/fx/test/tracer/test_acc_tracer.py
- py/torch_tensorrt/fx/test/tracer/test_dispatch_tracer.py
- py/torch_tensorrt/fx/tracer/acc_tracer/acc_ops.py
afdc533da031a64e162bb08c8629ff38739e24f8 Wei Wei <wwei6@fb.com> [fx2trt] disable dispatch trace leaf node test c22f691e6eae1b06ecd301eb6285b32d5dc9717c Mike Iovine <mikeiovine@fb.com> [fx2trt] Support dict inputs in acc tracer 8c05a3c57b1f5c63108b979ef8c61411525d0b1f Mike Iovine <mikeiovine@fb.com> [fx2trt] Support namedtuple access in acc tracer getattr 1580805d827eb40c941e769b0b99e7c6a3ed6f89 Wei Wei <wwei6@fb.com> [fx2trt] add reshape unit test baab27b81b1275de92fdaf760a158ce951564d33 Donglin Xia <doxia@fb.com> Register avg_pool3d for acc_op in acc_op.py ae4c4e2c3c18d78542140fcc30e1c24f7c647ef3 Wei Wei <wwei6@fb.com> [aten2trt] init check-in 87ef03338c9a25c5a610a2eb590345e8935f8d75 Wei Wei <wwei6@fb.com> [aten2trt] add binary ops 2bb168517ace7e638cffc7a241b1cbf528790b92 Mike Iovine …
> [FX]  Fix clamping float32 boundary values, aten2trt init check-in, fix slice issues

- core/conversion/converters/impl/select.cpp
- tests/core/conversion/converters/test_select.cpp
Adds a converter for aten::where.
> [feat]Add converter for aten::where

- core/conversion/converters/impl/normalize.cpp
- tests/core/conversion/converters/test_normalize.cpp
Adds a converter support for `aten::frobenius_norm.dim(Tensor self, int[1] dim, bool keepdim=False) -> (Tensor)`
> [feat]Add converter support for aten::frobenius_norm

- core/conversion/converters/impl/einsum.cpp
- tests/core/conversion/converters/test_einsum.cpp
- `aten::einsum` schema in 1.14 is `aten::einsum(str equation, Tensor[] tensors, *, int[]? path=None) -> Tensor`, whereas that of 1.13 has only the first two arguments
- Updated test cases to use three arguments instead of two
- Updated converter schema to allow for additional arguments
- Fails 1.13 tests, as 1.14 schema is incompatible
Relevant to PR #1412 
- Will fail existing CI tests, as 1.14 schema is not compatible with 1.13 schema
- [ x ] I have commented my code, particularly in …
> fix: `aten::einsum` schema switch for Torch 1.14 nightly

- core/partitioning/partitioning.cpp
- core/partitioning/segmentedblock/SegmentedBlock.h
- docsrc/contributors/partitioning.rst
- tests/core/partitioning/test_conditionals.cpp
- tests/core/partitioning/test_resolve_nontensor_inputs.cpp
- tests/core/partitioning/test_segmentation.cpp
Adds a heuristic to torch-trt partitioning's segmentation to avoid materializing segments until we hit a dependency of that segment. This can significantly reduce the number of segments/engines in cases where the linear traversal of torchscipt nodes would otherwise produce alternating torch and TRT segments which are not dependent on each-other
Fixes # ([issue](https://github.com/pytorch/TensorRT/issues/1266))
> [feat] Add dependency awareness to torch-trt partitioning

- notebooks/Resnet50-example.ipynb
Minor changes in documentation. 
- [NA] My code follows the style guidelines of this project (You can use the linters)
- [NA] I have performed a self-review of my own code
- [NA] I have commented my code, particularly in hard-to-understand areas and hacks
- [NA] I have added tests to verify my fix or my feature
- [NA] New and existing unit tests pass locally with my changes
- [NA] I have added the relevant labels to my PR in so that relevant reviewers are notified
> docs: minor changes in Resnet50 example

- core/conversion/converters/impl/select.cpp
- tests/core/conversion/converters/test_select.cpp
Fix a bug in `aten::masked_fill.Scalar(Tensor self, Tensor mask, Scalar value) -> (Tensor)` where differing types in `self` and `value` cause an error at model compilation time. Improved type handling and inheritance behavior, and add regression tests to catch the bug.
- Ensure `value` input inherits type from `self`, avoiding a bug where mismatched types cause TRT `Select` to throw an error
- Test type-mismatched inputs (regression tests) to ensure type-casting is handled correctly
- [ x ] My code follows the style guidelines of this project (You can use the …
> fix: Ensure proper type inheritance in `aten::masked_fill`

- noxfile.py
> chore: Nox file update from NGC 22.11 release

- core/conversion/converters/impl/einsum.cpp
- TRT einsum implementation currently supports 2 tensor inputs, however the converter will accept any number of tensor arguments (it accepts a list of tensors) and TRT throws an error at compilation
- `aten::einsum` converter now checks that the tensor argument list does not exceed 2 elements, and throws an informative error otherwise
- [ x ] New and existing unit tests pass locally with my …
> fix: Add check to ensure einsum converter has no more than 2 tensor inputs

- core/conversion/converters/impl/normalize.cpp
- tests/core/conversion/converters/test_normalize.cpp
Adds partial converter support for aten::linalg_norm. https://pytorch.org/docs/stable/generated/torch.linalg.norm.html. Non-None scalar ord arguments are not yet supported. Note that the string ord variant is a different schema and will fallback to torch.
> [feat] Add partial converter support for aten::linalg_norm

- noxfile.py
- Lint noxfile to avoid CI errors for PRs
- Lint file
> chore: Lint `noxfile.py`

- core/partitioning/shape_analysis.cpp
Resolves a CUDA 710 error Issue arising when compiling BERT models with 3+ inputs. The issue arises due to the role of the third tensor in inference computations. Specifically, as specified in the [BERT model code linked here](https://github.com/huggingface/transformers/blob/15fd39ea0ec4f826deb4cb8f3064004939544d30/src/transformers/models/bert/modeling_bert.py#L812-L835), the third argument, `token_type_ids` is of type `torch.LongTensor`, but can only take indices in $[0,1]$. This means that when values outside of this set are used, the input is invalid.
This becomes problematic when the inputs are, for example, indices in a dictionary or embedding - which seems to be the case here. Specifically, `aten::embedding` is used with Tensors which are the product of `token_type_ids`. The issue …
> fix: CUDA error 710 bugfix

- core/conversion/converters/impl/element_wise.cpp
Use `scalar_to_tensor` as much as possible in `element_wise.cpp` to avoid `scalar.to<float>()` which aggressively casts scalar to float. All tests passed.
Fixes #1447
> scalar_to_tensor avoid scalar.to<float>()

- core/partitioning/partitioning.cpp
- core/partitioning/shape_analysis.cpp
- tests/core/partitioning/BUILD
- tests/core/partitioning/test_type_auto_conversion.cpp
Support int64 <=> int32 type conversion.
Fixes #1382 
> feat: support int64 <=> int32 auto conversion

- core/conversion/conversionctx/BUILD
- core/conversion/conversionctx/ConversionCtx.h
- core/ir/ir.h
- core/lowering/BUILD
- core/lowering/CMakeLists.txt
- core/lowering/lowering.cpp
- core/lowering/lowering.h
- core/lowering/passes/BUILD
- core/lowering/passes/CMakeLists.txt
- core/lowering/passes/device_casting.cpp
- core/lowering/passes/passes.h
- core/runtime/execute_engine.cpp
- cpp/src/compile_spec.cpp
- tests/core/lowering/BUILD
- tests/core/lowering/test_device_casting.cpp
- Investigated issue arising with BART-base model (https://huggingface.co/facebook/bart-base) where certain tensor inputs to TensorRT were on the cpu, despite users explicitly casting all inputs properly
- Traced issue to internally-generated 0D tensors, mask tensors, and operations returning CPU tensors passed between Torch and Torch-TensorRT engines
- Added lowering passes to ensure function edge cases are appropriately dealt with, and added validation check in runtime to avoid models crashing at runtime due to device mismatches
- Fixed device location errors relating to specific `aten` functions and casting
- Added runtime check to ensure all tensor inputs to TorchTRT are …
> fix: Device casting issues with certain `aten` operators

- core/lowering/passes/module_fallback.cpp
- core/lowering/passes/passes.h
- tests/core/lowering/test_module_fallback_passes.cpp
unmangle_cls_name in the NotateModuleForFallback pass assumed all ___torch_mangle_ strings are the same length. In testing we saw parts of the module names getting removed when this assumption was violated.
> [fix] unmangle_cls_name for variable length mangled tags

- core/conversion/converters/converter_util.cpp
- core/conversion/converters/converter_util.h
- core/conversion/converters/impl/element_wise.cpp
- core/conversion/converters/impl/unary.cpp
- tests/core/conversion/converters/test_element_wise.cpp
- `aten::div` with truncation on integer tensor inputs currently throws an error if both inputs are integer type, as the TRT unary operations for absolute value and floor do not apply to Int32 or Bool types
- For absolute value, this is a legitimate bug as `aten::abs` is functional for integer types
- For the floor operation, `aten::floor` does not explicitly support integer inputs, and `torch.floor()` does not work with Int32 inputs by default (on `1.13.0.dev20220921+cu116`). However, `torch.div(..., rounding_mode="trunc")` with integer tensors does return an integer value, and so the corollary Torch-TRT converter should behave similarly
- Modified `aten:abs` converter logic to be a utility (moved file location), as the operator is used in multiple locations
- Added regression test to …
> fix: Error with `aten::div` when using truncation with Int32 tensor inputs

- tools/perf/benchmark.sh
- tools/perf/perf_run.py
Improved performance tooling functionality to allow timing of additional code components and coalescing results for easy exporting
- Add functionality for timing compilation in addition to inference
- Add bash scripting code for concatenating all model result outputs
- Tested manually on Docker container for verification
- [ …
> feat: Add functionality to performance tooling

- core/conversion/converters/impl/element_wise.cpp
- core/conversion/converters/impl/reduce.cpp
- tests/core/conversion/converters/test_reduce.cpp
**Duplicate of PR #1488 targeted at Release 1.3**
Fix compilation issues with Citrinet-1024 arising from type-casting issue in `aten::sum` and layer-naming issue in `aten::div`.
- Enable automatic type-casting in `aten::sum` for bool tensor inputs to agree with Torch casting behavior
- Fix bug in `aten::div` where all internal div layers have the same name
- Add test cases for `aten::sum` type-casting
Without type-casting, the error arises from the following:
```python
DEBUG: [Torch-TensorRT - Debug Build] - ITensor shape: [1, 1, 256]
DEBUG: [Torch-TensorRT - Debug Build] - ITensor type: Bool
DEBUG: [Torch-TensorRT - Debug Build] - InDims 1 1 256
DEBUG: [Torch-TensorRT - Debug Build] - Dim to reduce(original):[-1]
DEBUG: [Torch-TensorRT - Debug Build] - Dim to reduce(converted):[2]
DEBUG: …
```
> fix: Repair Citrinet-1024 compilation issues [Duplicate of PR #1488 for Release 1.3]

- core/conversion/converters/impl/reduce.cpp
- tests/core/conversion/converters/test_reduce.cpp
Propagate aten::sum.dim fix for bool inputs to aten::sum converter https://github.com/pytorch/TensorRT/pull/1488/files
TensorRT sum layers do not support bool tensor inputs. Add support by casting the input to int32.
> Support aten::sum with bool tensor input

- core/conversion/converters/converter_util.cpp
- core/conversion/converters/converter_util.h
- core/conversion/converters/impl/cast.cpp
- tests/core/conversion/converters/test_cast.cpp
Add mechanism to add a prefix to cast layer names. This allows us to avoid name conflict errors in cases where we perform the same cast on a tensor twice either internally in ops or in cases where there is both an int32 cast and a long cast which is automatically truncated to int32.
> [fix]Disambiguate cast layer names

- tools/perf/benchmark.sh
- tools/perf/hub.py
- tools/perf/perf_run.py
- tools/perf/utils.py
- Add fx path in benchmarking code
- Add fx saving tools to `utils` and `hub`
- Add PyTorch model parsing and loading in `perf_run` script
- Manually tested in Docker container
> feat: Add functionality for easily benchmarking fx code on key models

- core/lowering/passes/op_aliasing.cpp
- tests/core/lowering/test_operator_aliasing_pass.cpp
Add a trivial pass to convert aten::multiply to aten::mul https://pytorch.org/docs/stable/generated/torch.multiply.html.
> [feat]Canonicalize aten::multiply to aten::mul

- py/torch_tensorrt/fx/converters/acc_ops_converters.py
- py/torch_tensorrt/fx/test/passes/test_fuse_permute_matmul_trt.py
modified:   py/torch_tensorrt/fx/converters/acc_ops_converters.py
modified:   py/torch_tensorrt/fx/test/passes/test_fuse_permute_matmul_trt.py
This is identical to #1413 , but I will do this for @FelixXidddd
> broadcast the two input shapes for transposed matmul

- py/torch_tensorrt/fx/converters/acc_ops_converters.py
- py/torch_tensorrt/fx/test/passes/test_fuse_permute_matmul_trt.py
Copy of #1466 to bypass CLA issue.
In the current padding layer converter for version > 8.2, there are 3 padding layers: pre_pad + mid_pad + post_pad to do the converter. But please consider this case, we want to pad tensor from (2048, 628, 20) to (2048, 628, 32), the pre_pad and mid_pad can be erased because they are doing the opposite operation and waste time.
And consider that from version 8.2, the start of the slice layer can support negative. So let's use one padding layer to do this.
As described above, we can improve perf significantly.
- Perf improves, so no additional functional unit test is needed.
> make padding layer converter more efficient

- py/torch_tensorrt/fx/converters/acc_ops_converters.py
- BERT model (https://huggingface.co/bert-base-uncased) failing to compile with TorchDynamo/fx2trt due to string references not being equal, whereas their accompanying values are
- Updated check in `acc_ops_gelu` to check for equality by value instead of reference on string keyword arg
- [ x ] I have added the relevant labels to my …
> fix: Change equals-check from reference to value for BERT model not compiling in FX

- README.md
The dependencies section of README doesn't reflect the update of 1.3.0
Ref: https://github.com/pytorch/TensorRT/releases/tag/v1.3.0
> Update README dependencies section for v1.3.0

- core/conversion/converters/impl/select.cpp
- tests/core/conversion/converters/test_select.cpp
- Behavior of Torch-TRT differs from that of Torch in the case where the input tensors to `aten::where` have different rank
- Torch automatically broadcasts tensors to the highest-rank variant whereas the TRT Select layer requires tensors of the same rank and throws an error
- Add dimension checking and unsqueeze operator to ensure broadcasting is enabled
- Add test case to catch error
Resolves Part 1 of solution to Issue #1455 
- [ x ]  I have commented my code, particularly in hard-to-understand areas and hacks
- [ x ] I have added …
> fix: `aten::where` with differing-shape inputs bugfix

- core/lowering/lowering.h
- core/partitioning/partitioninginfo/PartitioningInfo.h
- core/partitioning/shape_analysis.cpp
- cpp/src/compile_spec.cpp
- Augment `aten::to` operator insertion at shape analysis time to insert the target device
- Add functionality to `PartitioningInfo` struct to store device information and produce cuda device string
- Make cuda device string function in `LowerInfo` and `PartitioningInfo` const to avoid altering struct fields
Uses schema
```python
Tensor.to(device : Device,
dtype : int,
non_blocking : bool=False,
copy : bool=False,
memory_format : Optional[int]) -> Tensor
```
Instead of 
```python
Tensor.to(dtype : int,
non_blocking : bool=False,
copy : bool=False,
memory_format : Optional[int]) -> Tensor
```
This switch was made to ensure the device for truncated objects is GPU, regardless of their origin, to avoid adding another lowering pass for this case. Since an `aten::to` operation is already being …
> fix: Automatically send truncated long ints to cuda at shape analysis time

- tools/perf/README.md
- tools/perf/hub.py
- tools/perf/perf_run.py
- tools/perf/utils.py
- Add support for FX in YAML config specification path of `perf_run.py`
- Add support for only specifying one of: a PyTorch or TorchScript model
- Improve input model validation to throw errors earlier
- Remove deprecated option from torchvision model
- Add documentation for FX benchmarking
- [ x ] New and existing unit tests pass locally with …
> feat: Add functionality to FX benchmarking + Improve documentation

- core/conversion/converters/impl/select.cpp
- tests/core/conversion/converters/test_select.cpp
The aten::unbind converter used ITensor() rather than ITensorOrFreeze on the input tensor arg which caused crashes if called on an evaluated tensor.
> [fix] Fix crash when calling unbind on evaluated tensor

- py/torch_tensorrt/fx/test/converters/aten_op/test_flatten_aten.py
- py/torch_tensorrt/fx/test/converters/aten_op/test_reshape_aten.py
Fixed unit test failure. #1528 
> Update test_flatten_aten and test_reshape_aten due to PT2.0 changed tracer behavior for these ops

- py/torch_tensorrt/fx/converters/acc_ops_converters.py
- py/torch_tensorrt/fx/test/converters/acc_op/test_interpolate.py
- Improve argument checking and validation to match PyTorch interpolate arguments
- Ensure `align_corners=None` and `align_corners=False` have the same behavior
When user explicitly specifies `align_corners=False` as an argument, it is interpreted as `True`, since the current check solely checks for the input not being None. The argument check has been updated to check both that the input is not None, but also that it is not False, which is required as per [Torch documentation](https://pytorch.org/docs/stable/generated/torch.nn.functional.interpolate.html).
Fixes #1558 
- [ x ] I have commented my …
> fix: Bugfix for `align_corners=False`- FX interpolate

- core/partitioning/partitioninginfo/PartitioningInfo.h
- core/partitioning/shape_analysis.cpp
- core/util/trt_util.cpp
- cpp/src/compile_spec.cpp
- py/torch_tensorrt/csrc/tensorrt_classes.cpp
- tests/core/partitioning/test_type_auto_conversion.cpp
- Fix compilation error for GPT-2 model arising from Byte-type inputs fed into TensorRT Engine
- Update translation dictionary between Torch and TensorRT types to include `at::kByte`
- Add field to PartitioningInfo specifying whether to cast Int8 inputs to TensorRT Engines to Int, to avoid error arising from Int8 inputs being fed into non-quantized engines
- Add automatic detection of quantized/calibrated models and disable Int8 => Int32 casting in those cases
- Fix bug where LoweringInfo target device was not being updated for Python API
- Allow `castNode` to force creation of a new node and avoid searching for an existing one to convert
- Add test to ensure cast is inserted in the Torch engine preceding a TensorRT engine, when the Byte tensor is an output of the Torch engine
Error …
> fix: Properly cast intermediate Int8 tensors to TensorRT Engines in Fallback

- core/conversion/converters/impl/max.cpp
- tests/core/conversion/converters/test_max.cpp
aten::max/min and aten::argmax/min currently error out with int inputs on the topk layer which only supports activation types. Add a cast to float to support int inputs.
> feat: Support int inputs to aten::max/min and aten::argmax/argmin

- core/conversion/evaluators/aten.cpp
- tests/core/conversion/evaluators/test_aten_evaluators.cpp
- Complete set of required operators for full coverage of HuggingFace T5-base model (https://huggingface.co/t5-base)
- Add evaluator for `full_like` with sufficient generality to double as functional operator for `ones_like` and `zeros_like`, with minor additions
- Add thorough testing to ensure type and shape inheritance for returned tensors agrees with documentation
Documentation of `full_like`: https://pytorch.org/docs/stable/generated/torch.full_like.html
Fixes #1583 
- [ x ] I have made corresponding …
> fix: Add `aten::full_like` evaluator

- core/conversion/converters/impl/expand.cpp
- tests/core/conversion/converters/test_expand.cpp
Adds converter support for aten::meshgrid.
> feat: Add support for aten::meshgrid

- .circleci/config.yml
> chore: Add FX core test

- core/lowering/passes/remove_dropout.cpp
- tests/core/lowering/test_remove_dropout_pass.cpp
- Remove existing dropout removal lowering pass implementation due to bug
- Use adapted Torch JIT dropout removal lowering pass to resolve bug where nested dropouts resulted in invalid graph
- Existing removal process left artifacts in graph which caused an internal assertion error
- Add two regression tests to catch nested dropout bug
Fixes #1587 
- [ x ] New and existing unit tests pass locally …
> fix: Replace `RemoveDropout` lowering pass implementation with modified JIT pass

- docker/Dockerfile
- Resolve issue with cuda file deletion command causing build crash
- Update installations to use Ubuntu 20.04
- Dockerfile Update
> chore: Update Dockerfile to Ubuntu 20.04 + Crash Resolution

- core/lowering/passes/linear_to_addmm.cpp
- tests/core/lowering/test_linear_to_addmm.cpp
- Fix 2 bugs in linear-to-addmm lowering pass:
- Lowering pass did not explore nested sub-blocks of a node, of the sort contained in `prim::If` when `bias=None`. As an example, these would be ignored:
```python
%4 : Tensor = prim::If(%true)
block0():
%res = aten::linear(%input, %weight, %biasNone)
-> (%res)
block1():
%res = aten::linear(%input, %weight, %biasNone)
-> (%res)
```
- Lowering pass did not insert fused linear code inside sub-blocks of `prim::If` even when the original function call occurred within such a block. As an example, the following translates to the subsequent graph, which contains an invalid computation:
```python
%4 : Tensor = prim::If(%true)
block0():
%res = aten::linear(%input, %weight, %bias)
-> (%res)
block1():
%res = aten::linear(%input, %invalid_weight, %bias) …
```
> fix: Bugfix in Linear-to-AddMM Fusion Lowering Pass

- core/runtime/TRTEngine.cpp
The IO Tensors and Bindings within the TensorRT `ICudaEngine` object are not necessarily stored in index-order, or in the order they are stored in PyTorch. Thus, one of the checks in the `TRTEngine` which extracts the TRT binding name and compares it to the Torch binding name is unnecessary/incorrect and can be improved.
As an example, consider an engine with two inputs: `{“input_0”, “input_1”}` and two outputs `{“output_0”, “output_1”}`. The Torch binding names (`c10::NameList`) stores these as:
```cpp
[“input_0”, “input_1”, “output_0”, “output_1”]
```
The TRT Engine binding buffer stores these names as:
```cpp
[“input_0”, “input_1”, “output_1”, “output_0”]
```
Thus, when we use direct indexing to access the binding names, an error is encountered, despite the fact that the overall set of …
> fix: Bugfix in TRT Engine deserialization indexing

- core/lowering/passes/reduce_to.cpp
- tests/core/lowering/test_reduce_to_pass.cpp
When there is a aten::to operation in the model as: 
```
sizes = sizes.to(device=boxes.device)
```
like what happens here: https://github.com/facebookresearch/detectron2/blob/58e472e076a5d861fdcf773d9254a3664e045bf8/detectron2/modeling/poolers.py#L65, What this operation does is setting the device for sizes variable, since all the other parameters for aten::to op is not explicitly set, this results in an aten::to op in graph as:
```
%sizes0.2 : Tensor = aten::to(%1954, %80, %80, %1955, %80, %6, %6, %80)
```
where:
```
%80 : NoneType = prim::Constant()
```
The NoneType is valid for aten::to candidate form:
```
aten::to.dtype_layout(Tensor(a) self, *, ScalarType? dtype=None, Layout? layout=None, Device? device=None, bool? pin_memory=None, bool non_blocking=False, bool copy=False, …
```
> fix: fix the inappropriate lowering pass of aten::to

- core/lowering/lowering.cpp
- core/lowering/passes/BUILD
- core/lowering/passes/CMakeLists.txt
- core/lowering/passes/passes.h
- core/lowering/passes/replace_aten_pad.cpp
- tests/core/lowering/BUILD
- tests/core/lowering/test_replace_aten_pad_pass.cpp
Lowering aten::pad to aten::constant_pad_nd/aten::reflection_padXd/aten::replication_padXd
Fixes #1566 
> Lowering aten::pad to aten::constant_pad_nd/aten::reflection_padXd/aten::replication_padXd

- core/conversion/converters/converter_util.cpp
- tests/core/conversion/converters/test_add_sub_mul.cpp
Duplicate layer names in TRT cause an error. Cast layers by default are named based on the Tensor pointer initial type and target type. This could cause name conflicts with multiple element-wise operations that performed the same type promotion on a given tensor. To resolve this, add the element_wise layer name to the type-promotion cast layer as a prefix.
- Breaking change (fix or feature that would cause existing …
> [fix] Disambiguate element-wise cast layer names

- core/conversion/converters/impl/batch_norm.cpp
- tests/core/conversion/converters/test_batch_norm.cpp
Use float types for compile-time calculations around batch_norm. Improves fp16 accuracy relative to pytorch. Fixes # (issue)
> Improve batch_norm fp16 accuracy

- .circleci/config.yml
- examples/fx/lower_example_aten.py
- py/setup.py
- py/torch_tensorrt/fx/passes/lower_basic_pass_aten.py
add an example of aten2trt, fix batch norm pass
torchdynamo has issues in running pytest. 
```
E       AssertionError: whole graph export entails exactly one call
```
> add an example of aten2trt, fix batch norm pass

- core/partitioning/partitioning.cpp
- core/partitioning/segmentedblock/SegmentedBlock.h
- tests/core/partitioning/test_resolve_nontensor_inputs.cpp
- <s>In certain TensorRT-executed blocks, multiple non-Tensor inputs originate from the same parent Tensor in another Torch block, so a single pass of resolveTRTNonTensorInputs does not resolve all non-Tensor inputs, causing failures at compile-time</s>
- Issue was determined to trace to the use of `prim::Loop` in the TensorRT block and is fixed in PR #1691 
- Add function to `SegmentedBlock` to get the ID of a block, so re-inserted blocks retain the same ID as the previous block being replaced
- Add regression test case to elicit behavior
```python
DEBUG: [Torch-TensorRT - Debug Build] - Finalizing in progress TensorRT block
DEBUG: [Torch-TensorRT - Debug Build] - Segment Block @2:
Target: TensorRT
Graph: graph(%1 : int,
%9 : int[],
%12 : Tensor):
```
```python
GRAPH: [Torch-TensorRT - …
```
> fix: Issue in non-Tensor Input Resolution

- docsrc/tutorials/use_from_pytorch.rst
Corrected a typo in the Using Torch-TensorRT Directly From PyTorch tutorial which was causing an error
Fixes #1688
> Corrected a typo, which was raising an error

- cpp/src/compile_spec.cpp
- py/torch_tensorrt/ts/_compile_spec.py
- Improve error messaging for input signature arguments by verifying the nesting depth of the object is within the bounds specified in the TorchScript compiler
- Throw user-error more quickly to avoid less-interpretable error messages later on
Relevant GraphInputs code:
https://github.com/pytorch/TensorRT/blob/5fa63743fc4448e38b1e6b01e7403c0d74717158/core/ir/GraphInputs.cpp#L42-L54
Fixes #1595 
- Improved input handling + error messaging
- [ x ] …
> fix: Improve input handling for `input_signature`

- core/conversion/converters/impl/unsqueeze.cpp
- tests/core/conversion/converters/test_unsqueeze.cpp
The PR consists of the following changes-
1.	Change the use_zeroes parameter to false in shuffle_layer->setReshapeDimensions(), else it is resulting in empty tensor
2.	Test test_unsqueeze.cpp - to test the above changes
In the case of dynamic inputs eg: [1,-1], the util::unsqueezeDims() was changing the dimension [1,1,0] when value 1 was to be inserted at index 1. In shuffle_layer->setReshapeDimensions(), the 0 in the third dimension causes it to get the dimension from input tensor which has length 0 in that dimension. The use_zeroes parameter is set to false so that [1,-1] is reshaped to [1,1,-1] instead.
Fix for issue [1596](https://github.com/pytorch/TensorRT/issues/1596).
- Bug fix (non-breaking change which fixes an …
> Unsqueeze operator with dynamic inout

- core/conversion/converters/impl/select.cpp
- tests/core/conversion/converters/test_select.cpp
Adds a converter for aten::index_select  https://pytorch.org/docs/stable/generated/torch.index_select.html
> [feat] Add converter support for index_select

- core/conversion/converters/impl/unary.cpp
- tests/core/conversion/converters/test_unary.cpp
Adds converter support for aten::logical_not.
> [feat] Add converter support for aten::logical_not

- core/lowering/passes/convNd_to_convolution.cpp
- tests/core/lowering/test_conv1d_pass.cpp
- tests/core/partitioning/test_conditionals.cpp
- Lowering pass did not respect `prim::If` block boundaries
- Refactor convNd implementation to use more precise guard-insert paradigm instead of subgraph rewriting
- Write general function to apply for all convolution replacements
- When replacing a subgraph that occurs within an "If" block, the rewriter places the actual logic of the code outside of the block, so the rewrite makes the code execute both the "if" and the "else" path regardless of what the condition is
- Add regression test case to validate refactoring on `aten::conv1d`
Addresses first bug in #1597 
- [ x ] I have commented my code, …
> fix: Bugfix in convNd_to_convolution lowering pass

- core/conversion/converters/impl/reduce.cpp
- tests/core/conversion/converters/test_reduce.cpp
Adds converter support for aten::any.dim. https://pytorch.org/docs/stable/generated/torch.any.html
> [feat] Add converter for aten::any.dim

- core/conversion/converters/impl/select.cpp
- tests/core/conversion/converters/test_select.cpp
For a single index tensor the aten::index converter previously assumed that this always indexed the batch dimension. Use the adv_idx_indices to find the dimension it actually indexes instead.
> [fix] resolve issue for single non-batch index tensor in aten::index

- core/lowering/passes/replace_aten_pad.cpp
- tests/core/lowering/test_replace_aten_pad_pass.cpp
> fix: Handle nonetype pad value for Constant pad 

- .circleci/config.yml
- py/setup.py
- py/torch_tensorrt/fx/test/quant/test_quant_trt.py
- py/torch_tensorrt/fx/tracer/dispatch_tracer/aten_tracer.py
- Add testing for Torch 1.13.1 path in CI across both TS and FX compilation paths
- Disable `aten` tests for 1.13, to resolve Torch Dynamo import/functionality issues
- Add parameter fields to CI to accomodate Torch 1.13.1 version
- Update `dispatch_tracer` function docstrings and imports to avoid naming issue with `torch._dynamo` vs `torchdynamo`
<s>See [this CI run](https://app.circleci.com/pipelines/github/pytorch/TensorRT/2169/workflows/2563cdac-4795-4b97-9bf1-8aec0251e9e7) for a sample of the 1.13.1 run results. Currently the only failing tests are `test_conv_add_standalone_module` from the FX quantization path, and these failures may arise from API usage changes between 1.13 and 2.0.</s>
The CI is now passing with the updates to the FX quantization path. See [this CI …
> infra: Add Torch 1.13.1 testing to nightly CI

- core/compiler.cpp
- core/lowering/lowering.cpp
- core/partitioning/partitioning.cpp
- core/partitioning/partitioning.h
- tests/py/api/test_e2e_behavior.py
- tests/py/api/utils.py
- Update graph-building in compiler to account for case where all operations are supported by Torch-TRT, but the output is a collection
- Enable 'psuedo-partitioning' for nearly-fully-compiled models for which the only non-supported aspect of the model is the format of the output (TRT cannot output complex collections)
- Define a small subset of operation schemas which are allowed despite the flag `require_full_compilation`. These operations are packing and unpacking of Tuples/Lists, and some are already used in cases of `require_full_compilation`
- Display warnings to users if any portion of the `pseudo-partitioning` is unexpected, for example the model being partitioned ends up in more than 3 segments (maximally - a Torch segment to preprocess collection inputs, a TRT segment to perform …
> fix: Allow full model compilation with collection outputs

- py/torch_tensorrt/fx/tracer/dispatch_tracer/aten_tracer.py
Minor fix - update defaults to `"2.dev"`
> minor fix: Update default minimum torch version for aten tracer

- core/plugins/CMakeLists.txt
- core/runtime/CMakeLists.txt
- core/runtime/TRTEngine.h
- core/runtime/TRTEngineProfiler.cpp
Initial PR for #1563. Fixes Windows CMAKE build.
Finally had time to come back to this - build on a fresh Windows11 machine, all steps to setup/reproduce included.
The change to `core/plugins/CMakeLists.txt` seems like it should be unrelated to this. I was unable to build because 'cudnn.h' was required, but the include path was not being passed to the compiler as the `cuDNN` module wasn't specified. This might not be a problem in other targets because commonly the cudnn files are just installed in to the cuda include/lib/bin dirs.
Also note - windows is generally case insensitive. The normal output dir is `build/` but that doesn't work on Windows as there is a `BUILD` file. So I'm using `out/` as the output. But that isn't in the `.gitignore`, and I haven't included a change for that in …
> Get windows build working

- core/partitioning/partitioning.cpp
- core/partitioning/partitioning.h
- core/partitioning/shape_analysis.cpp
- Shape analysis code in partitioning defaults dry-run tensors to cuda:0 despite user-specified devices
- This leads to errors about device casting for internal tensors, which users cannot cast
- Add GPU-ID function arguments in functions to generate new tensors on the user-specified (or default) device
Fixes #1764 
- Verified locally [requires multi-GPU to test]
- [ x ] New and existing unit …
> fix: Bugfix in shape analysis for multi-GPU systems

- docker/Dockerfile
- docker/README.md
- docker/WORKSPACE.docker
- py/requirements.txt
- Build issue encountered in Docker arising from mismatched versions in WORKSPACE and Docker folder
- Update Dockerfile build process to adapt Torch version from `requirements.txt`
- Remove references to Torch version in Docker `WORKSPACE` file; instead use local Torch version
- [ x ] I have added the relevant labels to my PR in so …
> fix: Update Docker build to automatically adapt Torch version

- README.md
- WORKSPACE
- py/requirements.txt
- toolchains/ci_workspaces/WORKSPACE.x86_64.release.rhel
- toolchains/ci_workspaces/WORKSPACE.x86_64.release.ubuntu
- Update Torch versions to `2.1.0.dev` in alignment with current FX requirements
- Update README documentation to include latest release install
- Version + documentation updates
- CI
> chore: Update Torch and Torch-TRT versions and docs on `main`

- core/lowering/passes/remove_unnecessary_casts.cpp
- tests/core/lowering/test_remove_unnecessary_casts.cpp
- When `remove_unnecessary_casts` replaces both tensors in an `aten::div` call with the corresponding scalars, and the rounding mode (third argument) is specified, the schema becomes invalid
- To avoid this, we intercept the call and split the result based on what the third argument in the input was, either delegating the result to `aten::Int(aten::div(...))`, for "trunc" or `aten::floordiv(...)` for "floor"
- Update lowering pass to incorporate the above change, with appropriate documentation
- Add testing to verify catching and correctly handling these edge cases
Fixes #1780 
- [ x ] I …
> fix: Repair invalid schema arising from lowering pass

- README.md
- core/compiler.cpp
- core/conversion/conversion.cpp
- core/conversion/conversion.h
- cpp/src/compile_spec.cpp
- docsrc/getting_started/getting_started_with_python_api.rst
- py/torch_tensorrt/ts/_compile_spec.py
- tests/cpp/test_collections.cpp
- tests/py/api/test_collections.py
- Allow users to specify full model compilation when using `input_signature`, which allows for complex collection-based inputs
- Enable "psuedo-partitioning" phase for input collections as well as output collections
- Update `OutputIsCollection` to include dictionary outputs, and add function `InputIsCollection` to detect collection-based inputs during graph compilation
- Remove automatic fallback for collection pack/unpack operations when using `input_signature` argument
- Add collections tests to ensure full compilation is respected for input and output collections
Fixes #1602 
Fixes #1293 
Addresses #1595 
- Bug fix
- New feature
- [ x ] I have …
> fix: Allow full model compilation with collection inputs (`input_signature`)

- core/conversion/converters/impl/matrix_multiply.cpp
- tests/core/conversion/converters/test_matrix_multiply.cpp
Adds a converter for aten::baddbmm https://pytorch.org/docs/stable/generated/torch.baddbmm.html
> feat: add support for aten::baddbmm

- core/conversion/evaluators/aten.cpp
- core/conversion/var/Var.cpp
- tests/cpp/test_dynamic_size.cpp
Adds dynamic conversion path to support aten::mul on the output of dynamic aten::size.
> [feat] Add dynamic conversion path to aten::mul evaluator

- core/conversion/converters/impl/stack.cpp
- tests/core/conversion/converters/test_stack.cpp
Resolves error preventing aten::stack from converting correctly with dynamic shapes. Unsqueezed dims used 0 for dynamic dimension which was not aligned correctly with the dynamic dim in the input, switch to using -1.
> [fix] aten::stack with dynamic inputs

- core/conversion/evaluators/eval_util.cpp
- core/ir/ir.cpp
Some undefined attribute error was observed. 
This is because `attr::value` refers to some other symbol value in some context, which makes the node cannot find the corresponding attribute key. 
Fixes #1752 , #1755
> fix undefined attr issue

- core/util/trt_util.cpp
- Implement support for negative-indexing in unsqueeze, in accordance with the `torch.unsqueeze` function
- Fix bug for TFT model in PyTorch, which requires negative indexing in unsqueeze
- Update core utility logic and comments
Desired Behavior:
```python
torch.unsqueeze(torch.ones(4, 4), -1).shape
>>> (4, 4, 1)
torch.unsqueeze(torch.ones(4, 4), -3).shape
>>> (1, 4, 4)
```
Fixes #1779
- [ x ] …
> fix: Out-Of-Bounds bug in Unsqueeze

- docker/Dockerfile
- docker/README.md
- docker/WORKSPACE.docker
- docker/WORKSPACE.ngc
- docker/dist-build.sh
- Upgrade Ubuntu version to 22.04
- Make custom build args for TensorRT and CUDNN versions, user-specifiable in a.b.c version format
- Make build args required, without defaults, to improve code cleanliness and reduce amount of changes needed when versions shift
- Provide clear error messages when the build args are not provided by the user
- Add documentation of the change in the Docker README
Fixes #1782 
- [ x ] I have made corresponding …
> feat: Upgrade Docker build to use custom TRT + CUDNN

- core/partitioning/shape_analysis.cpp
> fix: include str ivalue type conversion

- core/lowering/lowering.cpp
- tests/core/lowering/BUILD
- tests/core/lowering/test_autocast_long_inputs.cpp
AutocastLongInputs previously inserted cast nodes before the constant nodes used as inputs to the cast.
> fix: dependency order of inserted long input casts

- core/conversion/converters/impl/reduce.cpp
- tests/core/conversion/converters/test_reduce.cpp
Adds a converter to support aten::all.dim
> feat: Add ts converter support for aten::all.dim

- py/torch_tensorrt/fx/passes/lower_basic_pass_aten.py
- Remove references for PyTorch 2.0 stable
- CI-Tested
> fix: Remove references to `_native_batch_norm_legit_no_training` for PyTorch 2.0 Stable

- core/runtime/TRTEngine.cpp
- Fix `to_str()` method using invalid binding names for TRT Engines
- Method was using standard I/O names of the form `input_*`, `output_*`, which does not represent the full range of potential names
- Update implementation to access binding names directly from binding names array
- Update debug message printing to improve readability + clarity + provided information
Fixes #1844 
- [ x ] New and …
> fix: Error caused by invalid binding name in `TRTEngine.to_str()` method

- py/torch_tensorrt/fx/converters/aten_ops_converters.py
- py/torch_tensorrt/fx/test/converters/aten_op/test_mean_aten.py
- Replace existing implementation of aten.mean.dim with general version invoking centralized `add_reduce_layer` utility
- Add implementation of aten.mean.default by refactoring default case to be a special invocation of aten.mean.dim (specifically, one with `dim` being all dimensions in the Tensor and `keepdim` being False).
- Add defaults for optional arguments in converters
- Add test cases for combinations of input options to the converters
Fixes #1742 
Addresses First Bug in #1740
- [ x ] I have made …
> fix: Implement `aten.mean.default` and `aten.mean.dim` converters

- core/conversion/converters/impl/unary.cpp
- tests/core/conversion/converters/test_unary.cpp
Adds converter support for aten::log2. Uses the same method as onnx: https://github.com/pytorch/pytorch/blob/main/torch/onnx/symbolic_opset9.py#L5279
> feat: Add converter for aten::log2

- core/conversion/converters/impl/element_wise.cpp
- tests/core/conversion/converters/test_comparators.cpp
Adds converter support for aten::logical_and
https://pytorch.org/docs/stable/generated/torch.logical_and.html
> feat: Add converter support for logical_and

- .circleci/config.yml
- README.md
- WORKSPACE
- docker/Dockerfile
- docker/README.md
- docker/WORKSPACE.docker
- docker/WORKSPACE.ngc
- docker/dist-build.sh
- py/requirements.txt
- py/setup.py
- py/torch_tensorrt/fx/README.md
- py/torch_tensorrt/fx/test/passes/test_fuse_permute_linear_trt.py
- py/versions.py
- pyproject.toml
- toolchains/ci_workspaces/WORKSPACE.x86_64.release.rhel
- toolchains/ci_workspaces/WORKSPACE.x86_64.release.ubuntu
- Add support for `--legacy` flag in `setup.py`, to enable installation with PyTorch 1.13.1
- Add in test cases previously disabled due to dependency issues
- Improve documentation of `README`s across repository
- Update cudnn version to 8.8, update TRT version to 8.6 across all files and `README`s
- Update `docker` folder on release branch to use new build system with custom TRT, cudnn, CUDA, and Python versions
- Update `WORKSPACE` files to use Torch 2.0.1 Release Candidate
Stacked with PR #1759
- Functionality + Testing Additions
- Version Upgrades
- [ x ] I have commented my code, particularly …
> fix: Upgrade to PyTorch 2.0.1 Release Candidate + Other improvements

- py/torch_tensorrt/__init__.py
- Ensure `torch._dynamo` can be imported by validating Torch version
- Intended to fix legacy CI run
> fix: Add version checking for `torch._dynamo` import in `__init__`

- README.md
- docker/Dockerfile
- docker/README.md
- docker/dist-build.sh
- Add improved Docker build robustness by automatically correcting the attached `cuda` directory
- Allow specification of TensorRT and cuDNN versions as a.b (requiring only two values instead of three)
- Validate inputs and perform symlinks more cleanly
- Improve wildcard-matching system for apt versions on key nvinfer libraries
- Update README documentation
- Improve Docker build system
- [ x ] …
> fix: Improve Docker build robustness, add validation

- py/torch_tensorrt/fx/converters/acc_ops_converters.py
- In line with recent deprecation of the `kEXPLICIT_PRECISION` flag in TRT
- Add improved logic for weight handling in `conv` layers to bring all accelerated conv layers into agreement and fix errors in the Dynamo path arising from `TRTTensor` inputs
- Fix minor typos in error messages
Fixes #1885
- [ x ] I have added the relevant …
> fix: Improve input weight handling to `acc_ops` convolution layers in FX

- core/conversion/conversionctx/ConversionCtx.h
- core/conversion/evaluators/aten.cpp
- core/conversion/evaluators/eval_util.cpp
- cpp/bin/torchtrtc/main.cpp
- cpp/include/torch_tensorrt/torch_tensorrt.h
- cpp/src/compile_spec.cpp
- py/torch_tensorrt/csrc/register_tensorrt_classes.cpp
- py/torch_tensorrt/csrc/tensorrt_classes.cpp
- py/torch_tensorrt/csrc/tensorrt_classes.h
- py/torch_tensorrt/csrc/torch_tensorrt_py.cpp
- py/torch_tensorrt/ts/_compile_spec.py
- py/torch_tensorrt/ts/_compiler.py
- tests/cpp/test_dynamic_size.cpp
- tests/util/run_graph_engine.cpp
- tests/util/util.h
This PR does the following
1) The aten::size dynamic shape handling is now disabled by default. `allow_shape_tensors=True` will enable it.
2) Modifications to aten::size include preserving the static dimensions in the input, thereby not converting any known types eg: `Int` into `ITensors`
> feat: Wrap dynamic size handling in a compilation flag

- .circleci/config.yml
- Addresses nightly legacy CI failure
- CI Testing
> fix: Add torchvision legacy CI parameter

- py/torch_tensorrt/fx/converters/acc_ops_converters.py
See #1886 for details
- PR Cherry-Pick
- CI verification
> fix: Cherry-pick `acc` convolution fix to `release/1.4`

- py/torch_tensorrt/fx/converters/acc_ops_converters.py
- py/torch_tensorrt/fx/diagnostics.py
- py/torch_tensorrt/fx/fx2trt.py
- py/torch_tensorrt/fx/input_tensor_spec.py
- py/torch_tensorrt/fx/lower.py
- py/torch_tensorrt/fx/passes/lower_basic_pass.py
- py/torch_tensorrt/fx/passes/lower_pass_manager_builder.py
- py/torch_tensorrt/fx/passes/pass_utils.py
- py/torch_tensorrt/fx/test/converters/aten_op/test_cat_aten.py
- py/torch_tensorrt/fx/test/converters/vanilla/test_convolution_vanilla.py
- py/torch_tensorrt/fx/test/core/test_input_tensor_spec.py
- py/torch_tensorrt/fx/test/passes/test_fuse_permute_linear_trt.py
- py/torch_tensorrt/fx/test/passes/test_pass_utils.py
- py/torch_tensorrt/fx/test/passes/test_setitem_trt.py
- py/torch_tensorrt/fx/test/tracer/test_acc_tracer.py
- py/torch_tensorrt/fx/test/tracer/test_dispatch_tracer.py
- py/torch_tensorrt/fx/test/trt_lower/trt_splitter_test.py
- py/torch_tensorrt/fx/tools/common_fx2trt.py
- py/torch_tensorrt/fx/tools/model_packager.py
- py/torch_tensorrt/fx/tools/trt_splitter.py
- py/torch_tensorrt/fx/tracer/acc_tracer/acc_normalizer.py
- py/torch_tensorrt/fx/tracer/acc_tracer/acc_ops.py
- py/torch_tensorrt/fx/tracer/acc_tracer/acc_tracer.py
- py/torch_tensorrt/fx/tracer/acc_tracer/acc_utils.py
- py/torch_tensorrt/fx/tracer/dispatch_tracer/aten_tracer.py
- py/torch_tensorrt/fx/utils.py
> Sync fb internal change to OSS

- py/torch_tensorrt/dynamo/backend/__init__.py
- py/torch_tensorrt/dynamo/backend/_defaults.py
- py/torch_tensorrt/dynamo/backend/_settings.py
- py/torch_tensorrt/dynamo/backend/backends.py
- py/torch_tensorrt/dynamo/backend/lowering/_decompositions.py
- py/torch_tensorrt/dynamo/backend/lowering/_partition.py
- py/torch_tensorrt/dynamo/backend/test/test_lowering.py
- py/torch_tensorrt/dynamo/backend/test/test_partitioning.py
- py/torch_tensorrt/dynamo/backend/test/utils.py
- py/torch_tensorrt/dynamo/test/test_dynamo_backend.py
- Improve torch.compile Dynamo partitioning system by incorporating key arguments including `min_block_size` and `torch_executed_ops`, which are available for use in TorchScript
- Improve torch.compile lowering system by adding key new decompositions to improve coverage and reduce the number of unique operators requiring implementation
- Update testing framework to use utilities, reducing code replication
- Add extensive testing of new partitioning system and lowering phases
**Note:** Not to be merged prior to `release/1.4` branch finalization (features are experimental and evolving)
Fixes #1832 
- …
> fix: Improve partitioning + lowering systems in `torch.compile` path

- .circleci/config.yml
- README.md
- WORKSPACE
- py/requirements.txt
- py/torch_tensorrt/fx/README.md
- Upgrade FX CI testing by splitting tests using CI utilities + pytest
- Upgrade stack to use TensorRT 8.6.1
- Stack Upgrade
- CI Upgrade
> fix: Upgrade TRT to 8.6.1, parallelize FX tests in CI

- .circleci/config.yml
- README.md
- WORKSPACE
- docker/Dockerfile
- docker/README.md
- docker/dist-build.sh
- py/requirements.txt
- py/torch_tensorrt/fx/README.md
- py/versions.py
- toolchains/ci_workspaces/WORKSPACE.x86_64.release.rhel
- toolchains/ci_workspaces/WORKSPACE.x86_64.release.ubuntu
- Upgrade to Torch 2.0.1 and TensorRT 8.6.1, latest stable versions
- Update documentation accordingly, as well as `WORKSPACE` files and builds
- Cherry-pick Docker fixes into release branch
Fixes #1895
- Dependency version upgrades
- CI testing
> fix: Upgrade `release/1.4` to Torch 2.0.1 + TensorRT 8.6.1

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/new-story.md
- Create template for proposing new stories, which include multiple issues/features/PRs all related under a key central theme
- Fix numbering in bug report template
- Add default "Story" label
> feat: Add issue template for Story

- core/conversion/converters/converter_util.h
- core/conversion/converters/impl/concat.cpp
- tests/core/conversion/converters/test_concat.cpp
Add support for pytorch style type promotion within the aten::cat converter. Resolves issues with "unsupported type" errors from aten::cat(Int, Float) which is supported by pytorch.
> feat: support type promotion in aten::cat converter

- py/torch_tensorrt/fx/converters/acc_ops_converters.py
- py/torch_tensorrt/fx/converters/activation.py
- py/torch_tensorrt/fx/converters/aten_ops_converters.py
- py/torch_tensorrt/fx/converters/converter_utils.py
- py/torch_tensorrt/fx/converters/impl/activation.py
- py/torch_tensorrt/fx/converters/nn_ops_converters.py
Proposes reorganization of the converters to separate IR from implementation.
Introduces `SourceIR` enum to inform downstream tasks of any necessary special cases.
~~Note: This PR cannot be merged without child PRs updating uses of `common_activation` and `add_activation` to use the new method.~~
- Refactor
> Reorg for converters in (FX Converter Refactor [1/N])

- py/torch_tensorrt/fx/converters/aten_ops_converters.py
- py/torch_tensorrt/fx/test/converters/aten_op/test_cat_aten.py
- Add default `dim=0` to concatenation operator for use cases which do not have a specific concatenation dimension specified
- T5 encounters this error during compilation
- Add test cases to elicit error with default dimension
Fixes #1862
Addresses #1740 
- [ x ] I have added the relevant labels to my PR in so that relevant …
> fix: Add support for default dimension in `aten.cat`

- third_party/cuda/BUILD
Fixed the following error when building on CUDA12: 
external/cuda/include/cuda_fp16.hpp:65:10: fatal error: nv/target: No such file or directory
65 | #include <nv/target>
> Relaxing glob pattern for CUDA12

- py/torch_tensorrt/dynamo/backend/__init__.py
- py/torch_tensorrt/dynamo/backend/backends.py
- py/torch_tensorrt/dynamo/backend/conversion.py
- py/torch_tensorrt/dynamo/backend/lowering/_partition.py
- Add `fake_tensor_unsupported` decorator to helper backend
- Refactor `conversion` implementation to use compilation settings object as well, to reduce code duplication and encourage reuse
- Improve debugger messages by pre-formatting support string
- [ x ] I have added the relevant labels to my PR in so that relevant reviewers are …
> fix: Address `.numpy()` issue on fake tensors

- core/conversion/converters/impl/element_wise.cpp
- tests/core/conversion/converters/test_div.cpp
PyTorch automatically casts int/int division to float. Torch-TensorRT previously output an integer which created parity issues.
> fix: int/int=float division

- core/conversion/converters/impl/stack.cpp
- tests/core/conversion/converters/test_stack.cpp
Handle negative dims arg in aten::stack for values < -1. 
> fix: Support dims < -1 in aten::stack converter

- core/partitioning/partitioning.cpp
- tests/core/partitioning/test_shape_analysis.cpp
isInputDynamic previously returned false if any inputs had static shapes. This forced static shape propagation incorrectly when not all input shapes were dynamic.
> fix: Resolve issue in isInputDynamic with mixed static/dynamic shapes

- docker/WORKSPACE.ngc
- noxfile.py
The following files are modified-
1. _docker/WORKSPACE.ngc_ changing the python lib files to python 3.10. Hardcoded at present
2. _noxfile.py_ changing the PYT_PATH to python3.10
> DLFW changes

- core/conversion/converters/impl/unary.cpp
- tests/core/conversion/converters/test_unary.cpp
Adds a converter to support `aten::isfinite` https://pytorch.org/docs/stable/generated/torch.isfinite.html.
Implemented as `(x-x)==(x-x)`. Relies on the fact that `x-x = NaN` for `NaN`, `inf` and `-inf` and `NaN != NaN`.
> feat: Add converter for aten::isfinite

- py/torch_tensorrt/fx/converters/aten_ops_converters.py
- py/torch_tensorrt/fx/converters/impl/elementwise/ops.py
- py/torch_tensorrt/fx/test/converters/aten_op/test_rsqrt_aten.py
> Moving elementwise core to impl - rsqrt (FX Converter Refactor [9/N]) <Target: converter_reorg_elementwise>

- py/torch_tensorrt/dynamo/backend/lowering/_decompositions.py
- py/torch_tensorrt/dynamo/backend/test/test_decompositions.py
- py/torch_tensorrt/dynamo/common_utils/test_utils.py
- Decompose addmm operator into mul, matmul, and add ops
- Add test case for addmm decomposition
Fixes #1790
- Improved operator coverage
> fix: Add decomposition for `aten.addmm`

- py/torch_tensorrt/dynamo/fx_ts_compat/fx2trt.py
- py/torch_tensorrt/dynamo/fx_ts_compat/lower.py
- py/torch_tensorrt/dynamo/fx_ts_compat/lower_setting.py
- py/torch_tensorrt/dynamo/fx_ts_compat/passes/pass_utils.py
- Max Stream,
- Version Compatability
- Optimization Level
> Upstream 3 features to fx_ts_compat: MS, VC, Optimization Level

- core/lowering/lowering.cpp
- core/lowering/lowering.h
- core/lowering/passes/passes.h
- core/lowering/passes/remove_unnecessary_casts.cpp
- cpp/src/compile_spec.cpp
- cpp/src/torch_tensorrt.cpp
- py/torch_tensorrt/csrc/tensorrt_classes.cpp
- py/torch_tensorrt/csrc/tensorrt_classes.h
- py/torch_tensorrt/csrc/torch_tensorrt_py.cpp
- tests/core/lowering/test_remove_unnecessary_casts.cpp
- *Adds improved support for full-conversion **and** TRT engine export for a variety of models*
- Automatically remove output repacking for `convert_method_to_trt_engine` calls, to improve parity between models which can be converted directly to TRT engines, and models which can be fully compiled
- Add new internal `CompileSpec` argument for lowering which indicates whether the lowering passes originate from a `convert_method_to_trt_engine` call or a regular `compile` call, which affects whether the lowering pass is applied
- Regular TorchScript graphs cannot have this pass applied, as it can otherwise break the output graph. Newer versions of Torch disallow graph outputs with 0 or 2+ arguments which are not packed in a struct
- Current lowering pass detects outputs which are flat Lists …
> fix: Add lowering pass to remove output repacking in `convert_method_to_trt_engine` calls

- core/conversion/evaluators/aten.cpp
- tests/core/conversion/evaluators/evaluator_test.bzl
- tests/core/conversion/evaluators/test_aten_evaluators.cpp
This PR addresses the issue #1678 
Fixes #1678
-aten::slice schema is fixed since it gets invalid type
-aten::list is included in the evaluators
-PR 1691 is included for fixing prim::Loop fallback issue
> Fixing aten::slice invalid schema and implementing aten::list evaluator

- core/conversion/converters/impl/constant_pad.cpp
Rewrite constant_pad_nd converter to use a single slice layer rather than fill and concat. This is similar to what onnx implements here: https://github.com/onnx/onnx-tensorrt/blob/main/builtin_op_importers.cpp#L3249
Functionality covered by existing tests, shows 5ms perf improvement on internal test.
> fix: Rewrite constant_pad_nd to use a single slice layer for performance

- core/conversion/converters/BUILD
- core/conversion/converters/CMakeLists.txt
- core/conversion/converters/impl/chunk.cpp
- tests/core/conversion/converters/BUILD
- tests/core/conversion/converters/test_chunk.cpp
Adding converrter for aten::chunk
WIP for dynamic shape
Fixes #1801
> Adding converter aten::chunk in torchscript

- core/runtime/TRTEngine.cpp
- TRT Index should be used to access tensor names, as opposed to pytorch index
> fix: Repair index used to access tensor bindings

- tests/py/models/test_models.py
- Update range on BERT module inputs to respect input/embedding indexing restrictions
- Fix failing CI test with BERT on TorchScript path
- CI validation
> fix: Repair input range on BERT inputs for CI

- py/torch_tensorrt/dynamo/test/test_dynamo_backend.py
- Add unittest assertion module to streamline error messaging and reporting
> fix: Refactor assertions in E2E tests for Dynamo

- py/torch_tensorrt/dynamo/backend/__init__.py
- py/torch_tensorrt/dynamo/backend/_defaults.py
- py/torch_tensorrt/dynamo/backend/_settings.py
- py/torch_tensorrt/dynamo/backend/conversion.py
- Redirect import of `TRTInterpreter` and `InputTensorSpec` to source from `torch_tensorrt.dynamo.fx_ts_compat.fx2trt`
- Update necessary defaults, settings, and function schemas to support specialized arguments, including `workspace_size`
- Update docstrings accordingly
- [ x ] I have added the relevant labels to my PR in so that …
> chore/fix: Update `TRTInterpreter` impl in Dynamo compile [1 / x]

- tests/core/conversion/converters/test_topk.cpp
- Update test code to generate a random unique sequence of integers for TopK comparison testing, avoiding index and value collisions in the results which were causing CI test failures
- CI verification
> fix: Repair flaky TopK core test

- py/torch_tensorrt/dynamo/backend/backends.py
- py/torch_tensorrt/dynamo/backend/utils.py
- Add ability to pass `options` dictionary to `kwargs` in `torch_tensorrt_backend`, for compatibility with updated torch compile API
- The `options` dictionary is automatically parsed for specified fields and overwrites those fields in the `settings` object
- [ …
> feat: Add `options` kwargs for Torch compile [3 / x]

- py/torch_tensorrt/dynamo/backend/conversion.py
- py/torch_tensorrt/dynamo/fx_ts_compat/fx2trt.py
- Add argument for specification of output data types of TRT engines in the interpreter, to avoid type mismatches at runtime
- Add support for output data type provision in the Dynamo compile path, which simultaneously tests the feature via the backend testing and e2e frameworks
- [ x ] I have added the relevant labels to my PR in …
> feat: Add support for output data types in `TRTInterpreter` [2 / x]

- .bazelrc
- .circleci/config.yml
- CMakeLists.txt
- README.md
- WORKSPACE
- py/requirements.txt
- py/setup.py
- py/torch_tensorrt/dynamo/backend/backends.py
- py/torch_tensorrt/dynamo/backend/conversion.py
- py/torch_tensorrt/dynamo/backend/utils.py
- py/torch_tensorrt/dynamo/fx_ts_compat/fx2trt.py
- toolchains/ci_workspaces/WORKSPACE.x86_64.release.rhel
- toolchains/ci_workspaces/WORKSPACE.x86_64.release.ubuntu
- Upgrade Torch version across the stack
- Update `setup.py` dependencies
- Switch default required C++ version to C++17, as required for new Torch distributions
- Dependency Version Upgrade
> chore: Upgrade Torch nightly to `2.1.0.dev20230605` [4 / x]

- core/runtime/execute_engine.cpp
- Output binding indices are not guaranteed to be strictly after input binding indices in value
- Instead, we can use the output binding map as the ground truth for the mapping from TRT indices to PyTorch Tensor indices
- This bug is encountered when using `TRTModuleNext` on certain models (see issue below)
Fixes #2053
Addresses Second Bug in #1565 
- [ x ] New and existing unit tests pass …
> fix: Repair output binding indexing scheme in TRT

- py/torch_tensorrt/dynamo/backend/__init__.py
- py/torch_tensorrt/dynamo/backend/backends.py
- Improve kwarg passing through Dynamo frontend
- Improve logging in case of TRT compilation failures
> fix: Improve logging and kwarg passing in Dynamo

- py/torch_tensorrt/dynamo/backend/backends.py
- py/torch_tensorrt/dynamo/backend/test/test_specialized_models.py
- py/torch_tensorrt/dynamo/fx_ts_compat/fx2trt.py
- py/torch_tensorrt/fx/converters/acc_ops_converters.py
- py/torch_tensorrt/fx/converters/aten_ops_converters.py
- py/torch_tensorrt/fx/converters/converter_utils.py
- py/torch_tensorrt/fx/fx2trt.py
- py/torch_tensorrt/fx/trt_module.py
- py/torch_tensorrt/fx/utils.py
- Refactor `to_numpy` function to handle non-tensor inputs, avoiding fake tensor issue during compilation of constants
- Refactor multiple functions to allow for `numpy` data types and shapes, as a workaround for `torch.Tensor` instantiations being fake
- Develop new "unified" data type translation which takes any of `{TRT, Numpy, Torch}` data types and translates them to any other of those
- Add regression test case to elicit behavior
Fixes #1951 
- [ x ] I have made corresponding changes to the …
> fix: Add support for fake tensors

- py/torch_tensorrt/dynamo/backend/__init__.py
- py/torch_tensorrt/dynamo/backend/conversion.py
- py/torch_tensorrt/dynamo/fx_ts_compat/fx2trt.py
- py/torch_tensorrt/dynamo/fx_ts_compat/lower.py
- py/torch_tensorrt/dynamo/fx_ts_compat/lower_setting.py
- Pass-through new TRT args in export
- Fix bug in `fx_ts_compat` where `explicit_batch_dimension` did not exist in input args
- Pass-through build failures arg in compile
> fix: Repair argument passing in both Dynamo paths

- py/torch_tensorrt/dynamo/backend/backends.py
- py/torch_tensorrt/dynamo/backend/lowering/__init__.py
- py/torch_tensorrt/dynamo/backend/lowering/_partition.py
- py/torch_tensorrt/dynamo/backend/lowering/_pre_aot_lowering.py
- py/torch_tensorrt/dynamo/backend/lowering/substitutions/__init__.py
- py/torch_tensorrt/dynamo/backend/lowering/substitutions/einsum.py
- py/torch_tensorrt/dynamo/backend/lowering/substitutions/maxpool1d.py
- py/torch_tensorrt/dynamo/backend/test/test_pre_aot_lowering.py
- py/torch_tensorrt/dynamo/backend/test/utils.py
- Add functionality for advanced exclusion of both function and module-type nodes in Torch-TRT
- Add sample exclusion for `torch.einsum` function which can be accelerated as a single unit via TRT
- Add utilities and improve module and function-level exclusion mechanisms
- Add test cases for new exclusion mechanism
Fixes #1959
- [ x ] New and existing unit tests pass locally with my …
> feat: Add support for general-purpose function acceleration in Dynamo [6 / x]

- py/torch_tensorrt/dynamo/backend/backends.py
- Caused by passing Fake Tensor objects into TRT engines mid-compilation
- Resolved by replacing all FX modules with TRT equivalents after all TRT compilation is complete. This way, modules are not run on FakeTensors generated during compilation
Fixes #2072
- [ x ] I …
> fix: Repair null bindings issue in TRT Engines

- docker/Dockerfile
- Enable `libtorch` sourcing from WORKSPACE file in Docker container
Addresses #1560
- Container improvement
> fix: Add python3 symlink in final container

- py/torch_tensorrt/dynamo/__init__.py
- py/torch_tensorrt/fx/tracer/dispatch_tracer/aten_tracer.py
- Wrap Dynamo import in version check
Fixes #2090
- CI Validation
> fix: Repair import error for legacy TS testing

- py/torch_tensorrt/fx/test/passes/test_fix_reshape_batch_dim.py
- py/torch_tensorrt/fx/test/passes/test_remove_duplicate_output_args.py
- Switches between `num_users` and `#users` based on Torch version
Changed here: https://github.com/pytorch/pytorch/pull/101140
> fix: Repair graph naming for FX legacy suite

- core/lowering/lowering.cpp
- core/lowering/passes/exception_elimination.cpp
- core/lowering/passes/passes.h
- tests/core/lowering/test_exception_elimination_pass.cpp
- Torch-TensorRT has evaluator support for exception elimination and this particular lowering pass causes certain models to halt compilation indefinitely
- Modify this lowering pass to use a safer node-replacement system via direct node input replacement
- Add new `EliminateExceptionsSafe` lowering pass, which has functionally the same task as that of `EliminateExceptions`, but with a safer replacement scheme
- Update EliminateExceptions to use direct node input replacement instead of `replaceAllUsesWith` to avoid issue with invalid IR causing program halting
- Add testing for new lowering pass
The [`torch::jit::EliminateExceptions`](https://github.com/pytorch/pytorch/blob/main/torch/csrc/jit/passes/remove_exceptions.h) lowering pass is listed as "risky" in the documentation, and as per …
> fix: Replace EliminateExceptions lowering pass

- py/torch_tensorrt/dynamo/backend/backends.py
- Propagate original error through to the user instead of masking with `AssertionError`
- Helpful for debugging complex models and converter errors more efficiently
- Logging improvement
> chore: Improve error propagation for torch compile

- py/torch_tensorrt/dynamo/conversion/trt_interpreter.py
- Fixes error causing PyTree failures during Dynamo tracing for new converters returning lists of Tensors
The following error is encountered when testing converters:
```python
Traceback (most recent call last):
File "~/python_virtual_environments/torch_trt_venv/lib/python3.10/site-packages/parameterized/parameterized.py", line 620, in standalone_func
return func(*(a + p.args), **p.kwargs, **kw)
File "~/TensorRT/py/torch_tensorrt/dynamo/converters/test/test_split.py", line 25, in test_split
self.run_test(
File "~/TensorRT/py/torch_tensorrt/dynamo/converters/test_utils.py", line 102, in run_test
super().run_test(
File "~/TensorRT/py/torch_tensorrt/dynamo/fx_ts_compat/tools/common_fx2trt.py", line 84, in run_test
interpreter_result = interpreter.run(lower_precision=precision)
File …
```
> fix: TRTInterpreter output lacks return value

- py/torch_tensorrt/dynamo/__init__.py
- py/torch_tensorrt/dynamo/common_utils/converter_utils.py
- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- py/torch_tensorrt/dynamo/conversion/trt_interpreter.py
- py/torch_tensorrt/dynamo/converter_registry.py
- py/torch_tensorrt/dynamo/lowering/_partition.py
- py/torch_tensorrt/fx/converter_registry.py
- Add Dynamo converter registry which functions as a superset of the standard FX converter registry
- For use with new + experimental converters
- Uses custom decorator `dynamo_tensorrt_converter`
- Update references within Dynamo functions to use the converter registry `DYNAMO_CONVERTERS`
- Add custom class overriding default Dictionary class to access converters from various registries
- Add new dictionary type `Dict[Target, Sequence[ConverterSupport]]` as well as ConverterSupport class which stores a converter and its validation implementation
- Add unified `DYNAMO_CONVERTERS` dictionary which coalesces both the FX and Dynamo converter dictionaries and acts as a single unified dictionary
Fixes #1942 
Fixes #2071 
- New feature …
> fix/feat: Add Dynamo-only converter registry

- .github/workflows/docgen.yml
- packaging/pre_build_script.sh
- toolchains/ci_workspaces/WORKSPACE.x86_64.cu121.release.rhel
> chore: fix the docgen job

- core/conversion/converters/impl/select.cpp
- tests/core/conversion/converters/test_masked_fill.cpp
- tests/core/conversion/converters/test_select.cpp
Adds support for dynamic shape inputs in aten::select and aten::masked_fill converters.
> [feat] TS: Add support for dynamic select and masked_fill

- core/conversion/converters/impl/shuffle.cpp
- tests/core/conversion/converters/test_shuffle.cpp
- tests/cpp/test_dynamic_size.cpp
Added a converter support for aten::unflatten.
Created a separate PR for #1808 
> feat: Added support for aten::unflatten converter

- core/conversion/converters/impl/quantization.cpp
- tests/core/conversion/converters/test_quantization.cpp
Added support for fake_quant_per_tensor variant named aten::fake_quantize_per_tensor_affine.tensor_qparams with scale as a Tensor in the schema.
> feat: Added a variant for aten::fake_quant_per_tensor

- .github/workflows/docker_builder.yml
- docker/Dockerfile
- Add GHA automated job to build Docker container with latest `main` branch for Torch-TensorRT
- Add concurrency control to avoid build clashes
- Add environment variables to reduce code duplication, improve readability, and make the code easier to modify when versions change
- Add new container registry URL to host built containers
See here: https://github.com/pytorch/TensorRT/pkgs/container/tensorrt%2Ftorch_tensorrt_main, for a sample of what the container registry + naming looks like.
**Note:** It seems that previous package versions are stored in ["Untagged"](https://github.com/pytorch/TensorRT/pkgs/container/tensorrt%2Ftorch_tensorrt_main/versions?filters%5Bversion_type%5D=untagged), which is not preferable. Seeking workarounds for this.
> ci: Add automatic GHA job to build + push Docker Container on `main`

- .circleci/config.yml
- Reduce testing time on CircleCI by over 15 mins
- Tests currently are only split by file, not by individual test cases since these are managed by two different commands (CircleCI vs PyTest)
Fixes #2139 
- CI fix
> chore: Add parallelism to Dynamo tests

- core/conversion/converters/impl/expand.cpp
- core/lowering/lowering.cpp
- core/lowering/passes/BUILD
- core/lowering/passes/CMakeLists.txt
- core/lowering/passes/passes.h
- core/lowering/passes/tile_to_repeat.cpp
- docsrc/contributors/lowering.rst
- tests/core/conversion/converters/test_expand.cpp
- tests/core/lowering/BUILD
- tests/core/lowering/test_tile_to_repeat_pass.cpp
Added support for aten::tile using aten::repeat mechanism. Refer torch implementation for torch.tile
> feat: Added support for aten::tile converter

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/embedding.py
- Remove arguments not present in initial schema for embedding
- Improve coverage of embedding operator by expanding set of convertible implementations
- Update parameter-checking function accordingly
**Note:** Reflects [this embedding schema](https://github.com/pytorch/pytorch/blob/3a300ed84efa8e458df02ee4f92532667cefbe29/aten/src/ATen/native/native_functions.yaml#L2194-L2199).
- Existing …
> fix: Update `aten.embedding` to reflect schema

- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- tests/py/dynamo/converters/test_where_aten.py
- Update logic in broadcasting utility to reflect differing ranks, including 0D tensors
- Clean up code to reduce extra conditionals and variables
- Add regression test case to `aten.where` suite
Fixes #2227
> fix: Repair broadcasting utility for `aten.where`

- py/torch_tensorrt/dynamo/conversion/impl/condition/ops.py
- tests/py/dynamo/converters/test_where_aten.py
Fixes #2179 
Adds test case for the case where y_other dimension will not be equal to the broadcasted dimension
Further to do: Remove the evaluator section, since as discussed, this aten::where.self overload would have an unique schema having Tensor inputs, and by the time we get to partitioning/compilation the tracer already pre evaluates the constants
> Type mismatch for dynamo aten::where converter

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/slice/ops.py
- py/torch_tensorrt/dynamo/conversion/impl/unsqueeze.py
- tests/py/dynamo/converters/test_expand_aten.py
- Add support for `aten.expand.default` in Dynamo converter registry
- Build converter to support rank-padding for input Tensors, in line with the existing Torch behavior
- Add test case to validate new behavior, in addition to existing cases validating old behavior
Fixes #2183
- [ x ] I have added the relevant labels to my PR in so …
> fix: Allow rank differences in `aten.expand`

- core/runtime/execute_engine.cpp
- py/torch_tensorrt/_Input.py
- tests/py/dynamo/backend/test_specialized_models.py
- Remove dimension padding on inputs to TRT engines in runtime
- Add regression testing in Dynamo path
Fixes #2187
> fix: Address runtimes with 0D inputs

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/elementwise/ops.py
- py/torch_tensorrt/dynamo/conversion/impl/unary/ops.py
- tests/py/dynamo/converters/harness.py
- tests/py/dynamo/converters/test_abs_aten.py
- tests/py/dynamo/converters/test_acos_aten.py
- tests/py/dynamo/converters/test_acosh_aten.py
- tests/py/dynamo/converters/test_asin_aten.py
- tests/py/dynamo/converters/test_asinh_aten.py
- tests/py/dynamo/converters/test_atan_aten.py
- tests/py/dynamo/converters/test_atanh_aten.py
- tests/py/dynamo/converters/test_ceil_aten.py
- tests/py/dynamo/converters/test_cos_aten.py
- tests/py/dynamo/converters/test_cosh_aten.py
- tests/py/dynamo/converters/test_exp_aten.py
- tests/py/dynamo/converters/test_floor_aten.py
- tests/py/dynamo/converters/test_isinf_aten.py
- tests/py/dynamo/converters/test_log_aten.py
- tests/py/dynamo/converters/test_logical_not_aten.py
- tests/py/dynamo/converters/test_recip_aten.py
- tests/py/dynamo/converters/test_round_aten.py
- tests/py/dynamo/converters/test_sign_aten.py
- tests/py/dynamo/converters/test_sin_aten.py
- tests/py/dynamo/converters/test_sinh_aten.py
- tests/py/dynamo/converters/test_sqrt_aten.py
- tests/py/dynamo/converters/test_tan_aten.py
Implemented all 22 unary dynamo converters, including `EXP`, `LOG`, `SQRT`, `RECIP`, `ABS`, `SIN`, `COS`, `TAN`, `SINH`, `COSH`, `ASIN`, `ACOS`, `ATAN`, `ASINH`, `ACOSH`, `ATANH`, `CEIL`, `FLOOR`, `NOT`, `SIGN`, `ROUND`, `ISINF`.
Fixes #2199 
> feat: support many unary dynamo converters

- docker/Dockerfile
- Decrease Docker container size by cleaning up build cache/unnecessary files after building, uncompressed reduction of ~6GB
- Docker improvement
- CI Container
> fix: Decrease Docker container size by 20%

- py/torch_tensorrt/_Device.py
- py/torch_tensorrt/_compile.py
- py/torch_tensorrt/dynamo/_defaults.py
- py/torch_tensorrt/dynamo/_settings.py
- py/torch_tensorrt/dynamo/compile.py
- py/torch_tensorrt/dynamo/conversion/conversion.py
- py/torch_tensorrt/dynamo/utils.py
- tests/py/dynamo/backend/test_compiler_utils.py
- Enables support for device compilation settings in Dynamo paths
- Developed in a way such that extensions for multiple gpus can be made in a straightforward fashion
- Default device type/format can be customized
- Defaults to current present device, with context-aware switching, enable the following workflow for torch compile:
```python
with torch.cuda.device(1):
model = models.resnet18(pretrained=True).eval().cuda()
input = torch.randn((1, 3, 224, 224)).cuda()
compile_spec = {
"inputs": [
torchtrt.Input(
input.shape, dtype=torch.float, format=torch.contiguous_format
)
],
"enabled_precisions": {torch.float},
"debug": True,
"ir": "torch_compile",
}
trt_mod = torchtrt.compile(model, **compile_spec)
```
Fixes #2172 
- New feature …
> feat: Add support for device compilation setting

- .circleci/config.yml
- py/torch_tensorrt/_compile.py
- toolchains/ci_workspaces/WORKSPACE.x86_64.legacy
- toolchains/legacy/pyproject.toml
- Update `config.yaml` to support legacy CI testing, including upgraded `.toml` and `WORKSPACE` files built specifically for the legacy version
- Add parameters to the configuration file to allow switching CUDA versions for the legacy build
- Update default in `compile()` to be TorchScript in the legacy install
> fix: Legacy CI `pip` installation

- py/torch_tensorrt/dynamo/lowering/_decomposition_groups.py
- Add softmax default to disabled decompositions
- Improve typing of decopmosition sets
Fixes #2267
- Decomposition and documentation update
> feat: Exempt default softmax from decomposition

- docker/Dockerfile
- Previously, the Docker container size reduction (#2257) applied across multiple layers, causing the changes to not be reflected in the resultant container
- New container size is 23.8 GB, down from 27.9 GB
- Container size reduction
- GHA Build
- [ x ] I have added the relevant labels to my PR in so that relevant …
> fix: Unify layers in Docker Container Cleanup

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- py/torch_tensorrt/dynamo/conversion/impl/__init__.py
- py/torch_tensorrt/dynamo/conversion/impl/conv.py
- py/torch_tensorrt/dynamo/conversion/impl/squeeze.py
Support conv dynamo converter.
Fixes #2250, #2185
> feat: support conv dynamo converter

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/matmul.py
- tests/py/dynamo/conversion/test_matmul_aten.py
`set_layer_name(layer, target, name)` -> `set_layer_name(layer, target, name, source_ir)`
Fixes #2203 
> fix: add an arg in matmul

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/reduce.py
- tests/py/dynamo/conversion/test_sum_aten.py
Support `torch.ops.aten.sum.dim_IntList` dynamo converter
Fixes #2244 
> feat: support torch.ops.aten.sum.(default and dim_IntList) dynamo converter

- py/torch_tensorrt/dynamo/tools/opset_coverage.py
Updates the coverage tool to treat converters for default overloads to the root op name
> tools(opset_coverage): Map default ops to unoverloaded ops

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/unary/ops.py
- tests/py/dynamo/converters/test_neg_aten.py
Initial support for a dynamo converter.
> add initial support for torch.ops.aten.neg.default converter

- .github/workflows/build-test.yml
> chore: enabling TS FE testing

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- py/torch_tensorrt/dynamo/conversion/impl/elementwise/base.py
- py/torch_tensorrt/dynamo/conversion/impl/elementwise/ops.py
- tests/py/dynamo/conversion/test_add_aten.py
- tests/py/dynamo/conversion/test_div_aten.py
- tests/py/dynamo/conversion/test_equal_aten.py
- tests/py/dynamo/conversion/test_floor_div_aten.py
- tests/py/dynamo/conversion/test_greater_aten.py
- tests/py/dynamo/conversion/test_less_aten.py
- tests/py/dynamo/conversion/test_logical_and_aten.py
- tests/py/dynamo/conversion/test_logical_or_aten.py
- tests/py/dynamo/conversion/test_logical_xor_aten.py
- tests/py/dynamo/conversion/test_max_aten.py
- tests/py/dynamo/conversion/test_min_aten.py
- tests/py/dynamo/conversion/test_mul_aten.py
- tests/py/dynamo/conversion/test_pow_aten.py
- tests/py/dynamo/conversion/test_sub_aten.py
Support many elementwise dynamo converters, including `add`, `mul`, `maximum`, `minimum`, `sub`, `div`(already implemented), `pow`, `floor_divide`, `logical_and`, `logical_or`, `logical_xor`, `eq`, `gt`, `lt`
Fixes #2208 
> feat: support many elementwise dynamo converters

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/__init__.py
- py/torch_tensorrt/dynamo/conversion/impl/linear.py
Support linear (fully connected layer) dynamo converter.
Fixes #2251 
> feat: support linear (fully connected layer) dynamo converter

- tests/cpp/test_compiled_modules.cpp
- tests/cpp/test_modules_as_engines.cpp
- tests/modules/hub.py
More info:
https://github.com/huggingface/pytorch-image-models/issues/1946
> WAR: Disabling ViT tests until exporting with py311 is fixed

- py/torch_tensorrt/dynamo/conversion/impl/unary/ops.py
- tests/py/dynamo/conversion/test_neg_aten.py
> fix: Move aten.neg test case

- py/torch_tensorrt/dynamo/backend/backends.py
- Versioning does not recognize `2.1.0+cu118` as equal to `2.1.0`. Switch implementation to use less-than comparison
> small fix: Packaging version switch

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- py/torch_tensorrt/dynamo/conversion/impl/cast.py
- py/torch_tensorrt/dynamo/conversion/impl/elementwise/base.py
- tests/py/dynamo/conversion/test_casts.py
- TRT does not allow inputs of graphs to be outputs as well, however many of the scenarios encountered in real models can have this situation come up, especially in cases where the input is cloned or copied and then returned
- The current converters will register these operators as a no-op, causing TRT engine building to fail on such inputs
- Instead of requiring creation of an identity layer for every case of a clone or copy node, we instead check if that node is the only operator on a placeholder (input) and then insert the identity layer or not, accordingly
- Coalesce implementations of clone and to_copy, which are effectively the same operator
- Add test cases to validate new behavior
- Add new boilerplate converter validator utility to support this case
Addresses bug in #1565
- Bug …
> fix: Add special cases for `clone` and `to_copy` where input of graph is output

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- py/torch_tensorrt/dynamo/conversion/impl/__init__.py
- py/torch_tensorrt/dynamo/conversion/impl/split.py
- tests/py/dynamo/conversion/test_split_aten.py
- tests/py/dynamo/converters/test_split_aten.py
> aten::split converter

- core/conversion/converters/impl/shuffle.cpp
- tests/core/conversion/converters/test_shuffle.cpp
Fix errors in aten::flatten converter when encountering start index < 0 and end index < -1.
> fix: Support non -1 end idx and <0 start idx in aten::flatten converter

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/unary/ops.py
- tests/py/dynamo/conversion/test_erf_aten.py
This PR support dynamo converter for `torch.erf`
> Dynamo converter support for torch.ops.aten.erf.default op 

- py/torch_tensorrt/dynamo/runtime/_PythonTorchTensorRTModule.py
- tests/py/dynamo/runtime/test_python_runtime.py
- Enable support for 0D and 1D inputs in Python runtime
- Remove shape checks which are faulty in cases where inputs do not have an explicit batch
- Add regression test cases for the Python runtime
- [ x ] I have added the relevant labels to my PR in so that relevant …
> fix: Allow low rank inputs in Python Runtime

- core/runtime/execute_engine.cpp
- core/runtime/runtime.cpp
- core/runtime/runtime.h
- Fix issue where GPU ID of device compiled on was taking precedence over GPU ID of device in context
- Clean up logic in device detection
Fixes #2319 
Fixes #2269 
- See [`test_multi_gpu_serde.cpp`](https://github.com/pytorch/TensorRT/blob/8ebb5991f8bc46fea6179593b882d5c160bc1a53/tests/cpp/test_multi_gpu_serde.cpp)
- [ x ] New and …
> fix: Address multi-GPU issue in engine deserialize

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/__init__.py
- py/torch_tensorrt/dynamo/conversion/impl/deconv.py
- tests/py/dynamo/conversion/test_deconvolution_aten.py
Support deconv (1d, 2d, and Nd) dynamo converter.
Fixes #2207 
> feat: support deconv (1d, 2d, and Nd) dynamo converter

- py/torch_tensorrt/dynamo/lowering/substitutions/einsum.py
- py/torch_tensorrt/dynamo/lowering/substitutions/maxpool1d.py
Hi, I maintain the custom ops story in PyTorch. This PR updates the the usage of PyTorch's private custom op API to a newer API. This API is still private but closer to what we want it to be.
API migration.
> Update usage of PyTorch's custom op API

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- tests/py/dynamo/conversion/test_bmm.py
Support bmm converter for dynamo
> feat: support bmm converter in dynamo

- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- py/torch_tensorrt/dynamo/conversion/impl/normalization/ops.py
- py/torch_tensorrt/dynamo/conversion/impl/permutation.py
- py/torch_tensorrt/dynamo/conversion/impl/reduce.py
- py/torch_tensorrt/dynamo/conversion/impl/select.py
- py/torch_tensorrt/dynamo/conversion/impl/slice/ops.py
- py/torch_tensorrt/dynamo/conversion/impl/squeeze.py
- py/torch_tensorrt/dynamo/conversion/impl/unsqueeze.py
- tests/py/dynamo/conversion/test_amax_aten.py
- tests/py/dynamo/conversion/test_sum_aten.py
- Add key converter utility for getting positive dimension from negative counterpart, including extensions for getting positive dimension from a Sequence of input dimensions
- Update implementations across the library of converters
- Update test cases, including regression test
Fixes #2342
- [ x ] I have added the relevant labels to …
> fix: Add support for negative dimensions in reduce

- core/util/trt_util.cpp
- tests/py/ts/models/test_models.py
- Add condition to dynamic-dimension insertion for using zero dimension in place of dynamic (-1)
- This effectively enables 2 non-contiguous dynamic dimensions. For more than two, an additional fix/overhaul of the dimension squeeze system is needed
- Add regression test case to catch similar scenarios
Fixes #2331
- [ x  ] I have performed a self-review of my own code
- [ x ] I have …
> fix: Issue in TS dimension-squeeze utility

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/select.py
- tests/py/dynamo/conversion/test_index_aten.py
> Aten::Index converter

- py/torch_tensorrt/dynamo/conversion/__init__.py
- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/condition/ops.py
- py/torch_tensorrt/dynamo/conversion/impl/reduce.py
- py/torch_tensorrt/dynamo/conversion/impl/unsqueeze.py
- py/torch_tensorrt/dynamo/conversion/ops_evaluators.py
- py/torch_tensorrt/dynamo/conversion/prims_ops_converters.py
- tests/py/dynamo/conversion/test_div_aten.py
- tests/py/dynamo/conversion/test_sum_aten.py
- tests/py/dynamo/conversion/test_unsqueeze_aten.py
- tests/py/dynamo/conversion/test_where_aten.py
- Focus on SD-performance-accelerating converters
- Add minimal implementation for `broadcast_in_dim`
- Add `prims.div` support
- Fix bug in `sum`
- Fix bug in `where`
- Add test cases for converters to avoid regressions
Fixes: #2346 
- Perf improvements
- [ x ] I have …
> fix/feat: Add and repair multiple converters for SD + other models

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- py/torch_tensorrt/dynamo/conversion/impl/__init__.py
- py/torch_tensorrt/dynamo/conversion/impl/shuffle.py
- tests/py/dynamo/conversion/test_converter_utils.py
- tests/py/dynamo/conversion/test_reshape_aten.py
Support `flatten` and `reshape` via shuffle_layer
Fixes #2214
> feat: support flatten and reshape via shuffle_layer

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/reduce.py
- tests/py/dynamo/conversion/harness.py
- tests/py/dynamo/conversion/test_amax_aten.py
- tests/py/dynamo/conversion/test_max_aten.py
- tests/py/dynamo/conversion/test_maximum_aten.py
- tests/py/dynamo/conversion/test_min_aten.py
- tests/py/dynamo/conversion/test_minimum_aten.py
- tests/py/dynamo/conversion/test_prod_aten.py
- tests/py/dynamo/conversion/test_sum_aten.py
Support prod, max, min, and mean via reduce layer
Fixes #2205 
> feat: support prod, max, min, and mean via reduce layer

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/__init__.py
- py/torch_tensorrt/dynamo/conversion/impl/cat.py
This PR moves the aten::cat implementation to the dynamo impl library.
> Dynamo converter cat

- py/torch_tensorrt/dynamo/lowering/passes/constant_folding.py
- The latest Torch nightly changed certain operators which Inductor's constant fold utility references by name, causing errors when the constant folder is invoked
- This PR addresses those errors accordingly by subclassing the Torch utility as needed
Fixes #2374
- CI validation
- [ x ] I have added the relevant labels to my PR in so …
> fix: Repair issue in Torch Constant Folder

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/__init__.py
- py/torch_tensorrt/dynamo/conversion/impl/argmax.py
- tests/py/dynamo/conversion/test_argmax_aten.py
> support argmax converter

- docsrc/index.rst
- docsrc/user_guide/dynamic_shapes.rst
- docsrc/user_guide/torch_compile.rst
- py/torch_tensorrt/dynamo/_settings.py
- Add detailed descriptions of pre, during, and post compilation processes
- Add descriptions of valuable compile-time arguments
- Write about thress specific use cases of the tool
Fixes #2359
-Documentation
> docs: Add documentation of `torch.compile` backend usage

- py/torch_tensorrt/dynamo/backend/backends.py
- py/torch_tensorrt/dynamo/conversion/conversion.py
- py/torch_tensorrt/dynamo/conversion/impl/reduce.py
- py/torch_tensorrt/dynamo/conversion/impl/slice/ops.py
- py/torch_tensorrt/dynamo/utils.py
- tests/py/dynamo/conversion/test_slice_aten.py
- tests/py/dynamo/conversion/test_sum_aten.py
- Fix slice and sum converter bugs
- `slice` incorrectly parsed negative-indexed start or end indices
- `sum` needs to cast boolean tensors to int32, and can take the sum of int32 tensors
- Add regression test cases to validate fixes
- Fix issue where outputs can be torch.int64 when a sum of booleans is returned
- Fix issue where inputs in torch compile were being checked for contiguity
- Propagate fix to utility
Fixes #2400 
- [ x ] I have added tests …
> fix: Converter, inputs, and utils bugfixes for Transformer XL

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/embedding.py
- tests/py/dynamo/conversion/test_embedding_bag_aten.py
Support embedding_bag converter. Currently, only 1D input is supported.
schema: https://github.com/pytorch/pytorch/blob/bdecdfd202df3fa25fd9998070fd19fee4b14971/aten/src/ATen/native/native_functions.yaml#L2251
pytorch doc: https://pytorch.org/docs/stable/generated/torch.nn.functional.embedding_bag.html#torch-nn-functional-embedding-bag
Note: 
1. **We currently only support 1D input** because, in PyTorch, `offsets` is only used when input is 1D. If input is 2D of shape (B, N), it will be treated as B bags (sequences) each of fixed length N, and this will return B values aggregated in a way depending on the mode. `offsets` is ignored and required to be None in this case. However, according to the schema, `offsets` is required for input with any dimensions. There's no place describing how it …
> feat: support embedding_bag converter (1D input)

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/slice/ops.py
- tests/py/dynamo/conversion/test_chunk_aten.py
Support `chunk` dynamo converter. This is a part of `slice` converter.
Fixes part of #2215 
> feat: support chunk dynamo converter

- docsrc/user_guide/saving_models.rst
- py/requirements.txt
- py/torch_tensorrt/dynamo/__init__.py
- py/torch_tensorrt/dynamo/compile.py
- py/torch_tensorrt/dynamo/export.py
- tests/py/dynamo/models/test_export_serde.py
1) The API to generate an exported program from a TRT graphmodule is as follows:
```
exp_program = torchtrt.dynamo.trace(model, **compile_spec)
trt_gm = torchtrt.dynamo.compile(exp_program, **compile_spec)
trt_exp_program = torchtrt.dynamo.transform(trt_gm, [input], exp_program.call_spec)
```
2) Changed dynamo.compile to allow torch.fx.GraphModules.
> feat: Wrap ExportedPrograms transformations with an API, allow dynamo.compile to accept graphmodules.

- docsrc/index.rst
- docsrc/user_guide/dynamo_export.rst
- docsrc/user_guide/saving_models.rst
> chore: Add documentation for dynamo.compile backend

- py/torch_tensorrt/dynamo/tools/opset_coverage.py
The opset_coverage.py tool was failing with the following error:
```
Traceback (most recent call last):
File "/opt/torch_tensorrt/py/torch_tensorrt/dynamo/tools/opset_coverage.py", line 213, in <module>
find_coverage_status(ATEN_OPS, "ATen")
File "/opt/torch_tensorrt/py/torch_tensorrt/dynamo/tools/opset_coverage.py", line 199, in find_coverage_status
coverage = opset_coverage(opset)
File "/opt/torch_tensorrt/py/torch_tensorrt/dynamo/tools/opset_coverage.py", line 147, in opset_coverage
elif registry_data["FX ATen Converters Registry"] >= 1:
KeyError: 'FX ATen Converters Registry'
```
For some reason, some ATen and Prims ops appear with the registry name "FX Legacy ATen Converters Registry"
> Support new FX Legacy Registry in opset coverage tool

- py/torch_tensorrt/dynamo/conversion/impl/embedding.py
There's a type error bug in `embedding_bag` implementation. This is a fix to the PR #2395 
> fix: type error in embedding_bag

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/slice/ops.py
- tests/py/dynamo/conversion/test_cumsum_aten.py
Support `cumsum` dynamo converter. This is a part of `slice` converter.
Fixes part of #2215 
> feat: support cumsum dynamo converter

- .github/workflows/docker_builder.yml
- tools/perf/benchmark.sh
- tools/perf/custom_models.py
- tools/perf/hub.py
- tools/perf/perf_run.py
- tools/perf/requirements.txt
- tools/perf/utils.py
- Add new key models to benchmarking scripts
- Add fixes and improvements to existing benchmarking code
- Code improvements
- New models for benchmarking
> feat/fix: Add new models, fix perf scripts

- tools/perf/benchmark.sh
- tools/perf/hub.py
- tools/perf/perf_run.py
- tools/perf/utils.py
- Switch model dictionary to lazy-loading scheme
- Change model references to name-based instead of file-based
> fix: Upgrade perf benchmark system

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/slice/ops.py
- tests/py/dynamo/conversion/test_tile_aten.py
Support `tile` dynamo converter. This is a part of `slice` converter.
Fixes part of #2215 
> feat: support tile dynamo converter

- .circleci/config.yml
- README.md
- WORKSPACE
- dev_dep_versions.yml
- docker/README.md
- tools/perf/perf_run.py
- tools/perf/utils.py
- Segfault fix for benchmarking on Docker container with CUDNN 8.8
- Likely due to Torch 2.1.0 based on CUDNN 8.9
- [ x ]  I have commented my code, particularly in hard-to-understand areas and hacks
- Tested manually in Docker
> fix: Segfault fix for Benchmarks

- .github/workflows/docker_builder.yml
- Removes forward slashes from container names to avoid issues with tags and naming
- GHA fix
- [ - ] My code follows the style guidelines of this project (You can use the linters)
- [ - ] I have performed a self-review of my own code
- [ - ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ - ] I have made corresponding changes to the documentation
- [ - ] New and existing unit tests pass locally with my changes
- [ - ] I have added the relevant labels to my PR in so that relevant reviewers are notified
> minor fix: Parse out slashes in Docker container name

- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- py/torch_tensorrt/dynamo/conversion/impl/select.py
- tests/py/dynamo/conversion/test_index_aten.py
This PR addresses the changes for the cases where indices are list of numpy arrays or numpy for aten::index. #2394
> Numpy changes for aten::index converter

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/lowering/_decomposition_groups.py
- tests/py/dynamo/conversion/test_batch_norm_aten.py
This change adds an additional native BN converter which improves performance of models using BN
> chore: add additional native BN converter (cherry-pick of #2446)

- .github/workflows/docker_builder.yml
- docsrc/index.rst
- Cherry pick of #2440 
- Cherry-pick of PR to `release/2.1` branch
- [ - ] My code follows the style guidelines of this project (You can use the linters)
- [ - ] I have performed a self-review of my own code
- [ - ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ - ] I have made corresponding changes to the documentation
- [ - ] New and existing unit tests pass locally with my changes
- [ - ] I have added the relevant labels to my PR in so that relevant reviewers are notified
> cherry-pick/fix: Docs rendering on PyTorch site (#2440)

- tools/perf/accumulate_results.py
- tools/perf/benchmark.sh
- tools/perf/perf_run.py
- Benchmark script fix
- `torch.compile` requires `no_grad` even during the initial compilation phase to avoid adding backward-pass instrumentation to the model
> fix: Wrap perf benchmarks with no_grad

- README.md
- WORKSPACE
- py/requirements.txt
- Upgrade `release/2.1` to use Torch 2.1.1 and Torchvision 0.16.1
- Version Upgrade
> chore: Upgrade `release` to Torch 2.1.1

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- py/torch_tensorrt/dynamo/conversion/impl/slice/ops.py
- tests/py/dynamo/conversion/test_slice_aten.py
- Slice operator schema allows optional inputs for specified dimensions and allows not specifying certain inputs at all
- Fix issue where the converter did not reflect these Torch behaviors
- Fix issue where bounds past the end of the array were not allowed (as they are in Python, ONNX, Torch)
- Add regression tests to catch such errors
[Slice Schema](https://github.com/pytorch/pytorch/blob/68278cf7a805d2307859bbc364f2e163ae6dba67/aten/src/ATen/native/native_functions.yaml#L5340)
- [ x ] I have made corresponding …
> fix: Bug in slice operator with default inputs

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- py/torch_tensorrt/dynamo/conversion/impl/__init__.py
- py/torch_tensorrt/dynamo/conversion/impl/grid.py
- tests/py/dynamo/conversion/test_grid_aten.py
> Expose IGridSampleLayer

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/elementwise/base.py
- py/torch_tensorrt/dynamo/conversion/impl/elementwise/ops.py
- py/torch_tensorrt/dynamo/conversion/impl/unary/ops.py
- tests/py/dynamo/conversion/test_bitwise_and_aten.py
- tests/py/dynamo/conversion/test_bitwise_not_aten.py
- tests/py/dynamo/conversion/test_bitwise_or_aten.py
- tests/py/dynamo/conversion/test_bitwise_xor_aten.py
- tests/py/dynamo/conversion/test_eq_aten.py
- tests/py/dynamo/conversion/test_ge_aten.py
- tests/py/dynamo/conversion/test_gt_aten.py
- tests/py/dynamo/conversion/test_le_aten.py
- tests/py/dynamo/conversion/test_lt_aten.py
- tests/py/dynamo/conversion/test_ne_aten.py
Support more elementwise and unary dynamo converters.
For `bitwise_op` converters, TensorRT doesn't support bitwise ops. Thus, if inputs are `int` values, they will fall back to pytorch. If inputs are `bool`, they will be converted with the help of `logical_op`.
Fixes #2208 #2199 
> feat: support more elementwise and unary dynamo converters

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- py/torch_tensorrt/dynamo/conversion/impl/slice/ops.py
- py/torch_tensorrt/dynamo/lowering/passes/_aten_lowering_pass.py
- py/torch_tensorrt/dynamo/lowering/passes/view_to_reshape.py
- tests/py/dynamo/conversion/test_slice_aten.py
- tests/py/dynamo/lowering/test_aten_lowering_passes.py
- Cherry-pick of #2464 
- Cherry-pick of #2463
- Cherry-pick to `release/2.1`
> cherry-pick: View and slice bugfixes

- tools/perf/benchmark.sh
- tools/perf/perf_run.py
- tools/perf/requirements.txt
> chore: Add TRT runner via onnx

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/reduce.py
- tests/py/dynamo/conversion/test_amin_aten.py
Support `aten.amin` dynamo converter
Fixes #2493 
> feat: support aten.amin dynamo converter

- py/torch_tensorrt/dynamo/conversion/impl/slice/ops.py
- tests/py/dynamo/conversion/test_cumsum_aten.py
- tools/perf/benchmark.sh
- tools/perf/perf_run.py
- tools/perf/requirements.txt
- Cherry-pick of #2403 
- Fixes bug where `aten.cumsum` and `aten.chunk` have converters but no implementation on the branch
- Cherry-pick of #2503
- Cherry-pick to `release/2.1`
> cherry-pick: Perf + Bugfix PRs

- py/torch_tensorrt/dynamo/conversion/ops_evaluators.py
- tests/py/dynamo/conversion/test_arange_aten.py
Support `aten.arange.start_step` dynamo converter.
Fixes #2492 
> feat: support aten.arange.start_step dynamo converter

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/__init__.py
- py/torch_tensorrt/dynamo/conversion/impl/topk.py
- tests/py/dynamo/conversion/test_argmin_aten.py
Support argmin converter. 
#2498
> feat: support argmin aten converter

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/__init__.py
- py/torch_tensorrt/dynamo/conversion/impl/upsample.py
- tests/py/dynamo/conversion/test_upsample.py
#2219 
Expose IResizeLayer in dynamo.conversion.impl
> feat: expose IResizeLayer in dynamo.conversion.impl

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/topk.py
- tests/py/dynamo/conversion/test_sort_aten.py
Support `aten.sort` dynamo converter.
Fixes #2508 
> feat: support aten.sort dynamo converter

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
See details in the issue below.
Fixes #2480 
> fix: aten.index converter

- py/requirements.txt
- pyproject.toml
- tests/modules/custom_models.py
- tests/modules/requirements.txt
Fix bugs with new nightly version restrictions
> fix: Torch nightly version constraint

- core/conversion/conversionctx/ConversionCtx.cpp
- core/runtime/register_jit_hooks.cpp
Converting a torchscript with torch-tensorRT shows large memory leaks. A simple way to reproduce the leaks is provided in this script:
```python
import numpy as np
import torch_tensorrt as trt
import torch
import torchvision
import psutil
import gc
if __name__ == "__main__":
network = torchvision.models.mobilenet_v2(pretrained=True)
network.eval().cuda()
torch_s = torch.jit.script(network)
compile_settings = {
"inputs": [
trt.Input([1, 3, 224, 224])
],
"enabled_precisions": {torch.float32},
}
output_path = "/tmp/trt.ts"
for _ in range(3):
print(f"Used Virtual Memory: {psutil.virtual_memory().used / (1024*1024)}")
trt_ts_module = trt.compile(torch_s, **compile_settings)
torch.jit.save(trt_ts_module, output_path)
del trt_ts_module
gc.collect()
```
Running this script prints the used memory …
> Fix memory leaks

- .github/workflows/docker_builder.yml
- py/requirements.txt
- pyproject.toml
- Version upgrade bump, narrow specification of versions
- Docker builder switch to GPU-provisioned machine
- Fixes build issue for Docker container
> fix: Docker builder with new Torch versions

- core/conversion/converters/impl/matrix_multiply.cpp
- tests/core/conversion/converters/test_matrix_multiply.cpp
Previously the aten::matmul converter always left padded tensors to match dims between self and other. This behavior does not match PyTorch which right pads 1D tensors by 1 for other > self and left pads by 1 for self > other, removing the padded dim after the matmul in both cases.
> Fix: aten::matmul converter behavior with 1d tensors

- py/torch_tensorrt/dynamo/_DryRunTracker.py
- py/torch_tensorrt/dynamo/_compiler.py
- py/torch_tensorrt/dynamo/_defaults.py
- py/torch_tensorrt/dynamo/_settings.py
- py/torch_tensorrt/dynamo/partitioning/_adjacency_partitioner.py
- py/torch_tensorrt/dynamo/partitioning/_global_partitioner.py
- py/torch_tensorrt/dynamo/utils.py
- tests/py/dynamo/backend/test_backend_compiler.py
- tests/py/dynamo/partitioning/test_fast_partitioning.py
- tests/py/dynamo/partitioning/test_global_partitioning.py
- tests/py/dynamo/testing_utilities.py
- Enables building of TRT engines with "dryrun" capabilities, meaning all of the phases except conversion are run and verbose logs of the graph structure and composition are printed for the user
- Improves general-purpose debug logging by printing dryrun stats to the debug logs regardless of option specification
- Provides intuitive schematic of the graph engines, inputs, and code path through the course of the graph
<details>
<summary>
<b>Sample Schematic</b>
</summary>
```python
++++++++++++++++++++++++++++++++++++++++++++++++++ Dry-Run Results for Graph ++++++++++++++++++++++++++++++++++++++++++++++++++
The graph consists of 89 Total Operators, of which 81 operators are supported, 91.01% coverage
The following ops are currently unsupported or excluded from conversion, and are listed …
```
> feat: Add dryrun feature to Dynamo paths

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/unary/ops.py
- tests/py/dynamo/conversion/test_trunc_aten.py
Support `aten.trunc` dynamo converter
Fixes #2536 
> feat: support aten.trunc dynamo converter

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- tests/py/dynamo/conversion/test_copy_aten.py
Support `aten.copy` dynamo converter.
Fixes #2435 
> feat: support aten.copy dynamo converter

- py/torch_tensorrt/dynamo/_compiler.py
- py/torch_tensorrt/dynamo/_settings.py
- py/torch_tensorrt/dynamo/conversion/_ConverterRegistry.py
- py/torch_tensorrt/dynamo/partitioning/_adjacency_partitioner.py
- py/torch_tensorrt/dynamo/partitioning/_global_partitioner.py
- tests/py/dynamo/models/test_dyn_models.py
- tests/py/dynamo/models/test_export_serde.py
- Previously, `torch_executed_ops` were excluded at partitioning time, but not conversion time, causing a bug with obscure usages of `getitem`
- Now, `torch_executed_ops` are excluded at partitioning time and their converters are explicitly disabled
- [ x ] I have added the relevant labels to my PR in so that relevant reviewers are …
> fix: Repair usage of `torch_executed_ops`

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- tests/py/dynamo/conversion/test_casts.py
- Fixes the case where engines return multiple copies of the same tensor with inserted casts. This behavior is disallowed in TRT
- Added regression test case
- This fix should be removed once #2561 is merged
- [ x ] I have added the relevant labels to my PR in so that …
> fix: Switch all copies to force cast

- py/torch_tensorrt/dynamo/conversion/impl/condition/ops.py
This PR exposes ISelect layer. Fixes #2213. 
Note it does not have test cases since `aten.select` uses TensorRT gather layer. TensorRT select layer is used by `aten.where`. So the functionality will be tested by where test cases.
> Exposing select layer

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/elementwise/ops.py
- tests/py/dynamo/conversion/test_remainder_aten.py
Support `aten.remainder.Scalar` and `aten.remainder.Tensor`
Fixes #2564 #2565 
> feat: support aten.remainder.Scalar and aten.remainder.Tensor

- core/conversion/converters/BUILD
- core/conversion/converters/impl/internal_ops.cpp
- core/conversion/converters/impl/unary.cpp
- core/lowering/lowering.cpp
- core/lowering/passes/BUILD
- core/lowering/passes/passes.h
- core/lowering/passes/unpack_scaled_dot_product_attention.cpp
- core/lowering/register_trt_placeholder_ops.cpp
- tests/core/conversion/converters/BUILD
- tests/core/conversion/converters/test_scaled_dot_product_attention.cpp
- tests/core/conversion/converters/test_unary.cpp
Adds a lowering pass to unpack scaled_dot_product_attention. Required a fix to aten::sqrt converter to support int32 inputs. Uses a custom op with converter to handle bool attn_mask behavior.
https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html
> [feat] Support conversion of scaled_dot_product_attention

- .github/workflows/assigner.yml
- .github/workflows/build-test.yml
- .github/workflows/label.yml
The default write permission of the token has been revoked org-wide, so we need to set that explicitly here for these workflows that update PRs (write).
(Also update the labeler to v4 cause why not)
> Grant write permission to token

- .github/workflows/build-test.yml
The credential has been revoked to be replaced by OIDC https://github.com/pytorch/test-infra/pull/4865
> Clean up AWS credentials

- py/torch_tensorrt/_compile.py
- py/torch_tensorrt/dynamo/__init__.py
- py/torch_tensorrt/dynamo/_compiler.py
- py/torch_tensorrt/dynamo/conversion/__init__.py
- py/torch_tensorrt/dynamo/conversion/_conversion.py
- tests/py/dynamo/runtime/test_convert_method_to_trt_engine.py
Add a function `convert_method_to_trt_engine()` for dynamo.
I'm not familiar with this part, so detailed reviews and suggestions are greatly welcome.
Fixes #2410 
> feat: add `convert_method_to_trt_engine()` for dynamo

- .github/workflows/assigner.yml
- .github/workflows/build-test.yml
- .github/workflows/label.yml
- .github/workflows/linux-test.yml
Adds the following changes
1) https://github.com/pytorch/TensorRT/pull/2592
2) https://github.com/pytorch/TensorRT/pull/2591
> chore: clean up AWS credentials PR changes

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/reduce.py
- tests/py/dynamo/conversion/test_any.py
> feat: support aten.any related converters in dynamo

- .github/workflows/docker_builder.yml
- Update Docker Build GHA for release branch
> fix: Update release branch for Docker build GHA

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/shuffle.py
- tests/py/dynamo/conversion/test_pixel_shuffle_aten.py
Support `aten.pixel_shuffle` dynamo converter.
Fixes #2594 
> feat: support aten.pixel_shuffle dynamo converter

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/permutation.py
- tests/py/dynamo/conversion/test_roll_aten.py
Support `aten.roll` dynamo converter.
Fixes #2567 
> feat: support aten.roll dynamo converter

- .pre-commit-config.yaml
- examples/int8/training/vgg16/vgg16.py
- py/torch_tensorrt/_Device.py
- py/torch_tensorrt/_Input.py
- py/torch_tensorrt/dynamo/_compiler.py
- py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py
- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- py/torch_tensorrt/dynamo/lowering/_decomposition_groups.py
- py/torch_tensorrt/dynamo/lowering/passes/lower_linear.py
- py/torch_tensorrt/dynamo/lowering/passes/lower_scaled_dot_product_attention.py
- py/torch_tensorrt/dynamo/lowering/passes/view_to_reshape.py
- py/torch_tensorrt/dynamo/runtime/_PythonTorchTensorRTModule.py
- py/torch_tensorrt/fx/converters/aten_ops_converters.py
- py/torch_tensorrt/fx/fx2trt.py
- py/torch_tensorrt/fx/lower.py
- py/torch_tensorrt/fx/passes/lower_basic_pass.py
- py/torch_tensorrt/fx/passes/lower_pass_manager_builder.py
- py/torch_tensorrt/fx/passes/pass_utils.py
- py/torch_tensorrt/fx/test/converters/acc_op/test_split.py
- py/torch_tensorrt/fx/tools/common_fx2trt.py
- py/torch_tensorrt/fx/trt_module.py
- py/torch_tensorrt/ts/_compile_spec.py
- pyproject.toml
- Fix linter issue with version upgrade
- Linter fix
> fix: Linter + config fix

- py/torch_tensorrt/dynamo/_compiler.py
- Cherry-pick of #2635
- Cherry-pick
> cherry-pick: Remove extraneous argument in `compile` (#2635)

- examples/dynamo/torch_compile_advanced_usage.py
- examples/dynamo/torch_compile_transformers_example.py
- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- tests/py/dynamo/conversion/test_index_aten.py
- Currently, pending the implementation of #2590, constant index Tensors are type `int64` before being frozen. This workaround enables valid usecases while #2590 is being implemented
> small fix: Index validator enable int64

- examples/dynamo/torch_compile_advanced_usage.py
- examples/dynamo/torch_compile_transformers_example.py
- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- tests/py/dynamo/conversion/test_index_aten.py
- Cherry-pick of #2642 
- Cherry-pick
> small fix: Index validator enable int64 (#2642)

- tests/py/dynamo/conversion/test_pool_aten.py
Update tests of pooling converters.
> fix: update tests of pooling converters

- core/conversion/converters/impl/conv_deconv.cpp
- tests/core/conversion/converters/test_conv_deconv.cpp
This PR enables the conv1d -> conv2d converter mapping work when the weights are Tensor.
PS: Kernel tensor is also unsqueezed when the filterDims are unsqueezed for conv1d -> conv2d scenario.
> feat: Fixed conv1d converter when weights are Tensor

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/unary/ops.py
- tests/py/dynamo/conversion/test_log10.py
support converter for torch.log10
> feat: support converter for torch.log10

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/unary/ops.py
- tests/py/dynamo/conversion/test_log2.py
Support converter for torch.log2
> [feat] support converter for torch.log2

- .github/workflows/linux-test.yml
- WORKSPACE
- docker/dist-build.sh
- py/requirements.txt
- toolchains/ci_workspaces/WORKSPACE.x86_64.release.rhel.tmpl
> chore: update pytorch to 2.3

- py/torch_tensorrt/dynamo/conversion/_conversion.py
- py/torch_tensorrt/dynamo/lowering/passes/constant_folding.py
- Register all constants as model parameters, which do not get fake-ified by the active FakeTensor context
- Buffers and other constant registrations can be fake-ified, which is problematic for TRT tracing
Fixes #2658
- Pending CI verification on existing models
- [ x …
> fix: FakeTensors appearing in `get_attr` calls

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/pool.py
- tests/py/dynamo/conversion/test_adaptive_avgpool_aten.py
Support `adaptive_avg_pool1d` dynamo_converter.
Fixes #2603 
> feat: support adaptive_avg_pool1d dynamo converter

- core/lowering/passes/CMakeLists.txt
Add missing source file `core/lowering/passes/unpack_scaled_dot_product_attention.cpp` to `core/lowering/passes/CMakeLists.txt`. If not do so, when building shared library `torchtrt` will fail due to missing reference to function `UnpackScaledDotProductAttention`.
> fix: Add cmake missing source file ref for core_lowering.passes

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/shuffle.py
- tests/py/dynamo/conversion/test_pixel_unshuffle_aten.py
> Add support for `aten.pixel_unshuffle` dynamo converter

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/elementwise/ops.py
- tests/py/dynamo/conversion/test_atan2_aten.py
New feature to support aten.atan2 converter. I also add test case including edge case for inputs are zero. 
Fixes # ([issue](https://github.com/pytorch/TensorRT/issues/2586))
> feat: support aten.atan2 converter

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/unary/ops.py
- tests/py/dynamo/conversion/test_isnan_aten.py
In TRT, there isn't a direct way to check for NaN values, so I used a clever method. This method involves comparing the tensor to itself; input == input will only be false when dealing with NaN values.
Fixes # ([issue](https://github.com/pytorch/TensorRT/issues/2712))
> feat: support aten.isnan converter

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/pool.py
- tests/py/dynamo/conversion/test_adaptive_avgpool_aten.py
Support `adaptive_avg_pool2d` and `adaptive_avg_pool3d`.
Fixes #2611 #2612 
> feat: support adaptive avg pool 2d and 3d dynamo converters

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/unary/ops.py
- tests/py/dynamo/conversion/test_expm1_aten.py
New feature to support aten.expm1 converter. I also add test case for exponential constant with different dimensions.
Fixes # ([issue](https://github.com/pytorch/TensorRT/issues/2713))
> feat: support aten.expm1 converter

- tests/py/dynamo/conversion/test_binary_ops_aten.py
Fixed a param bug in `test_binary_ops_aten`. The param is required to be a tuple instead of a single value.
> fix: param bug in `test_binary_ops_aten`

- py/torch_tensorrt/dynamo/lowering/_decomposition_groups.py
- py/torch_tensorrt/dynamo/lowering/_decompositions.py
- tests/py/dynamo/lowering/test_decompositions.py
This is an extension to support aten::empty_like.
> empty_permute decomposition

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/lowering/_decomposition_groups.py
- tests/py/dynamo/conversion/test_grid_aten.py
This PR addresses the issue #2665 
1. Removing grid_sampler_2d from lowering ops
2. Adding grid_sampler.default and grid_sampler_2d.default to the CONVERTER key registry
3. Adding tests for grid_sampler.default and grid_sampler_2d.default tests
4. Restructing the test
5. Correcting the interpolation mode and padding mode in the tests
> Removing grid lowering

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
Partially #2665
Even though the operator is properly registered along with #2681 being applied, the operator is still decomposed into lower-level operators rather than converted using this converter, just like https://github.com/pytorch/TensorRT/issues/2665#issuecomment-1975168297. Adding `aten.upsample_bilinear2d.default` and `aten.upsample_bilinear2d.vec` to [torch_disabled_decompositions](https://github.com/pytorch/TensorRT/blob/ad74a735056667726692c49a175a790647ef889e/py/torch_tensorrt/dynamo/lowering/_decomposition_groups.py#L178) doesn't help. Compiling the model under `with torch.inference_mode()` also doesn't help. At the end I find out that I have to remove [these two lines](https://github.com/pytorch/pytorch/blob/660ec3d38d9d1c8567471ae7fe5b40ae7c6d7438/torch/_decomp/decompositio …
> Fix upsample converter not properly registered

- core/conversion/converters/impl/interpolate.cpp
- tests/core/conversion/converters/test_interpolate.cpp
Adds converter support for aten::grid_sampler in the TorchScript frontend. https://pytorch.org/docs/stable/generated/torch.nn.functional.grid_sample.html
> feat: TS Add converter support for aten::grid_sampler

- py/requirements.txt
- Fixes broken `torchvision` import in latest Docker containers
- Dependency fix
> fix: Bump `torchvision` version

- py/torch_tensorrt/dynamo/conversion/impl/normalization/ops.py
- py/torch_tensorrt/dynamo/conversion/impl/select.py
- py/torch_tensorrt/dynamo/conversion/impl/squeeze.py
- py/torch_tensorrt/dynamo/conversion/impl/unsqueeze.py
- Remove references to `network.has_implicit_batch_dimension` for TRT 10
- Default `network.has_implicit_batch_dimension=False`
- Remove deprecated code
- Validated in CI
> fix: Remove references to implicit batch for TRT 10

- docsrc/py_api/dynamo.rst
- py/torch_tensorrt/_compile.py
- py/torch_tensorrt/dynamo/_compiler.py
- tests/py/dynamo/runtime/test_convert_module_to_trt_engine.py
fix: `convert_module_to_trt_engine`
add doc.
Fixes #2692
> fix: convert_module_to_trt_engine

- WORKSPACE
- docsrc/getting_started/installation.rst
NOTE: There should not be a reason you need to modify the WORKSPACE now to build the repo, deps should get pulled automatically.
> chore: bump deps for default workspace file

- .github/workflows/build-test.yml
- Fix issue in `nightly` + `main` where infra points to a fixed channel and release branch
- Infra bug fix (non-breaking change which fixes an issue)
> fix: Point infra branch to main

- tests/py/dynamo/lowering/test_decompositions.py
This excludes the test of the values in `empty_like` and instead checks for equal shapes from torch and torchTRT
> "empty_like" decomposition test correction

- py/torch_tensorrt/dynamo/conversion/impl/normalization/ops.py
- tests/py/dynamo/conversion/test_layer_norm_aten.py
Refactored `layer norm` converter with TRT INormalization Layer
Fixes #2730
> fix: refactor layer norm converter with INormalization Layer

- .github/scripts/install-torch-tensorrt.sh
- .github/workflows/build-test.yml
- README.md
- WORKSPACE
- dev_dep_versions.yml
- packaging/pre_build_script.sh
- py/requirements.txt
- py/torch_tensorrt/csrc/torch_tensorrt_py.cpp
- pyproject.toml
- tests/py/dynamo/models/test_dyn_models.py
- toolchains/ci_workspaces/WORKSPACE.x86_64.release.rhel.tmpl
This PR runs CI to test TRT-10 GA support for main branch.
> TRT-10 GA Support for main branch

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/attention.py
- py/torch_tensorrt/dynamo/lowering/passes/lower_scaled_dot_product_attention.py
- tests/py/dynamo/conversion/test_attention.py
- tests/py/dynamo/lowering/test_aten_lowering_passes.py
- Add support for `is_causal` argument in attention converter
> feat: Add support for `is_causal` argument in attention

- py/torch_tensorrt/dynamo/conversion/ops_evaluators.py
- tests/py/dynamo/conversion/harness.py
- tests/py/dynamo/conversion/test_rand_aten.py
Covers the converters- aten.rand, aten.randn, aten.randperm
> Rand converter - evaluator

- tests/py/dynamo/conversion/harness.py
Fix a bug in func `run_test_compare_tensor_attributes_only`
Fixes #2808 
> fix: a bug in func run_test_compare_tensor_attributes_only

- py/torch_tensorrt/ts/ptq.py
```bash
holy@HOLYWU:~$ python3 -c "import torch_tensorrt.ts.ptq"
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/home/holy/.local/lib/python3.10/site-packages/torch_tensorrt/ts/ptq.py", line 14, in <module>
from py.torch_tensorrt.ts.logging import Level, log
ModuleNotFoundError: No module named 'py'
```
> Fix ModuleNotFoundError in ptq

- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- py/torch_tensorrt/dynamo/conversion/impl/elementwise/base.py
- tests/py/dynamo/conversion/test_binary_ops_aten.py
- tests/py/dynamo/conversion/test_bitwise_and_aten.py
- tests/py/dynamo/conversion/test_bitwise_or_aten.py
- tests/py/dynamo/conversion/test_bitwise_xor_aten.py
> fix: bug in elementwise base for static inputs

- .gitignore
- py/torch_tensorrt/dynamo/tools/opset_coverage.py
- tools/opset_coverage.ipynb
> tool: Opset coverage notebook

- packaging/pre_build_script_windows.sh
- As is added in #2806 for C++ builds, enable `--release` flag for builds in `main` to enable correct nightly versioning on PyTorch index
- Address CI Issue
> ci: Add release flag for nightly build tag

- docsrc/dynamo/torch_compile.rst
TensorRT backend for torch.compile documentation, In the snippet it sets the precision using options={"precision": torch.half} which isn’t documented and dosen’t seem to have effect and it should be replaced by options={"enabled_precisions": [torch.half]}
> [doc] Update options documentation for torch.compile

- core/util/trt_util.cpp
- core/util/trt_util.h
- py/torch_tensorrt/_enums.py
- py/torch_tensorrt/dynamo/_defaults.py
- py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py
- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- tests/py/dynamo/models/test_dtype_support.py
> feat(//py/torch_tensorrt/dynamo): Support for BF16

- docsrc/index.rst
- examples/distributed_inference/README.md
- examples/distributed_inference/data_parallel_gpt2.py
- examples/distributed_inference/data_parallel_stable_diffusion.py
- examples/distributed_inference/requirement.txt
This PR shows a simple example about using `accelerate` library for data parallel inference.
> feat: data parallel inference examples

- py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py
- py/torch_tensorrt/dynamo/runtime/_PythonTorchTensorRTModule.py
Fix bugs in TRT 10 upgrade.
Fixes #2811 
> fix: bugs in TRT 10 upgrade

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/linear.py
- py/torch_tensorrt/dynamo/conversion/impl/normalization/ops.py
- tests/py/dynamo/conversion/test_cdist_aten.py
New feature to support aten._cdist_forward converter converter. I have added test cases ensuring compatibility with both matching and broadcasting input shapes.
Fixes # ([issue](https://github.com/pytorch/TensorRT/issues/2725))
> feat: support aten._cdist_forward converter

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/unary/ops.py
- tests/py/dynamo/conversion/test_log1p.py
A converter for the torch.ops.aten.log1p operation (elementwise log(1 + x))
Fixes # ([issue](https://github.com/pytorch/TensorRT/issues/2760))
> feat: support aten.log1p converter

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/select.py
- tests/py/dynamo/conversion/harness.py
- tests/py/dynamo/conversion/test_scatter_aten.py
> Aten scatter converter

- .github/workflows/build-test-linux.yml
- .github/workflows/build-test-windows.yml
- py/torch_tensorrt/_enums.py
- tests/py/requirements.txt
> chore: Make from and to methods use the same TRT API

- py/torch_tensorrt/dynamo/conversion/impl/slice/ops.py
This change got excluded from the DS suppport PR by mistake. 
> chore: Minor fix 2.3

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- py/torch_tensorrt/dynamo/conversion/impl/slice/ops.py
- tests/py/dynamo/conversion/test_diagonal_aten.py
A converter for the torch.ops.aten.diagonal operation. There are very good reference for aten.diagonal operation ( https://github.com/pytorch/pytorch/blob/082251e76b93b277ff2791d0e2b64934add34644/torch/_refs/__init__.py#L4255 )
Fixes # ([issue](https://github.com/pytorch/TensorRT/issues/2846))
> feat: support aten.diagonal converter

- py/torch_tensorrt/dynamo/lowering/_decompositions.py
- tests/py/dynamo/lowering/test_decompositions.py
Fixes #2434 
This PR would be dependant on #2664 and #2669. Major changes
1. 2664- Implementation makes use of `aten::scatter.src`
2. 2669- Constants getting converted to fake tensors in `get_attr` call due to which different device location `meta` and` cpu` in torch
> slice_scatter decomposition

- py/torch_tensorrt/dynamo/lowering/_decompositions.py
- tests/py/dynamo/lowering/test_decompositions.py
Fixes #2436
This PR would be dependant on https://github.com/pytorch/TensorRT/pull/2519, https://github.com/pytorch/TensorRT/pull/2664 and https://github.com/pytorch/TensorRT/pull/2669. Major changes
2519- Decomposition of aten::slice_scatter
2664- Implementation makes use of aten::scatter.src
2669- Constants getting converted to fake tensors in get_attr call due to which different device location meta and cpu in torch
> select_scatter decomp

- README.md
- py/ci/Dockerfile.ci
- py/ci/build_whl.sh
- py/ci/soname_excludes.params
Current many linux auditwheel build is broken for TensorRT10.0.1
The yum install cannot find the new TensorRT10.0.1
Switch to download the tarball from official TensorRT site and pip install it.
> manylinux wheel file build update for TensorRT-10.0.1

- py/torch_tensorrt/dynamo/conversion/impl/embedding.py
Numpy has removed itemset api since 2.0, so need to replace the itemset call
>           offsets.itemset(-1, len_embed)
E           AttributeError: `itemset` was removed from the ndarray class in NumPy 2.0. Use `arr[index] = value` instead.
Collecting numpy (from torchvision==0.18.0->-r /__w/TensorRT/TensorRT/pytorch/tensorrt/tests/py/requirements.txt (line 8))
398
Downloading numpy-2.0.0rc2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.3 MB)
> replace itemset due to numpy version 2.0 removed itemset api

- py/torch_tensorrt/dynamo/conversion/impl/embedding.py
cherry pick https://github.com/pytorch/TensorRT/pull/2879 to release branch
Numpy has removed itemset api since 2.0, so need to replace the itemset call
offsets.itemset(-1, len_embed)
E AttributeError: itemset was removed from the ndarray class in NumPy 2.0. Use arr[index] = value instead.
> cherry pick pull/2879 to release/2.3 branch

- packaging/pre_build_script_windows.sh
- tests/py/requirements.txt
- Cherry-pick of #2821
- Cherry-pick
> cherry-pick: Add release flag for nightly build tag (#2821)

- .github/scripts/install-torch-tensorrt-windows.sh
- packaging/pre_build_script_windows.sh
- tests/py/requirements.txt
- Addresses CI error for missing `nvinfer.dll` on release branch
- CI fix
> fix: Missing nvinfer.dll in CI for Windows [`release/2.3`]

- tests/py/requirements.txt
Bump transformers version from 4.39 to 4.40
`FAILED models/test_models_export.py::test_bert_base_uncased - torch._dynamo.exc.InternalTorchDynamoError: 'ascii' codec can't decode byte 0xf0 in position 7043: ordinal not in range(128)`
> Bump transformers version from 4.39 to 4.40

- .github/workflows/build-test-linux.yml
- .github/workflows/build-test-windows.yml
- py/torch_tensorrt/dynamo/runtime/_PythonTorchTensorRTModule.py
- py/torch_tensorrt/dynamo/runtime/_TorchTensorRTModule.py
- tests/py/dynamo/models/test_hf_generate_dynamic.py
- Cherry-pick of #2876
- Generative inference with HF text generation models such as gpt2 can fail if graph segmentation causes a symbolic integer to be passed from Torch to TRT, since the Torch output is an integer, while TRT expects a tensor
- Added logic to the modules to address this case
- Added test cases to validate generation with both Python and C++ runtimes
- [ x ] New and existing unit …
> fix: Repair integer inputs in dynamic shape cases

- core/conversion/converters/impl/select.cpp
- tests/core/conversion/converters/test_slice.cpp
Adds converter support for aten::flip https://pytorch.org/docs/stable/generated/torch.flip.html
> feat: TS Add converter support for aten::flip

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- tests/py/dynamo/conversion/test_convolution_aten.py
- tests/py/dynamo/conversion/test_split_aten.py
Updated and added test cases for dynamic shape of split function
Add dynamic shape support tag in function decorator of converter
> Dynamic support for split

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- tests/py/dynamo/conversion/test_sub_aten.py
Add dynamic shape test for sub and supports_dynamic_shapes=True flag
> feat: Add dynamic shape support for sub

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- tests/py/dynamo/conversion/test_copy_aten.py
- tests/py/dynamo/conversion/test_sqrt_aten.py
Add dynamic shape support for aten sqrt and copy operation 
> feat: dynamic shapes support for sqrt and copy

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- tests/py/dynamo/conversion/test_ge_aten.py
- tests/py/dynamo/conversion/test_gt_aten.py
Add dynamic shape support to aten ops gt/ge
> add dynamic shape support for aten.ops.gt and aten.ops.ge

- .github/workflows/build-test-linux.yml
- dev_dep_versions.yml
- docsrc/index.rst
- examples/dynamo/README.rst
- examples/dynamo/vgg16_fp8_ptq.py
- examples/int8/training/vgg16/requirements.txt
- packaging/pre_build_script.sh
- py/torch_tensorrt/_enums.py
- py/torch_tensorrt/dynamo/_compiler.py
- py/torch_tensorrt/dynamo/_defaults.py
- py/torch_tensorrt/dynamo/backend/backends.py
- py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py
- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/__init__.py
- py/torch_tensorrt/dynamo/conversion/impl/quantize.py
- py/torch_tensorrt/dynamo/lowering/__init__.py
- py/torch_tensorrt/dynamo/lowering/_remove_sym_nodes.py
- py/torch_tensorrt/dynamo/lowering/passes/_aten_lowering_pass.py
- py/torch_tensorrt/dynamo/lowering/passes/remove_detach.py
- tests/py/dynamo/conversion/harness.py
- tests/py/dynamo/models/test_models_export.py
- tests/py/dynamo/testing_utilities.py
- versions.py
> chore: cherry-pick FP8

- .github/workflows/build-test-linux.yml
- .github/workflows/build-test-windows.yml
- .github/workflows/docgen.yml
- .github/workflows/linux-test.yml
- .github/workflows/windows-test.yml
Cancel the in-progress ci build when a new commit is pushed
too many ci/cd is running in parallel and wasted lots of runner resources
> Cancel in-progress ci build when a new commit is pushed

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- tests/py/dynamo/conversion/test_split_aten.py
> chore: Dynamic support for split (#2871) into main

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/normalization/ops.py
- tests/py/dynamo/conversion/test_group_norm_aten.py
- tests/py/dynamo/conversion/test_layer_norm_aten.py
Add dynamic shape support for layer_norm/group_norm/native_group_norm
> Add dynamic shape support for layer_norm/native_group_norm/group_norm

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- tests/py/dynamo/conversion/test_neg_aten.py
Add test case for dynamic shape input of aten.neg ops
Replaced output_dtypes arg in run_test_with_dynamic_shape() with check_dtype to handle
integer type of dynamic shape input test case.
> feat: dynamic shapes support for neg ops

- py/torch_tensorrt/dynamo/lowering/_decompositions.py
- tests/py/dynamo/lowering/test_decompositions.py
> empty_stride decomposition

- py/torch_tensorrt/dynamo/conversion/ops_evaluators.py
- tests/py/dynamo/conversion/test_empty_aten.py
In this PR I am facing issue in the test case of 
```
(
"empty_four_dimension_memformat",
[1, 2, 2, 1],
torch.float32,
"cuda",
torch.channels_last,
),
(
"empty_five_dimension_memformat",
[1, 2, 2, 2, 1],
torch.float32,
"cuda",
torch.channels_last_3d,
),
```
In the `TRTInterpreter.run()`, the stride of the empty_tensor  
`torch.ops.aten.empty.memory_format([1,2,2,1], dtype = torch.int32, memory_format = torch.channels_last)` 
is (4,1,2,2) (the desired torch output. This is an evaluator so could check the output in this [line](https://github.com/pytorch/TensorRT/blob/main/py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py#L308) - 
However when it comes to [line](https://github.com/pytorch/TensorRT/blob/main/tests/py/dynamo/conversion/harness.py#L149) the stride is (4,2,1,1). This is the …
> empty_memory_format evaluator

- core/conversion/converters/impl/layer_norm.cpp
- tests/core/conversion/converters/test_layer_norm.cpp
Update the aten::layer_norm converter to use INormalizationLayer. Resolves warning about precision:
`WARNING: [Torch-TensorRT TorchScript Conversion Context] - Running layernorm after self-attention in FP16 may cause overflow. Exporting the model to the latest available ONNX opset (later than opset 17) to use the INormalizationLayer, or forcing layernorm layers to run in FP32 precision can help with preserving accuracy.`
More closely matches behavior of onnx-tensorrt https://github.com/onnx/onnx-tensorrt/blob/main/builtin_op_importers.cpp#L2270
Covered by existing aten::layer_norm converter tests (updated to remove reshape which invalidates test).
- New …
> chore: Update layer_norm converter to use INormalizationLayer

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- tests/py/dynamo/conversion/test_elu_aten.py
- tests/py/dynamo/conversion/test_hard_sigmoid_aten.py
- tests/py/dynamo/conversion/test_leaky_relu_aten.py
- tests/py/dynamo/conversion/test_softplus_aten.py
Add dynamic shape support for leaky_relu/elu/hard_sigmoid/softplus
> Add dynamic shape support for leaky_relu/elu/hard_sigmoid/softplus

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/unary/ops.py
- tests/py/dynamo/conversion/test_dropout_aten.py
Support `native_dropout` dynamo converter.
Per [the schema](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/native_functions.yaml#L283), this function returns two tensors. The first is `output` and the other is `mask`. For inference, i.e., `train` is not `True` or `None`, whatever the `p` is, it always returns `input` and all `True`s.
Fixes #2494 
> feat: support `native_dropout` dynamo converter

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/select.py
- tests/py/dynamo/conversion/test_index_put_aten.py
I have implemented the `aten::index_put` operation using the `add_scatter` layer with `trt.ScatterMode.ND`. However, I was unable to implement the `accumulate=True` case, which is currently handled by the validator.
Fixes # ([issue](https://github.com/pytorch/TensorRT/issues/2544))
> feat: support aten index_put converter for accumulate=False

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/shuffle.py
- py/torch_tensorrt/dynamo/utils.py
- tests/py/dynamo/conversion/harness.py
- tests/py/dynamo/conversion/test_resize_aten.py
Support converter for `aten.resize_` operation: https://pytorch.org/docs/stable/generated/torch.Tensor.resize_.html#torch.Tensor.resize_
One critical aspect of this operation is handling cases where the target size (output size) is larger than the input tensor size. When `the target size` is larger than `the input tensor size`, the values of the additional elements are unpredictable. In PyTorch, these additional elements are not initialized, which can result in values that are close to `zero` but are not guaranteed to be `zero`.
In the converter developed for this PR, the additional elements are initialized to `zero` using `numpy.zeros`. While this approach ensures a predictable output, it does not exactly replicate the behavior of PyTorch, where the values of the additional elements are …
> feat: support aten.resize_ converter

- docker/Dockerfile
> fix the docker build failure on main

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- tests/py/dynamo/conversion/test_amax_aten.py
- tests/py/dynamo/conversion/test_amin_aten.py
- tests/py/dynamo/conversion/test_max_aten.py
- tests/py/dynamo/conversion/test_min_aten.py
- tests/py/dynamo/conversion/test_prod_aten.py
- tests/py/dynamo/conversion/test_sum_aten.py
add dynamic shape support for amax/amin/max/min/prod/sum
> add dynamic shape support for amax/amin/max/min/prod/sum

- examples/dynamo/vgg16_fp8_ptq.py
Fix a bug in `vgg16_fp8_ptq.py` example.
Fixes #2932 
> fix: bug in vgg16_fp8_ptq example

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- tests/py/dynamo/conversion/test_acos_aten.py
- tests/py/dynamo/conversion/test_asin_aten.py
- tests/py/dynamo/conversion/test_cosh_aten.py
- tests/py/dynamo/conversion/test_sinh_aten.py
- tests/py/dynamo/conversion/test_tan_aten.py
Support dynamic shapes for for tan, sinh, cosh, asin and acos operations
> feat: dynamic shape support for tan, sinh, cosh, asin and acos

- tests/core/conversion/converters/BUILD
- tests/core/conversion/evaluators/BUILD
- tests/core/runtime/BUILD
- Add back missing `select` calls in Bazel `BUILD`s
> fix: Add missing select in Bazel BUILD

- py/torch_tensorrt/ts/ptq.py
Fix use_cache flag usage. We could actually remove use_cache flag and use cache if a user provides `cache_file`. But this would affect the existing workflows and backwards compatibility. So, changes are intentionally minimal here. 
Fixes https://github.com/pytorch/TensorRT/issues/2960
> chore: fix use_cache flag

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- tests/py/dynamo/conversion/test_bitwise_and_aten.py
- tests/py/dynamo/conversion/test_bitwise_not_aten.py
- tests/py/dynamo/conversion/test_bitwise_or_aten.py
- tests/py/dynamo/conversion/test_bitwise_xor_aten.py
- tests/py/dynamo/conversion/test_exp_aten.py
- tests/py/dynamo/conversion/test_expm1_aten.py
- tests/py/dynamo/conversion/test_log10.py
- tests/py/dynamo/conversion/test_log2.py
- tests/py/dynamo/conversion/test_log_aten.py
- tests/py/dynamo/conversion/test_recip_aten.py
Add dynamic shape support for bitwise_and/or/xor/not, exp/expm1/recip/log/log2/log10
> Add dynamic shape support for bitwise_and/or/xor/not, exp/expm1/recip/log/log2/log10

- .github/workflows/docgen.yml
We now templaterized the toolchains/ci_workspaces/WORKSPACE.x86_64.release.rhel.tmpl file, it requires the following two envs:
CHANNEL/CU_VERSION
in both linux, windows build pipeline, those two are populated correctly, however in doc gen pipeline, thoese two are not set.
```
http_archive(
name = "libtorch_pre_cxx11_abi",
build_file = "@//third_party/libtorch:BUILD",
strip_prefix = "libtorch",
urls = ["https://download.pytorch.org/libtorch/${CHANNEL}/${CU_VERSION}/libtorch-shared-with-deps-latest.zip"],
)
```
> Doc build pipeline issue fix

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/__init__.py
- py/torch_tensorrt/dynamo/conversion/impl/prelu.py
- py/torch_tensorrt/dynamo/lowering/_decomposition_groups.py
- tests/py/dynamo/conversion/test_prelu_aten.py
> Add support for prelu dynamo converter

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- tests/py/dynamo/conversion/test_eq_aten.py
- tests/py/dynamo/conversion/test_pow_aten.py
- tests/py/dynamo/conversion/test_remainder_aten.py
dynamic shape support for pow/mod/eq operator
> feat: dynamic shape support for pow/mod/eq operator

- py/torch_tensorrt/dynamo/conversion/impl/slice/ops.py
- tests/py/dynamo/conversion/test_slice_aten.py
I have just added the test cases, and not refactored `has_dynamic_shape` and `set_layer_name` since they are already part of https://github.com/pytorch/TensorRT/pull/2853
> dynamic shape for slice converter

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/squeeze.py
- tests/py/dynamo/conversion/test_squeeze_aten.py
It seems full dynamic shape for squeeze is not supported because data-dependent shape is used as input.
add_non_zero() was used to get dims to remove and it's result is used for reshape of input.
https://github.com/pytorch/TensorRT/commit/2cf4eaaae6abe2181dc45c942d4c76c7a3d12e5a#diff-7e6d7566192094882e7d98bfd423d08f49cf2d334c15cd3db12f4385ba82d3a1R51-R115
If dims for squeeze are static shape, operation is successful.
shape of x = (1, -1, 1, -1, 1)
torch.ops.aten.squeeze.dims(x, (0, 4))
If dims for squeeze are dynamic shape, there will be assert()
shape of x = (1, -1, 1, -1, 1)
torch.ops.aten.squeeze.dims(x, (0, 1))
AssertionError: We don't support squeeze dynamic dim.
More than one dynamic dim can be used if they are not squeezed.
Please delete options that are not relevant and/or add …
> feat: dynamic shape support for squeeze ops

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/pool.py
- tests/py/dynamo/conversion/test_pool_aten.py
Dynamic shapes support for aten avg_pool1d, avg_pool2d and avg_pool3d
> feat: support dynamic shapes for avg poolNd

- README.md
- WORKSPACE
- core/ir/Input.cpp
- dev_dep_versions.yml
- docker/README.md
- examples/dynamo/requirements.txt
- packaging/pre_build_script_windows.sh
- packaging/smoke_test_script.sh
- py/ci/Dockerfile.ci
- py/requirements.txt
- pyproject.toml
- tests/py/requirements.txt
- toolchains/ci_workspaces/WORKSPACE.win.release.tmpl
- toolchains/ci_workspaces/WORKSPACE.x86_64.release.rhel.tmpl
> [WIP] upgrade to public TRT 10.1.0.27

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- tests/py/dynamo/conversion/test_linear_aten.py
Dynamic shape support for aten.linear 
When using `torch.randn` for `weight` initialization, an assertion error occurs. 
```
AssertionError: Tensor-likes are not close! 
Mismatched elements: 323 / 2304 (14.0%)
Greatest absolute difference: 0.015128374099731445 at index (1, 1, 139) (up to 0.001 allowed) 
Greatest relative difference: 3.242828845977783 at index (1, 1, 154) (up to 0.001 allowed)
```
However, no error occurs with `torch.rand` initialization. 
This is likely due to a numerical error, but I haven't pinpointed the exact cause yet.
> feat: support dynamic shape for aten.linear

- py/torch_tensorrt/dynamo/lowering/_decompositions.py
- tests/py/dynamo/lowering/test_decompositions.py
The issue in this PR is for cases where there is index collision. Example of such cases-
`scatter_add(input_tensor = torch.zeros(3,5), dim=1, index_tensor = torch.tensor([[0, 1, 2, 0]]).cuda(), src_tensor = torch.tensor([[1, 2, 3, 1]], dtype=torch.int32).cuda())`
Looks like straighforward decomposition by stacking the src_tensor would not work, since it would again lead to collision for some cases.
The better way to implement is to do converter implementation and allot the values using advanced indexing.
Working on this now.
> scatter_add_decomposition

- tests/py/dynamo/lowering/test_decompositions.py
assertEquals is deprecated in TestCase in python 3.12
should use assertEqual instead
> assertEquals is deprecated in TestCase in Python 3.12

- py/torch_tensorrt/dynamo/conversion/impl/normalization/ops.py
- tests/py/dynamo/conversion/test_group_norm_aten.py
- [ x] My code follows the style guidelines of this project (You can use the linters)
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas and hacks
- [ x] I have added tests to verify my fix or my feature
- [ …
> Group norm bug fix

- .github/workflows/release-linux.yml
- .github/workflows/release-wheel-linux.yml
fix the build name issue:
BUILD_VERSION: this is the our torch_tensorrt version
PYTORCH_VERSION: this is the torch version
most of the time torch_tensorrt and torch version are the same
but in case in release2.3: BUILD_VERSION is 2.3.0 PYTORCH_VERSION:2.3.1
hence here make the change so that it is clear.
> fix the artifacts name issue

- .github/workflows/release-wheel-linux.yml
fix the build name issue:
BUILD_VERSION: this is the our torch_tensorrt version
PYTORCH_VERSION: this is the torch version
most of the time torch_tensorrt and torch version are the same
but in case in release2.3: BUILD_VERSION is 2.3.0 PYTORCH_VERSION:2.3.1
hence here make the change so that it is clear.
> Fix the build name issue: cherry pick from 3041 back to main

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/pool.py
- tests/py/dynamo/conversion/test_adaptive_avgpool_aten.py
Support dynamic shapes for `aten.adaptive_avg_pool1d`, `aten.adaptive_avg_pool2d`, and `aten.adaptive_avg_pool3d`. However, dynamic shapes are only supported for the `batch` dimension in `adaptive_avg_pool1d`, and for both the `batch` and `channel` dimensions in `adaptive_avg_pool2d` and `adaptive_avg_pool3d`.
> feat: dynamic shape support for adaptive_avg_poolNd (partially)

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/select.py
- tests/py/dynamo/conversion/test_select_aten.py
Support dynamic shapes for aten.select.int. As shown below, since the arguments dim and index for select.int are int and not list, no reshaping is required.
```
- func: select.int(Tensor(a) self, int dim, SymInt index) -> Tensor(a)
variants: function, method
device_check: NoCheck
device_guard: False
dispatch:
CompositeExplicitAutograd: select_symint
SparseCsrCPU, SparseCsrCUDA: select_sparse_csr
NestedTensorCPU, NestedTensorCUDA: select_nested
tags: core
```
> feat: dynamic shape support for aten.select.int

- tests/py/dynamo/models/test_export_serde.py
Pytorch had export serde bugs which were fixed in nightly. This PR re-enables the disabled tests.
> chore: re-enable serde tests

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/topk.py
- py/torch_tensorrt/dynamo/utils.py
- tests/py/dynamo/conversion/test_any.py
- tests/py/dynamo/conversion/test_sort_aten.py
- tests/py/dynamo/conversion/test_trunc_aten.py
dynamic shape support for any/sort/trunc ops
> chore: dynamic shape support for any/sort/trunc ops

- core/runtime/execute_engine.cpp
> chore: bug fix in runtime

- py/torch_tensorrt/_compile.py
- py/torch_tensorrt/dynamo/__init__.py
- py/torch_tensorrt/dynamo/_compiler.py
- py/torch_tensorrt/dynamo/_defaults.py
- py/torch_tensorrt/dynamo/_settings.py
- py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py
- py/torch_tensorrt/dynamo/conversion/_conversion.py
- py/torch_tensorrt/dynamo/runtime/_PythonTorchTensorRTModule.py
- py/torch_tensorrt/dynamo/runtime/_TorchTensorRTModule.py
- tests/py/dynamo/conversion/harness.py
- tests/py/dynamo/models/test_dtype_support.py
- tests/py/dynamo/models/test_models_export.py
- tests/py/dynamo/runtime/conftest.py
- tests/py/dynamo/runtime/test_convert_module_to_trt_engine.py
- tests/py/dynamo/runtime/test_lazy_engine_init.py
- tests/py/ts/api/test_collections.py
Allows engines to not be setup immediately after compilation but all at once before the module is returned back to the user.
Fixes #2673 
> feat: Lazy engine initialization

- tests/modules/custom_models.py
- tests/py/ts/api/test_collections.py
- tests/py/ts/models/test_models.py
> bugfix: WAR disable BERT TS test

- tests/py/dynamo/models/test_export_kwargs_serde.py
> Renamed convert_exported_program_to_serialized_trt_engine

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/shuffle.py
- tests/py/dynamo/conversion/test_pixel_shuffle_aten.py
- tests/py/dynamo/conversion/test_pixel_unshuffle_aten.py
Support dynamic shapes for aten.pixel_suffle and aten.pixel_unshuffle. 
The overall logic is the same as before, but now shape information is retrieved using add_shape, and additional TensorRT operations are used as needed. As shown in the test cases, it fully supports dynamic shapes for all dimensions.
> feat: dynamic support for pixel_suffle and pixel_unshuffle

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/normalization/ops.py
- tests/py/dynamo/conversion/test_pdist_aten.py
np.triu_indices(dim0, k=1) is implemented by index calculation in loop layer when dim0 is dynamic shape
> chore: dynamic shape support for pdist ops

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/matmul.py
- py/torch_tensorrt/dynamo/lowering/_decomposition_groups.py
- tests/py/dynamo/conversion/test_matmul_aten.py
The existing code already supports it. It's just not registered and get lowered.
> feat: Support `aten.dot` dynamo converter

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/pad.py
- tests/py/dynamo/conversion/test_pad_aten.py
Added dynamic shape support for the following padding operations:
- `aten.constant_pad_nd`
- `aten.reflection_pad1d`
- `aten.reflection_pad2d`
- `aten.reflection_pad3d`
- `aten.replication_pad1d`
- `aten.replication_pad2d`
- `aten.replication_pad3d`
- `aten._pad_circular`
- `aten.pad`
A commonly used function, `get_padded_shape_tensors`, has been introduced to adjust the dimensions of the input tensor to account for padding in various padding modes. This function simplifies the handling of dynamic shapes across different padding operations.
> feat: dynamic shape support for pad ops

- py/torch_tensorrt/dynamo/_refit.py
- py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py
- py/torch_tensorrt/dynamo/conversion/_conversion.py
- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- py/torch_tensorrt/dynamo/runtime/_PythonTorchTensorRTModule.py
- py/torch_tensorrt/dynamo/runtime/_TorchTensorRTModule.py
- tests/py/dynamo/models/test_model_refit.py
Added refit acceleration to existing refit pipeline. 
During the first time of compilation, the interpreter will cache the weight name mapping between weights in TRT engine and weights in state_dict. The compiler then will do a tentative refit to test whether fast refit is success or not. If not, the caching will be removed. Later on, during refitting, if this mapping cache is detected, the re-interpretation of the module is skipped. 
If the fast refit fails, the refitter falls back to the regular refit, which re-interprets the module and does refitting accordingly.
- [ x] My code follows the style guidelines of this project (You can use the linters)
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas and hacks
- [ …
> Added refitting acceleration

- examples/dynamo/mutable_torchtrt_module_example.py
Small changes to the refit example 
- Small refactor
> refactor: Use HF to download the LoRA

- py/torch_tensorrt/dynamo/conversion/impl/pad.py
- tests/py/dynamo/conversion/test_pad_aten.py
Adjust reflection pad test cases to prevent runtime errors due to padding size exceeding input dimensions
- These changes ensure that the padding size remains smaller than the corresponding input dimensions, as reflection padding requires sufficient input data to reflect. Padding size must be limited by the input dimension to avoid runtime errors like "Padding size should be less than the corresponding input dimension".
> fix: Adjust reflection pad test cases to prevent runtime errors

- py/torch_tensorrt/dynamo/runtime/_MutableTorchTensorRTModule.py
```python
import torch_tensorrt as torchtrt
/__w/_temp/conda_environment_10423996349/lib/python3.9/site-packages/torch_tensorrt/__init__.py:137: in <module>
from torch_tensorrt.dynamo.runtime._MutableTorchTensorRTModule import (
/__w/_temp/conda_environment_10423996349/lib/python3.9/site-packages/torch_tensorrt/dynamo/runtime/_MutableTorchTensorRTModule.py:40: in <module>
class MutableTorchTensorRTModule(object):
/__w/_temp/conda_environment_10423996349/lib/python3.9/site-packages/torch_tensorrt/dynamo/runtime/_MutableTorchTensorRTModule.py:61: in MutableTorchTensorRTModule
Set[torch.dtype | dtype] | Tuple[torch.dtype | dtype]
E   TypeError: unsupported operand type(s) for |: 'type' and 'EnumMeta'
```
Type union operator was not supported on Python 3.9 since it's introduced on Python …
> Fix TypeError in MutableTorchTensorRTModule on Python 3.9

- .github/workflows/build-test-linux.yml
- .github/workflows/build-test-windows.yml
- py/torch_tensorrt/dynamo/conversion/_TRTBuilderMonitor.py
- py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py
- pyproject.toml
Adds progress monitoring for the engine building phase
> feat: Adding live progress monitoring to the engine building phase

- py/torch_tensorrt/dynamo/conversion/impl/normalization/ops.py
- tests/py/dynamo/conversion/test_batch_norm_aten.py
Support ITensor type running_mean and running_var arguments for Batch Norm converter.
Fixes # ([issue](https://github.com/pytorch/TensorRT/issues/3074))
> feat: Add handling for ITensor mean and var in batch_norm

- examples/dynamo/requirements.txt
- packaging/pre_build_script.sh
- packaging/pre_build_script_windows.sh
- py/requirements.txt
- pyproject.toml
- tests/py/requirements.txt
> fix tensorrt dependencies issue

- tests/py/dynamo/lowering/test_decompositions.py
```python
FAILED lowering/test_decompositions.py::TestLowering::test_scatter_add_0_scatter_add_zero_dim_indexOne_constant - AttributeError: 'TestLowering' object has no attribute 'assertEquals'
```
> Fix assertEquals AttributeError on Python 3.12

- core/lowering/passes/unpack_scaled_dot_product_attention.cpp
- tests/core/conversion/converters/test_scaled_dot_product_attention.cpp
Fixes #3080 
The threshold is deleted for now, which makes the tests failed. It will be totally fixed after #3061 gets merged.
> fix: TS test_scaled_dot_product_attention 

- MODULE.bazel
- README.md
- core/conversion/converters/impl/batch_norm.cpp
- dev_dep_versions.yml
- docker/README.md
- packaging/pre_build_script_windows.sh
- packaging/smoke_test_script.sh
- py/ci/Dockerfile.ci
- pyproject.toml
- tests/core/conversion/converters/test_instance_norm.cpp
- tests/py/ts/api/test_classes.py
- toolchains/ci_workspaces/MODULE.bazel.tmpl
- toolchains/legacy/WORKSPACE.win.release.tmpl
- toolchains/legacy/WORKSPACE.x86_64.release.rhel.tmpl
> chore: Bump TRT version to 10.3.0.26

- core/runtime/BUILD
- core/runtime/CMakeLists.txt
- core/runtime/Platform.cpp
- core/runtime/Platform.h
- core/runtime/TRTEngine.cpp
- core/runtime/TRTEngine.h
- core/runtime/execute_engine.cpp
- core/runtime/register_jit_hooks.cpp
- core/runtime/runtime.h
- py/torch_tensorrt/_Device.py
- py/torch_tensorrt/__init__.py
- py/torch_tensorrt/_enums.py
- py/torch_tensorrt/_features.py
- py/torch_tensorrt/dynamo/runtime/_PythonTorchTensorRTModule.py
- py/torch_tensorrt/dynamo/runtime/_TorchTensorRTModule.py
- py/torch_tensorrt/runtime/_utils.py
- tests/py/core/test_classes.py
Saves the target platform as part of the TRTEngine Data. 
Fixes #3103
Fixes #3101
> feat: Save target platform as part of TRTEngine Metadata

- py/torch_tensorrt/_compile.py
There is a typo in the `convert_method_to_trt_engine` function in `_compile.py` causing a Python syntax error.
Adding a comma fixes the issue.
> Fix typo in _compile.py

- py/torch_tensorrt/dynamo/lowering/_decompositions.py
> Fixing slice scatter and select scatter decomposition

- examples/dynamo/engine_caching_bert_example.py
- examples/dynamo/engine_caching_example.py
- py/torch_tensorrt/dynamo/_compiler.py
- py/torch_tensorrt/dynamo/_defaults.py
- py/torch_tensorrt/dynamo/_engine_caching.py
- py/torch_tensorrt/dynamo/_settings.py
- py/torch_tensorrt/dynamo/backend/backends.py
- py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py
- py/torch_tensorrt/dynamo/conversion/_conversion.py
- py/torch_tensorrt/dynamo/utils.py
- tests/py/dynamo/conversion/test_bitwise_and_aten.py
- tests/py/dynamo/conversion/test_embedding_bag_aten.py
- tests/py/dynamo/conversion/test_index_select_aten.py
- tests/py/dynamo/models/test_dtype_support.py
- tests/py/dynamo/models/test_dyn_models.py
- tests/py/dynamo/models/test_engine_cache.py
- tests/py/dynamo/models/test_export_kwargs_serde.py
- tests/py/dynamo/models/test_export_serde.py
- tests/py/dynamo/models/test_models.py
- tests/py/dynamo/models/test_models_export.py
- tests/py/dynamo/runtime/test_001_streams.py
- tests/py/dynamo/runtime/test_002_lazy_engine_init.py
Engine caching feature. More details see: https://github.com/pytorch/TensorRT/discussions/2957
> feat: engine caching

- py/torch_tensorrt/dynamo/conversion/impl/pad.py
Exported programs with dynamic shapes often include aten.constant_pad_nd with the argument `pad` containing mixture of `int` and `TRTTensor` values. This makes `pad_before + pad_after` fails in `get_padded_shape_tensors`.
> fix: get_padded_shape_tensors can now handle dynamic pads

- py/torch_tensorrt/dynamo/_compiler.py
- tests/py/dynamo/models/test_export_kwargs_serde.py
Calling `convert_exported_program_to_serialized_trt_engine` with either `inputs=()` or `arg_inputs=()` is blocked by `AssertionError`. This is because the empty tuple is evaluated as `False` when it is implicitly casted to `bool` type.
> bugfix: allow empty tuple for `inputs` or `arg_inputs`

- core/runtime/Platform.cpp
- docsrc/conf.py
- docsrc/index.rst
- examples/dynamo/README.rst
- examples/dynamo/engine_caching_bert_example.py
- examples/dynamo/engine_caching_example.py
- examples/dynamo/refit_engine_example.py
- py/torch_tensorrt/dynamo/_compiler.py
- py/torch_tensorrt/dynamo/_engine_cache.py
- py/torch_tensorrt/dynamo/_refit.py
- py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py
- py/torch_tensorrt/dynamo/conversion/_conversion.py
- py/torch_tensorrt/dynamo/utils.py
- setup.py
- tests/py/dynamo/models/test_engine_cache.py
Adds a bunch of text explaining the two new refit features for 2.5
> docs: Adding words to the refit and engine caching tutorials

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/slice/ops.py
- tests/py/dynamo/conversion/test_chunk_aten.py
This validator is for the purpose of dynamic shape support
> chunk converter validator

- py/torch_tensorrt/fx/__init__.py
Removes the global logging setup (which is initialized at import time). Solves #3145
> fix: remove global logging setup

- core/runtime/register_jit_hooks.cpp
```python
import torch
import torch_tensorrt
model = torch.nn.ReLU().eval().cuda()
inputs = [torch.randn(1, 3, 224, 224, device="cuda")]
trt_model = torch_tensorrt.compile(
model,
ir="dynamo",
inputs=inputs,
enabled_precisions={torch.float},
min_block_size=1,
make_refitable=False,
cache_built_engines=False,
reuse_cached_engines=False,
)
torch_tensorrt.save(trt_model, "trt.ts", output_format="torchscript", inputs=inputs)
loaded_model = torch_tensorrt.load("trt.ts")
```
```
holywu@HOLYWU:~$ python3 test.py
Unable to import quantization op. Please install modelopt library (https://github.com/NVIDIA/TensorRT-Model-Optimizer?tab=readme-ov-file#installation) to add support for compiling quantized models
WARNING:torch_tensorrt.dynamo.utils:Could not detect the device on which the model exists. …
```
> register_jit_hooks: Remove confusing error message

- py/torch_tensorrt/dynamo/conversion/impl/elementwise/ops.py
- py/torch_tensorrt/dynamo/lowering/_decompositions.py
- py/torch_tensorrt/dynamo/utils.py
- tests/py/dynamo/lowering/test_decompositions.py
#2740 should be using this. Will change it once this PR is finalized
> scatter reduce decomposition

- py/torch_tensorrt/dynamo/_defaults.py
> chore: make engine caching opt-in feature

- pyproject.toml
- tests/py/dynamo/models/test_models_export.py
- tests/py/requirements.txt
> upgrade modelopt

- py/torch_tensorrt/dynamo/_compiler.py
- py/torch_tensorrt/dynamo/_refit.py
- py/torch_tensorrt/dynamo/conversion/_ConverterRegistry.py
- py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py
- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- py/torch_tensorrt/dynamo/conversion/ops_evaluators.py
- py/torch_tensorrt/dynamo/conversion/prims_ops_converters.py
- py/torch_tensorrt/dynamo/utils.py
- tests/py/dynamo/conversion/harness.py
- tests/py/dynamo/conversion/test_cumsum_aten.py
- tests/py/dynamo/conversion/test_embedding_bag_aten.py
- tests/py/dynamo/models/test_model_refit.py
> feat: cherry pick of Refit fixes

- py/torch_tensorrt/dynamo/_exporter.py
- tests/py/dynamo/models/test_export_serde.py
Fixes https://github.com/pytorch/TensorRT/issues/3189
> fix: Fix static arange export

- docsrc/index.rst
- examples/dynamo/README.rst
- examples/dynamo/converter_overloading.py
Small tutorial on how to overload converters in Torch-TensorRT
> docs: A tutorial on how to overload converters in Torch-TensorRT

- .github/workflows/linux-test.yml
- .github/workflows/nightlies.yml
- .github/workflows/windows-test.yml
extend the timeout-minutes in build/test from 60 min to 120 min
> extend the timeout-minutes in build/test from 60 min to 120 min

- .github/workflows/build-test-windows.yml
cherry pick #3218: extend windows build timeout from 60 min to 120 min
> cherry pick #3218: extend windows build timeout from 60 min to 120 min

- py/torch_tensorrt/dynamo/_compiler.py
- py/torch_tensorrt/dynamo/partitioning/_global_partitioner.py
- tests/py/dynamo/partitioning/test_global_partitioning.py
https://github.com/pytorch/TensorRT/issues/3157
> fix the global partitioner bug

- py/torch_tensorrt/dynamo/_compiler.py
- py/torch_tensorrt/dynamo/backend/backends.py
add arg require_full_compilation
> cherry pick #3193: add req_full_compilation_arg from main to release/2.5

- .github/workflows/build-test-windows.yml
- .github/workflows/release-windows.yml
Since https://github.com/pytorch/test-infra/pull/5722, the `substitute-runner` job failed to replace the runner due to the string changed. When running on G5 instance, the time spent on building the wheel were less than 10 mins, and the job could usually complete in less than 15 mins, like https://github.com/pytorch/TensorRT/actions/runs/10998678934/job/30537276131#step:11:1. But when running on G4dn instance, the time spent on building the wheel became more than 30 mins, and the job took around 1 hour to complete, like https://github.com/pytorch/TensorRT/actions/runs/11220833237/job/31189943670#step:12:1.
> chore: Make substitute-runner in Windows CI work again

- tests/py/dynamo/models/test_models_export.py
According to https://docs.nvidia.com/deeplearning/tensorrt/support-matrix/index.html#hardware-precision-matrix, FP8 precision is supported for SM 8.9 or later. Confirmed to pass the tests locally on RTX 4060 Ti.
> Run test_base_fp8 for compute capability 8.9 or later

- core/runtime/TRTEngine.cpp
- core/runtime/TRTEngine.h
- core/runtime/execute_engine.cpp
- py/torch_tensorrt/dynamo/runtime/_PythonTorchTensorRTModule.py
torch.cuda.current_stream()/c10::cuda::getCurrentCUDAStream() always returns default stream and it leads running enqueueV3() with default stream.
torch.cuda.set_stream/c10::cuda::setCurrentCUDAStream is required to set current stream when new stream is acquired from pool
Fixes #3190
> Fix for warning as default stream was used in enqueueV3

- docsrc/index.rst
- docsrc/tutorials/notebooks.rst
- examples/README.rst
- examples/dynamo/README.rst
- examples/dynamo/torch_compile_resnet_example.py
- examples/dynamo/torch_compile_stable_diffusion.py
- examples/dynamo/torch_compile_transformers_example.py
- examples/dynamo/torch_export_gpt2.py
- examples/dynamo/torch_export_llama2.py
> chore: doc updates

- core/lowering/passes/remove_unnecessary_casts.cpp
An error was reported on NVBug:
```
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] LoweringPasses.RemoveSingleUse0DTensorsFloorDivIntCorrectly
[  FAILED  ] LoweringPasses.RemoveSingleUse0DTensorsFloorDivFloatCorrectly
With log:
unknown file: Failure
C++ exception with description "
Schema not found for node. File a bug report.
Node: %7 : int = aten::floor_divide(%6, %0)
Input types:int, int
candidates were:
aten::floor_divide(Tensor self, Tensor other) -> Tensor
aten::floor_divide.Scalar(Tensor self, Scalar other) -> Tensor
aten::floor_divide.out(Tensor self, Tensor other, *, Tensor(a!) out) -> Tensor(a!)
aten::floor_divide.Scalar_out(Tensor self, Scalar other, *, Tensor(a!) out) -> Tensor(a!)
within the graph:
graph(%0 : int):
%6 : int = prim::Constant[value=7]()
%7 : int = …
```
> fix: change floordiv to divmod for `//tests/core/lowering:test_remove_unnecessary_casts`

- py/torch_tensorrt/dynamo/conversion/converter_utils.py
When compiling `facebook/bart-base` with Torch-TensorRT, I encountered an error similar to the one in [this issue](https://github.com/pytorch/TensorRT/issues/3184), where `aten_ops.scatter.src` fails within `impl.elementwise.eq`. Upon investigation, I found that the issue arises when a scalar Numpy value is used in a slice operation as a constant layer. The output of this constant layer, which has a shape of `()` (scalar), is passed into `aten_ops.scatter.src`, causing the error. To fix this, I modified the shape to `(1,)` to avoid the issue.
I confirmed that after the modification, the TensorRT engine is successfully obtained using the Torch-TensorRT backend with the following code:
```python
import torch
from transformers import BartTokenizer, BartModel
import torch_tensorrt
backend = …
```
> fix: expand dim for scalar numpy when freezing tensors to IConstantLayers

- py/torch_tensorrt/_compile.py
- tests/py/ts/api/test_classes.py
Fixes # (issue) #3259
Also added testcases to capture the issue
> fix  issue 3259

- tests/py/requirements.txt
torchvision has removed the constraint since https://github.com/pytorch/vision/pull/8594 so it's no longer a blocker.
> Remove numpy version constraint in test requirements

- py/torch_tensorrt/dynamo/partitioning/common.py
- py/torch_tensorrt/dynamo/utils.py
Fixes #3269
extract_var_range_info is used by unwrap_tensor_shape and construct_dynamic_input
for the unwrap_tensor_shape, it only needs min and max
for the construct_dynamic_input, it needs min, opt and max
So added a flag to mark whether opt val is optional or not.
If it is optional then if cannot get the opt val(if got exception), we can still continue
if it is not optional then it will raise Error(if got exception)
> fix issue#3269: unwrap tensor shape without opt val

- .github/scripts/filter-matrix.py
- .github/workflows/build-test-linux.yml
Currently Tensorrt does not support python 3.13, disable it for now.
> disable python 3.13 for linux

- py/torch_tensorrt/dynamo/conversion/impl/slice/base.py
Minor change for giving correct names for slice layers.
[Example]
* Before: `[SLICE]-[unknown_ir_ops.slice.Tensor]-[slice_tensor]`
* After: `[SLICE]-[aten_ops.slice.Tensor]-[slice_tensor]`
> chore: add source_ir in slice layer name

- py/torch_tensorrt/dynamo/runtime/_MutableTorchTensorRTModule.py
got the following test issue due to the upstream pytorch change:
```
except pickle.UnpicklingError as e:
>                           raise pickle.UnpicklingError(_get_wo_message(str(e))) from None
E                           _pickle.UnpicklingError: Weights only load failed. This file can still be loaded, to do so you have two options, [1mdo those steps only if you trust the source of the checkpoint[0m.
E                               (1) Re-running `torch.load` with `weights_only` set to `False` will likely succeed, but it can result in arbitrary code execution. Do it only if you got the file from a trusted source.
E                               (2) Alternatively, to load with `weights_only=True` please check the recommended steps in the following error message.
E …
```
> fix MutableTorchTensorRTModule load issue

- py/torch_tensorrt/ts/_compile_spec.py
Currently importing `torch_tensorrt` calls `_cuda_init`, which can fail, preventing torch_tensorrt being imported in environments without a (working) GPU. This makes it slow to import torch_tensorrt and isn't necessary. This change switches to determining the current devices when TensorRTCompileSpec is called rather than when it's defined.
> don't initialize cuda at import time

- py/torch_tensorrt/dynamo/_engine_cache.py
- tests/py/dynamo/models/test_engine_cache.py
Reimplemented the get_hash function for engine caching, which fixes the existing bug and is able to deal with isomorphic graphs.
> fix: get_hash function for engine caching

- py/torch_tensorrt/dynamo/lowering/_decompositions.py
`torch.export.default_decompositions()` will get the same opset of decompositions as `torch._decomp.core_aten_decompositions()`, which is what you get when `enable_experimental_decompositions=True`. That is unwanted in `enable_experimental_decompositions=False` path. We only need decompositions for CIA ops here.
> Get decompositions only for CIA ops

- py/torch_tensorrt/dynamo/conversion/impl/slice/ops.py
- py/torch_tensorrt/dynamo/utils.py
When compiling the `roberta-base` model from Hugging Face (https://huggingface.co/FacebookAI/roberta-base), a `TypeError` occurs in the `cumsum` operation. For static shape input, the default datatype of `np.zeros(new_dims)` function is `np.float64` which is not handled properly by the `create_constant` utility function.
Fixes # ([issue](https://github.com/pytorch/TensorRT/issues/3187))
```
File "/usr/local/lib/python3.10/dist-packages/torch_tensorrt/dynamo/conversion/aten_ops_converters.py", line 934, in aten_ops_cumsum
return impl.slice.cumsum(
File "/usr/local/lib/python3.10/dist-packages/torch_tensorrt/dynamo/conversion/impl/slice/ops.py", line 387, in cumsum
zero_trttensor = get_trt_tensor(ctx, zeros, f"{name}_initial_value")
File …
```
> fix: cumsum add_constant bug fix (add dtype for np zeros)

- .github/scripts/generate_binary_build_matrix.py
- .github/workflows/build-test-linux.yml
- .github/workflows/build-test-tensorrt-linux.yml
- .github/workflows/build-test-tensorrt-windows.yml
- .github/workflows/build-test-windows.yml
- .github/workflows/generate_binary_build_matrix.yml
- .github/workflows/release-linux.yml
- .github/workflows/release-windows.yml
change docker img from manylinux to manylinux2_28 to fix the error `version GLIBC_2.28 not found`. We currently use `pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@main` to build matrix. This PR replace the pytorch yml with ourselves' so that we can maintain and customize by ourselves.
> fix: change docker img from manylinux to manylinux2_28 for all CUDA versions

- core/runtime/execute_engine.cpp
//tests/cpp:test_runtime_thread_safety test fails inconsistently.
Currently mutex protects only enqueueV3(), it should protect setTensorAddress as they are part of the same operation.
Below logging confirms race condition. 
execute_engine() {
compiled_engine->exec_ctx->setTensorAddress()
+std::cout << gettid() << " setTensorAddress " << outputs[pyt_idx].data_ptr() << std::endl;
std::unique_lock<std::mutex> lock()
compiled_engine->exec_ctx->enqueueV3()
+std::cout << "enqueueV3" << std::endl;
759630 setTensorAddress 0xaeeffaa00
759626 setTensorAddress 0xaeeffba00
759624 setTensorAddress 0xaeeffca00
759631 setTensorAddress 0xaeeffda00
759629 setTensorAddress 0xaeeffea00
759627 setTensorAddress 0xaef5f5a00
759633 setTensorAddress 0xaef5f6a00
759628 setTensorAddress 0xaef5f7a00
759632 …
> fix: Correct mutex scope in execute_engine()

- py/torch_tensorrt/dynamo/conversion/impl/conv.py
- tests/py/dynamo/conversion/test_convolution_aten.py
Added a test case for convolution with ITensor weight and fixed a bug related to handling Conv1d weight unsqueezing in the converter.
Fixes # ([issue](https://github.com/pytorch/TensorRT/issues/3326))
> Add test case for ITensor weight in convolution and fix related bug

- core/runtime/TRTEngine.cpp
- core/runtime/TRTEngine.h
- core/runtime/execute_engine.cpp
- core/runtime/register_jit_hooks.cpp
- docsrc/index.rst
- examples/dynamo/pre_allocated_output_example.py
- py/torch_tensorrt/dynamo/runtime/_PythonTorchTensorRTModule.py
- py/torch_tensorrt/dynamo/runtime/_TorchTensorRTModule.py
- py/torch_tensorrt/runtime/__init__.py
- py/torch_tensorrt/runtime/_pre_allocated_outputs.py
- tests/py/dynamo/runtime/test_002_cudagraphs_cpp.py
- tests/py/dynamo/runtime/test_002_cudagraphs_py.py
- tests/py/dynamo/runtime/test_pre_allocated_outputs.py
Latency hiding by creating the output tensor for next output buffer
Fixes #3275 
> feat: Runtime output buffer optimization

- py/torch_tensorrt/dynamo/conversion/_ConverterRegistry.py
- py/torch_tensorrt/dynamo/conversion/impl/__init__.py
Improves the logging in the converter registry
> chore: adding additional logging to the converter registry system

- core/runtime/TRTEngine.cpp
- core/runtime/TRTEngine.h
- core/runtime/execute_engine.cpp
- py/torch_tensorrt/dynamo/runtime/_CudaGraphsTorchTensorRTModule.py
- py/torch_tensorrt/dynamo/runtime/_PythonTorchTensorRTModule.py
- py/torch_tensorrt/runtime/_weight_streaming.py
- tests/py/dynamo/runtime/test_004_weight_streaming.py
Add flag indicates to reevaluate the runtime settings when weight streaming budget is changed.
Fixes #3308
> fix: Record cudagraphs when weight streaming budget has changed

- py/torch_tensorrt/dynamo/conversion/__init__.py
- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- py/torch_tensorrt/dynamo/conversion/custom_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/elementwise/base.py
- py/torch_tensorrt/dynamo/conversion/impl/nccl_ops.py
- py/torch_tensorrt/dynamo/conversion/impl/select.py
- py/torch_tensorrt/dynamo/lowering/passes/_replace_complex_placeholder_to_tuple.py
- py/torch_tensorrt/dynamo/lowering/passes/fuse_distributed_ops.py
- pyproject.toml
- uv.lock
Precommit was clearly not run, assorted fixes and reorg. Some AIs for @apbose re: custom ops and some hardcoded special cases 
> chore: [NCCL] reorg and better error messages

- docsrc/user_guide/saving_models.rst
A small documentation fix in the usage example in `Saving models compiled with Torch-TensorRT`
A small documentation fix
> Fix usage example

- .github/scripts/generate-tensorrt-test-matrix.py
- README.md
- dev_dep_versions.yml
- packaging/smoke_test_script.sh
- py/ci/Dockerfile.ci
- pyproject.toml
- toolchains/ci_workspaces/MODULE.bazel.tmpl
- toolchains/legacy/WORKSPACE.win.release.tmpl
- toolchains/legacy/WORKSPACE.x86_64.release.rhel.tmpl
- uv.lock
> Bump TRT version to 10.7

- .github/scripts/generate-tensorrt-test-matrix.py
- .github/workflows/build-test-tensorrt-linux.yml
- .github/workflows/build-test-tensorrt-windows.yml
- toolchains/ci_workspaces/MODULE_tensorrt.bazel.tmpl
Trigger Actions to run multiple TRT versions weekly. Automatically pull new TRT versions and check them.
> feat: Trigger Actions to run multiple TRT versions weekly

- .github/workflows/assigner.yml
- .github/workflows/build-tensorrt-linux.yml
- .github/workflows/build-tensorrt-windows.yml
- .github/workflows/build-test-linux.yml
- .github/workflows/build-test-tensorrt-linux.yml
- .github/workflows/build-test-tensorrt-windows.yml
- .github/workflows/build-test-windows.yml
- .github/workflows/docker_builder.yml
- .github/workflows/linter.yml
- .github/workflows/linux-test.yml
- .github/workflows/nightlies.yml
- .github/workflows/release-linux.yml
- .github/workflows/release-wheel-linux.yml
- .github/workflows/release-wheel-windows.yml
- .github/workflows/release-windows.yml
- .github/workflows/windows-test.yml
> fix: CI errors on release 2.6

- .github/workflows/docker_builder.yml
- docker/README.md
Fix CI docker build error for release 2.6.
> fix: CI docker build error for release 2.6

- .bazelrc
- .github/workflows/docgen.yml
- CONTRIBUTING.md
- docker/Dockerfile
- docker/README.md
- docker/dist-build.sh
- docsrc/getting_started/installation.rst
- docsrc/getting_started/jetpack.rst
- noxfile.py
- packaging/env_vars.txt
- py/README.md
- py/ci/Dockerfile.ci
- setup.py
> chore: flip use_cxx11_abi naming

- .pre-commit-config.yaml
- cpp/include/torch_tensorrt/macros.h
- cpp/include/torch_tensorrt/ptq.h
- py/torch_tensorrt/ts/_compiler.py
- py/torch_tensorrt/ts/ptq.py
> [Cherry-pick] Deprecate torchscript frontend

- MODULE.bazel
- README.md
- docker/dist-build.sh
- docs/_downloads/0e30a6276601af7e5fc4d5166e2e3d37/torch_compile_advanced_usage.py
- docs/_downloads/2a9ac10f2667047a7f398d1593b7ca33/torch_export_gpt2.py
- docs/_downloads/3d4d74f6636d986f33167154f6553961/torch_export_cudagraphs.py
- docs/_downloads/418941399c146271a7b7728ba3059960/dynamo_compile_resnet_example.py
- docs/_downloads/7b7004dc2ea6f839be532665e16e0426/torch_export_llama2.py
- docs/_downloads/d6e1bb6ec5f884994554d9d12e37a0f6/torch_compile_resnet_example.py
- docs/_downloads/dfa60e8f9850fd7761f3e7da81304d32/torch_compile_transformers_example.py
- docs/_downloads/e1ef5a42560a98a132f56a79d0b66f79/dynamo_compile_advanced_usage.py
- docs/_downloads/e550c5f53cc43e11aa6da8cfb79b54df/dynamo_compile_transformers_example.py
- docs/v1.4.0/_downloads/418941399c146271a7b7728ba3059960/dynamo_compile_resnet_example.py
- docs/v1.4.0/_downloads/e1ef5a42560a98a132f56a79d0b66f79/dynamo_compile_advanced_usage.py
- docs/v1.4.0/_downloads/e550c5f53cc43e11aa6da8cfb79b54df/dynamo_compile_transformers_example.py
- examples/dynamo/torch_compile_advanced_usage.py
- examples/dynamo/torch_compile_resnet_example.py
- examples/dynamo/torch_compile_transformers_example.py
- examples/dynamo/torch_export_cudagraphs.py
- examples/dynamo/torch_export_gpt2.py
- examples/dynamo/torch_export_llama2.py
- py/requirements.txt
- py/torch_tensorrt/_Input.py
- py/torch_tensorrt/_enums.py
- py/torch_tensorrt/dynamo/conversion/_TRTBuilderMonitor.py
- py/torch_tensorrt/dynamo/conversion/impl/activation/ops.py
- py/torch_tensorrt/dynamo/utils.py
- py/torch_tensorrt/fx/test/converters/acc_op/test_where.py
- py/torch_tensorrt/fx/tracer/acc_tracer/acc_tracer.py
- pyproject.toml
Update versions across requirements.txt and README to reflect 2.6 release.
> chore: update release versions for 2.6

- .pre-commit-config.yaml
- cpp/include/torch_tensorrt/macros.h
- cpp/include/torch_tensorrt/ptq.h
- py/torch_tensorrt/ts/_compiler.py
- py/torch_tensorrt/ts/ptq.py
Deprecate the TS frontend, Dynamo can be used in conjunction with TorchScript to get the same deployment feature set + the extra operator support.  
> Deprecate torchscript frontend

- examples/dynamo/requirements.txt
- CVE-2024-11394
- References
https://nvd.nist.gov/vuln/detail/CVE-2024-11394
https://www.zerodayinitiative.com/advisories/ZDI-24-1515 https://github.com/pypa/advisory-database/tree/main/vulns/transformers/PYSEC-2024-229.yaml GHSA-hxxf-235m-72v3
> [oncall] Fix vulnerability in the transformers dependency for examples/dynamo

- tools/perf/perf_run.py
Add `--use_python_runtime` and `--enable_cuda_graph` args to the perf run script.
> feat: add `--use_python_runtime` and `--enable_cuda_graph` args to the perf run script

- examples/dynamo/auto_generate_plugin.py
- py/torch_tensorrt/dynamo/conversion/plugins/__init__.py
- py/torch_tensorrt/dynamo/conversion/plugins/_custom_op.py
- py/torch_tensorrt/dynamo/conversion/plugins/_generate_plugin.py
- py/torch_tensorrt/dynamo/conversion/plugins/_generate_plugin_converter.py
- pyproject.toml
- tests/py/dynamo/conversion/test_automatic_plugin.py
- tests/py/dynamo/conversion/test_automatic_plugin_with_attrs.py
This PR introduces a new feature which enables generating automatic plugin generation using TensorRT QDP feature.
> feat: Automatically generate QDP plugins

- py/torch_tensorrt/dynamo/conversion/_ConverterRegistry.py
- py/torch_tensorrt/dynamo/runtime/_MutableTorchTensorRTModule.py
This PR changed `List[Any], Dict[str, int] | None` to `Union[List[Any], Dict[str, int], None]`
Python 3.9 and earlier don't support this way. For compatibility, we need to use the Union style.
> fix: typing issue in Python 3.9 and earlier

- .github/scripts/generate-tensorrt-test-matrix.py
- .github/workflows/linux-test.yml
- packaging/pre_build_script.sh
- packaging/pre_build_script_windows.sh
It seems due to the tensorrt version restriction (now it's tensorrt-cu12>=10.8.0,<10.9.0) in the pyproject file, which made all tests install the same TRT.
Fixes #3434
> fix: remove TRT version restriction

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/conv.py
- tests/py/dynamo/conversion/test_convolution_aten.py
This PR fixes an issue where padding values given as a single-element list (e.g., `[0]` and `[1]`) were not properly converted in `convNd`, leading to a TensorRT error:
```
ERROR:torch_tensorrt [TensorRT Conversion Context]:IConvolutionLayer::setPaddingNd: Error Code 3: API Usage Error (Parameter check failed, condition: (padding.nbDims == 2 || padding.nbDims == 3) && allDimsGtEq(padding, 0) && allDimsLtEq(padding, kMAX_PADDING). )
```
For the padding value `[1]`, this also caused shape mismatches, such as:
```
AssertionError: The values for attribute 'shape' do not match: torch.Size([1, 6, 32, 32]) != torch.Size([1, 6, 34, 34]).
```
If `padding` is `[0]`, it still triggers a TensorRT `paramater check failure error`, but the final output is correct. This is a minor issue that doesn’t …
> fix: conv parameter check failure

- core/util/Exception.h
- examples/int8/training/vgg16/requirements.txt
- noxfile.py
- tests/py/ts/ptq/test_ptq_dataloader_calibrator.py
- tests/py/ts/ptq/test_ptq_trt_calibrator.py
Some minor changes for the NGC container release
> DLFW changes 25.01 onwards

- examples/dynamo/auto_generate_plugin.py
- py/torch_tensorrt/dynamo/conversion/plugins/_custom_op.py
- py/torch_tensorrt/dynamo/conversion/plugins/_generate_plugin_converter.py
As part of DDS support functionality, this PR supports Output Allocator runtime mode for auto-generated plugins.
> feat: support Output Allocator runtime mode for plugin autogen

- examples/dynamo/vgg16_ptq.py
- tests/py/dynamo/models/test_models_export.py
Fixes https://github.com/pytorch/TensorRT/issues/3419
> fix: Fix PTQ export

- py/torch_tensorrt/dynamo/runtime/_CudaGraphsTorchTensorRTModule.py
- tests/py/dynamo/runtime/test_004_weight_streaming.py
Add support for structured inputs in CudaGraphsTorchTensorRTModule using torch's tree utilities to properly handle both args and kwargs input
Fixes #3406 
> fix: structured inputs for CudaGraphsTorchTensorRTModule

- core/runtime/TRTEngine.cpp
- core/runtime/TRTEngine.h
- core/runtime/register_jit_hooks.cpp
- py/torch_tensorrt/dynamo/runtime/_CudaGraphsTorchTensorRTModule.py
- py/torch_tensorrt/dynamo/runtime/_PythonTorchTensorRTModule.py
- py/torch_tensorrt/dynamo/runtime/_TorchTensorRTModule.py
- py/torch_tensorrt/dynamo/runtime/meta_ops/register_meta_ops.py
- py/torch_tensorrt/runtime/_cudagraphs.py
- py/torch_tensorrt/runtime/_weight_streaming.py
When cuda graphs and weigh streaming are used together, cuda graphs is destroyed after setting the weight streaming.
Weight streaming recreates the context and load new module. Destroying cudagraphs with old reference caused application crash. Fix is to move cuda graphs reset before the weight streaming setting. 
The timing of __del__ is not entirely predictable in python. Moved cudagraph reset logic from __del__ to dedicated reset_cudagraph method and it's called when exiting from CudaGraphsTorchTensorRTModule context block
Fixes #3460
> fix: Destory cuda graphs before setting weight streaming

- core/runtime/TRTEngine.cpp
- core/runtime/TRTEngine.h
- core/runtime/register_jit_hooks.cpp
- py/torch_tensorrt/dynamo/runtime/_CudaGraphsTorchTensorRTModule.py
- py/torch_tensorrt/dynamo/runtime/_PythonTorchTensorRTModule.py
- py/torch_tensorrt/dynamo/runtime/_TorchTensorRTModule.py
- py/torch_tensorrt/dynamo/runtime/meta_ops/register_meta_ops.py
- py/torch_tensorrt/runtime/_cudagraphs.py
- py/torch_tensorrt/runtime/_weight_streaming.py
Cherrypick #3461 for release/2.7
> Cherrypick #3461 for release/2.7

- pyproject.toml
Adds a setting to the pyproject.toml so that you do not need to manually install a torch-tensorrt build into a venv before running a test script 
> tool: uv setting to avoid the pip install -e

- .github/scripts/filter-matrix.py
- .github/scripts/generate-tensorrt-test-matrix.py
- .github/scripts/generate_binary_build_matrix.py
- .github/scripts/install-torch-tensorrt.sh
- .github/workflows/build-test-linux.yml
- .github/workflows/build-test-windows.yml
- py/torch_tensorrt/_features.py
- py/torch_tensorrt/dynamo/_refit.py
- py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py
- pyproject.toml
- setup.py
- tests/modules/custom_models.py
- tests/modules/hub.py
- tests/py/dynamo/models/test_engine_cache.py
- tests/py/dynamo/models/test_model_refit.py
- tests/py/dynamo/models/test_models.py
- tests/py/dynamo/models/test_models_export.py
- tests/py/dynamo/models/test_weight_stripped_engine.py
- tests/py/dynamo/runtime/test_mutable_torchtrt_module.py
- tests/py/requirements.txt
Reenabled Python 3.13 builds since TensorRT has 3.13 wheels available now for TensorRT 10.9.
> chore: reenable py313

- py/torch_tensorrt/dynamo/conversion/impl/elementwise/base.py
- tests/py/dynamo/conversion/test_binary_ops_aten.py
#3458 bf16 support for elementwise
> bf16 support for elementwise operation

- examples/dynamo/llama2_flashinfer_rmsnorm.py
- py/torch_tensorrt/dynamo/conversion/plugins/_generate_plugin.py
- py/torch_tensorrt/dynamo/conversion/plugins/_generate_plugin_converter.py
> feat: rmsnorm lowering

- py/torch_tensorrt/dynamo/conversion/impl/select.py
- tests/py/dynamo/conversion/test_index_put_aten.py
Previously, index_put converter passed all test cases but failed in a corner case where slicing is done using a multi-dimensional tensor together with None (e.g., tensor[None, idx_tensor]). This PR updates the converter to properly handle that case.
> fix: index_put converter to handle multi-shape slicing with None

- py/torch_tensorrt/_features.py
- py/torch_tensorrt/dynamo/_refit.py
- py/torch_tensorrt/dynamo/conversion/_ConversionContext.py
- py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py
- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- tests/py/dynamo/automatic_plugin/test_flashinfer_rmsnorm.py
> Enabled refit on Python 3.13

- examples/dynamo/llama2_flashinfer_rmsnorm.py
- py/torch_tensorrt/dynamo/conversion/plugins/_generate_plugin.py
- py/torch_tensorrt/dynamo/conversion/plugins/_generate_plugin_converter.py
Cherrypick #3440 for release/2.7
> Cherrypick #3440 for release/2.7

- .github/workflows/build-test-linux.yml
- tests/py/dynamo/automatic_plugin/test_automatic_plugin.py
- tests/py/dynamo/automatic_plugin/test_flashinfer_rmsnorm.py
- tests/py/requirements.txt
Cherrypick #3424 for release/2.7
> Cherrypick #3424 for release/2.7

- py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py
If the default -1 is passed in, it will output a warning.
> fix: l2_limit_for_tiling

- .github/workflows/build-test-linux.yml
- py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py
- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- tests/py/dynamo/backend/test_backend_compiler.py
- tests/py/dynamo/conversion/harness.py
- tests/py/dynamo/models/test_dtype_support.py
- tests/py/dynamo/models/test_models_export.py
- tests/py/requirements.txt
> chore: test bf16 fixes in CI

- py/torch_tensorrt/_features.py
- py/torch_tensorrt/dynamo/_refit.py
- py/torch_tensorrt/dynamo/conversion/_ConversionContext.py
- py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py
- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- py/torch_tensorrt/dynamo/conversion/impl/conv.py
- py/torch_tensorrt/dynamo/conversion/impl/deconv.py
- py/torch_tensorrt/dynamo/conversion/impl/quantize.py
- tests/py/dynamo/automatic_plugin/test_flashinfer_rmsnorm.py
- tests/py/dynamo/models/test_models.py
- tests/py/dynamo/models/test_models_export.py
> Cherrypick #3481 and #3445

- tests/py/dynamo/runtime/test_000_compilation_settings.py
This PR disables the test for hope igx platform for TRT > 10.8
> disabling dla args for hope igx platform

- docsrc/RELEASE_CHECKLIST.md
- docsrc/getting_started/installation.rst
- docsrc/user_guide/runtime.rst
Remove pre-cxx11 abi references in doc.
> chore: remove pre-cxx11 abi references in doc

- .github/scripts/install-torch-tensorrt.sh
- packaging/driver_upgrade.bat
- tests/py/requirements.txt
> Fix Windows CI for Release 2.7

- py/torch_tensorrt/_compile.py
- py/torch_tensorrt/dynamo/conversion/truncate_double.py
- py/torch_tensorrt/dynamo/utils.py
> chore: miscellaneous fixes for handling graph breaks

- py/torch_tensorrt/_features.py
- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/unsqueeze.py
- py/torch_tensorrt/dynamo/conversion/plugins/_generate_plugin.py
- py/torch_tensorrt/dynamo/conversion/plugins/_generate_plugin_converter.py
Tensorrt 10.3.0 does not support tensorrt plugin which causing failures.
> add feature gate for tensorrt plugin

- py/torch_tensorrt/dynamo/backend/backends.py
- py/torch_tensorrt/dynamo/conversion/_ConversionContext.py
> Minor fix - check for DTensor on igpu platform

- examples/dynamo/register_sdpa.py
- examples/dynamo/sdpa_converter.py
- examples/dynamo/torch_export_flux_dev.py
- py/torch_tensorrt/dynamo/lowering/__init__.py
> feat: Implement SDPA op converter / lowering pass as extensions

- .github/workflows/build-test-linux-x86_64.yml
nvidia-modelopt conditional support already added in the tests/py/requirements.txt 
remove from the test workflow script, as it will fail in py3.13 due to nvidia-modelopt does not support py3.13
> nvidia-modelopt dependency fix

- .github/scripts/install-torch-tensorrt.sh
- packaging/driver_upgrade.bat
> cherry pick 3505(windows driver upgrade) to release2.6.1

- examples/dynamo/aot_plugin.py
- py/torch_tensorrt/dynamo/conversion/plugins/_generate_plugin_converter.py
This PR demonstrates how to use AOT plugin in Torch-TensorRT
> feat: TensorRT AOT Plugin

- py/torch_tensorrt/dynamo/lowering/_decompositions.py
This PR extends the changes introduced in [PR #3535](https://github.com/pytorch/TensorRT/pull/3535) by applying similar handling for the `device`, which was previously missed.
In the original PR, the focus was on ensuring the correct propagation of `dtype` when using `torch.full_like`. However, `torch.full_like` also accepts a `device` argument, and if a `device` is explicitly passed, it may differ from the input tensor's `device`. This can result in the output tensor being created on a different device than the input, leading to device mismatch issues.
```Python
import torch
from torch.export._trace import _export
from torch_tensorrt.dynamo.lowering import get_decompositions
device0 = torch.device("cuda", index=0)
device1 = torch.device("cuda", index=1)
class MyModel(torch.nn.Module): …
```
> fix: handle device in the same way as dtype in `aten.full_like` decomposition

- .github/scripts/filter-matrix.py
- .github/workflows/build-test-linux-aarch64-jetpack.yml
- .github/workflows/build_wheels_linux_aarch64.yml
> fix the jetson nightly build check bug

- py/requirements.txt
- py/torch_tensorrt/_compile.py
- py/torch_tensorrt/_features.py
- py/torch_tensorrt/_utils.py
- py/torch_tensorrt/dynamo/_compiler.py
- pyproject.toml
- tests/py/dynamo/runtime/test_003_cross_compile_for_windows.py
The PR addresses the following-
1. Enables the windows cross compile feature based on if platform linux and libnvinfer_builder_resource_win.so.* is present
2. Adds this as a decorator for the cross compile API
3. This utility is also added for skip tests
> Cross compile guard

- examples/dynamo/aot_plugin.py
> Fix: fix aot plugin example docstring issue

- pyproject.toml
- uv.lock
Allows uv commands to build the system now. 
For example 
```sh 
uv run --group test --extra torchvision pytest tests/py/dynamo/models/test_models.py
uv run examples/dynamo/aot_plugin.py 
uv pip install -e . 
```
> feat: working uv pyproject.toml

- examples/apps/README.md
- py/torch_tensorrt/dynamo/conversion/_ConversionContext.py
- py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py
- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- py/torch_tensorrt/dynamo/conversion/impl/conv.py
- py/torch_tensorrt/dynamo/conversion/impl/deconv.py
- tools/perf/Flux/flux_perf.py
> Changed weight map to tensor and fix the refit bug

- py/torch_tensorrt/dynamo/runtime/_MutableTorchTensorRTModule.py
- tests/py/dynamo/runtime/test_mutable_torchtrt_module.py
fix the enabled_precisions error in the test:
```
if (
>           torch.float8_e4m3fn in self.additional_settings["enabled_precisions"]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
or torch.int8 in self.additional_settings["enabled_precisions"]
):
E       KeyError: 'enabled_precisions'
/opt/python/cp312-cp312/lib/python3.12/site-packages/torch_tensorrt/dynamo/runtime/_MutableTorchTensorRTModule.py:329: KeyError
```
> fix enabled_precisions error in test cases

- py/torch_tensorrt/_compile.py
- py/torch_tensorrt/dynamo/_compiler.py
- py/torch_tensorrt/dynamo/runtime/_MutableTorchTensorRTModule.py
- py/torch_tensorrt/ts/_compile_spec.py
- py/torch_tensorrt/ts/_compiler.py
py39 does not like |
E   TypeError: unsupported operand type(s) for |: 'type' and 'EnumMeta'
> py39 does not like | E   TypeError: unsupported operand type(s) for |: 'type' and 'EnumMeta'

- .github/scripts/install-cuda-aarch64.sh
- .github/scripts/install-torch-tensorrt.sh
- .github/workflows/build-test-linux-x86_64.yml
- .github/workflows/build-test-tensorrt-linux.yml
- .github/workflows/build-test-tensorrt-windows.yml
- .github/workflows/windows-test.yml
- MODULE.bazel
- packaging/pre_build_script.sh
- packaging/pre_build_script_windows.sh
- py/requirements.txt
- tests/py/requirements.txt
- tests/py/requirements_no_deps.txt
- toolchains/ci_workspaces/MODULE.bazel.tmpl
1. remove c118 support
2. move torchvision, timm, flashinfer-python to requirements_no_deps.txt
3. upgrade torchvision from 0.22.0 to 0.23.0
upgrade modelopt to the latest
> a few CI changes

- py/torch_tensorrt/_compile.py
- tests/py/dynamo/models/test_export_serde.py
> disable aoti format in windows

- .github/workflows/build-test-tensorrt-windows.yml
- .github/workflows/build-test-windows.yml
> Fix dynamo core test failure on Windows

- py/torch_tensorrt/dynamo/_refit.py
- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- py/torch_tensorrt/dynamo/conversion/impl/normalization/ops.py
- tests/py/dynamo/models/test_model_refit.py
> Closed the perf gap of resnet and enabled refit

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/elementwise/ops.py
- tests/py/dynamo/conversion/harness.py
- tests/py/dynamo/conversion/test_casts.py
Extend the cast converter to support BF16
Fixes https://github.com/pytorch/TensorRT/issues/3637
> feat: Add bf16 support to cast converter

- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- py/torch_tensorrt/dynamo/conversion/impl/slice/ops.py
- py/torch_tensorrt/fx/converters/converter_utils.py
This PR updates the `type_cast` helper function to ensure compatibility with TensorRT's strongly typed network mode.
`type_cast` used `add_identity()` followed by `set_output_type()` to perform the data type cast. However, in strongly typed mode, calling `set_output_type()` on the identity layer causes an error below:
```
ILayer::setOutputType: Error Code 3: API Usage Error (Parameter check failed, condition: !mNetwork->usingStronglyTyped(). INetworkLayer::setOutputType cannot be called for a strongly typed network.)
[graphShapeAnalyzer.cpp::checkCalculationStatusSanity::1962] Error Code 2: Internal Error (Assertion !isInFlight(p.second.symbolicRep) failed. )
```
`type_cast` is called by `expand` function in `torch_tensorrt/dynamo/conversion/impl/slice/ops.py` with dynamic dimension …
> fix: replace add_identity by add_cast for type cast

- py/torch_tensorrt/dynamo/_refit.py
- py/torch_tensorrt/dynamo/backend/backends.py
- tests/py/dynamo/models/test_export_serde.py
- tests/py/dynamo/models/test_models.py
> Refit debug patch

- py/torch_tensorrt/dynamo/lowering/_decompositions.py
- tests/py/dynamo/lowering/test_decompositions.py
This is with reference to #3448.
The error currently being faced is that-  (div_2, sym_size_int_3669, mul_102, mul_114, reshape_default_3, mul_213, div_113, mul_2962, clone_54, select_1, clone_67, expand_122, slice_16, clone_68, expand_123, mul_4869, expand_184,
expand_185, mul_7245, expand_246, expand_247, mul_9621, expand_308, expand_309, mul_11997, expand_370, expand_371, mul_14373, expand_432, expand_433, mul_16749, expand_494, expand_495, expand_556, expand_557, 
mul_21501, expand_618, expand_619, mul_23877, expand_680, expand_681, mul_26253, expand_742, expand_743, mul_28629, expand_804, expand_805, mul_31005, expand_866, expand_867, mul_33381, expand_928, expand_929, 
mul_35757, expand_990, expand_991, mul_38133, expand_1052, expand_1053, mul_40509, expand_1114, expand_1115, …
> slice scatter support for dynamic cases 

- py/torch_tensorrt/dynamo/conversion/impl/quantize.py
> fix the int8 quantization failure error

- .github/workflows/build-test-linux-aarch64-jetpack.yml
- pyproject.toml
- uv.lock
> cherry pick 3685: disable jetson build in ci

- py/torch_tensorrt/dynamo/_refit.py
- tests/py/dynamo/models/test_model_refit.py
- tests/py/dynamo/runtime/test_mutable_torchtrt_module.py
> cherry pick 3680: fix refit test bug

- .bazelrc
- setup.py
got the following error in CI:
`C:\actions-runner\_work\_temp\conda_environment_16299188041\lib\site-packages\torch\include\fmt\base.h(463): error C2338: static_assert failed: 'Unicode support requires compiling with /utf-8'`
> fix windows build failure: add /utf-8

- .github/scripts/generate-tensorrt-test-matrix.py
- MODULE.bazel
- dev_dep_versions.yml
- docker/README.md
- pyproject.toml
- toolchains/ci_workspaces/MODULE.bazel.tmpl
> upgrade tensorrt from 10.11 to 10.12

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/__init__.py
- py/torch_tensorrt/dynamo/conversion/impl/linear.py
- py/torch_tensorrt/dynamo/lowering/_decomposition_groups.py
- tests/py/dynamo/conversion/test_linear_aten.py
This PR reverts back **linear converter** because it shows perf improvements on BERT in fp16 if we take linear op as a whole. I didn't observe significant improvements on BERT fp32 though.
Fixes #3702
> feat: revert linear converter

- core/runtime/TRTEngine.cpp
- core/runtime/TRTEngine.h
- core/runtime/register_jit_hooks.cpp
- examples/dynamo/dynamic_memory_allocation.py
- py/torch_tensorrt/dynamo/_compiler.py
- py/torch_tensorrt/dynamo/_defaults.py
- py/torch_tensorrt/dynamo/_settings.py
- py/torch_tensorrt/dynamo/runtime/_ResourceAllocator.py
- py/torch_tensorrt/dynamo/runtime/_TorchTensorRTModule.py
- py/torch_tensorrt/dynamo/runtime/__init__.py
- uv.lock
Allows the allocation strategy to be set at build time, fixes some of the mode switching and cleans up some naming 
> Some fixes for the dynamic memory setting

- py/torch_tensorrt/dynamo/conversion/impl/conv.py
- py/torch_tensorrt/dynamo/conversion/impl/deconv.py
- tests/py/dynamo/conversion/test_convolution_aten.py
in conv1d/deconv1d, 
input_tensor is (N,C,H) ---> (N, C, H, 1)
if stride is 2, once we moved to 2d, it should be (2, 1) not (2, 2)
This bug is only appear when we have a conv1d/deconv1d with stride more than 1
> fix conv1d/deconv1d bug with stride more than 1

- py/torch_tensorrt/dynamo/conversion/_TRTInterpreter.py
- py/torch_tensorrt/dynamo/conversion/impl/normalization/ops.py
- py/torch_tensorrt/dynamo/lowering/_decompositions.py
- tests/py/dynamo/models/test_dtype_support.py
- tests/py/dynamo/models/test_dyn_models.py
- tests/py/dynamo/models/test_models.py
- tests/py/dynamo/models/test_models_export.py
> add test cases for strong typing

- examples/apps/flux_demo.py
- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/impl/elementwise/base.py
- py/torch_tensorrt/dynamo/lowering/_decomposition_groups.py
- py/torch_tensorrt/dynamo/lowering/_decompositions.py
- py/torch_tensorrt/dynamo/lowering/passes/accumulate_fp32_matmul.py
- tools/perf/Flux/benchmark.sh
- tools/perf/Flux/flux_perf.py
> Fixed SDPA slow down and linear slow down

- tests/py/dynamo/models/test_models_export.py
> remove breakpoint()

- py/requirements.txt
- tests/py/requirements.txt
> add typing_extensions as test dependencies which is required by modelopt

- py/torch_tensorrt/dynamo/conversion/impl/dynamic_block_quantize.py
We only gated the FP4 in the op level which is not enough.
we need to gate the entire dynamic_block_quantize.py
python examples/dynamo/torch_compile_resnet_example.py
```
File "/home/ubuntu/Desktop/lan/jetson_py310/lib/python3.10/site-packages/torch_tensorrt/dynamo/conversion/__init__.py", line 1, in <module>
from . import (
File "/home/ubuntu/Desktop/lan/jetson_py310/lib/python3.10/site-packages/torch_tensorrt/dynamo/conversion/aten_ops_converters.py", line 13, in <module>
from torch_tensorrt.dynamo.conversion import impl
File "/home/ubuntu/Desktop/lan/jetson_py310/lib/python3.10/site-packages/torch_tensorrt/dynamo/conversion/impl/__init__.py", line 1, in <module>
from torch_tensorrt.dynamo.conversion.impl import (
File "/home/ubuntu/Desktop/lan/jetson_py310/lib/python3.10/site-packages/t …
```
> Fix Jetson FP4 gate issue

- .github/scripts/install-cuda-aarch64.sh
Torch upstream requires nvshmem in aarch64.
> add nvshmem in aarch64

- py/torch_tensorrt/dynamo/conversion/aten_ops_converters.py
- py/torch_tensorrt/dynamo/conversion/converter_utils.py
- py/torch_tensorrt/dynamo/conversion/impl/normalization/ops.py
- py/torch_tensorrt/dynamo/lowering/_decomposition_groups.py
Pytorch decomposes `torch.ops.aten._native_batch_norm_legit.no_stats` into a bunch of aten ops, which makes it way slow. See the issue below for details.
Fixes #3731 
> fix: batch norm issue encountered in RAFT

- tests/py/dynamo/models/test_llm_models.py
- tools/llm/torchtrt_ext/sdpa_converter.py
> change llm model test from gemma3 to qwen to skip auth

- setup.py
- tests/modules/hub.py
- tests/py/dynamo/models/test_models.py
- tests/py/dynamo/models/test_models_export.py
1) timm does not work on tegra
add if timm not exist skip timm related test
2) dlfw ci does not support git hash fall back to use non git 
3) dlfw do not add torch tensorrt as requirements in setup.py 
4) remove hub.py download from torchvision and timm only download our own models
> dlfw related changes

- tests/py/dynamo/conversion/harness.py
> fix guard_fn issue

- py/torch_tensorrt/dynamo/_compiler.py
- py/torch_tensorrt/dynamo/conversion/impl/normalization/ops.py
- tools/perf/README.md
- tools/perf/benchmark.sh
- tools/perf/custom_models.py
- tools/perf/perf_run.py
- tools/perf/utils.py
> Same changes as #3812 chore: Add more models for benchmark and polish codes

- .github/scripts/filter-matrix.py
- .github/scripts/install-cuda-aarch64.sh
- .github/scripts/install-cuda-dss.sh
- .github/workflows/build_linux.yml
- MODULE.bazel
- packaging/pre_build_script.sh
- setup.py
- tests/py/dynamo/partitioning/test_hierarchical_partitioning.py
- toolchains/ci_workspaces/MODULE.bazel.tmpl
> fix a few ci issues
